clerk/clerk-docs

- src/pages/components/authentication/_meta.json
These three links point to nowhere when clicked:
and since they're repeated a bit lower in the menu, under "Organization Management", my guess is that they're left over there.
This PR removes them.
> Remove org Components from Authentication section

- src/pages/quickstarts/nextjs/app-router.mdx
- src/pages/quickstarts/nextjs/stable.mdx
- src/pages/sdk/next/with-clerk-middleware.mdx
This is very trivial, but the file name of the sample code in the heading(Add Middleware, Protecting Your Pages) is incorrect.
Middleware will not work properly if the file name is wrong.
It would be much appriciated if you could modify them.
> fix: file name typo

- src/pages/quickstarts/nextjs/app-router.mdx
While it is shown in the example as such there is no explicit recommendation to wrap the `<body>` with the `<ClerkProvider>`, this PR aims to add that recommendation and remove any potential ambiguity.
> Add a recommendation to wrap the body tag with the ClerkProvider

- .gitignore
- src/pages/_meta.json
- theme.config.tsx
This PR moves the following support sidebar items:
- Discord
- Twitter
To the top navbar in the form of icons.
It also removes the support email from the sidebar, which can be added to the footer in the near future if we like this idea.
> Move support items to navbar icons

- src/pages/reference-react/customization/_meta.json
- src/pages/reference-react/internals/use-clerk.mdx
- src/pages/reference-react/internals/use-session-list.mdx
- src/pages/reference-react/internals/use-session.mdx
- src/pages/reference-react/internals/use-sign-in.mdx
- src/pages/reference-react/internals/use-sign-up.mdx
- src/pages/reference-react/user-management/use-auth.mdx
- src/pages/reference-react/user-management/use-user.mdx
This PR makes sure that all reference docs use the same headers like:
- `useHook()`
- `<Comp/>`
- `fn()`
> chore: make reference docs headers more consistent

- src/pages/quickstarts/native/expo.mdx
Changes:
-- | Img
-- | --
Add disclaimer about the needed dependencies that needs to be manually added | ![image](https://github.com/clerkinc/clerk-docs/assets/28108272/5a533d6b-c83a-4b01-ab8c-399c907c772d)
Make instructions more on par with what Next.JS have now | ![image](https://github.com/clerkinc/clerk-docs/assets/28108272/0a77cb3b-be06-43b1-bf31-6e99fe53c19f)
I found the second one specially useful since I worked in many codebases where people would blindly copy the snippets as they were provided.
So now, even if someone copy it and just change the values, they're likely to do as Expo recommends &mdash; and even learn something new about it 🙂
> docs: use recommended practices of expo guides -- for EAS

- src/components/Table.tsx
- src/pages/reference-react/_meta.json
- src/pages/reference-react/general/_meta.json
- src/pages/reference-react/general/clerk-provider.mdx
I added a new docs page: https://clerk-docs-git-clerk-provider.clerkpreview.com/reference-react/general/clerk-provider
We should make sure to add the `allowRedirectOrigins` to [this page of the stable docs](https://clerk.com/docs/reference/clerk-react/clerkprovider)
> Create new <ClerkProvider/> docs page

- src/components/Table.tsx
- src/pages/_meta.json
- src/pages/reference-gatsby/_meta.json
- src/pages/reference-gatsby/with-server-auth.mdx
- src/pages/reference-js/overview.mdx
This PR documents the uniquely exported `withServerAuth` from the `gatsby-plugin-clerk` package.
https://clerk-docs-git-gatsby-reference.clerkpreview.com/reference-gatsby/with-server-auth
> Add Gatsby Reference Page

- src/pages/_meta.json
- src/pages/reference-react/general/clerk-provider.mdx
- src/pages/reference-remix/_meta.json
- src/pages/reference-remix/clerk-app.mdx
- src/pages/reference-remix/clerk-catch-boundary.mdx
`@clerk/remix` has two unique exports that we should document in our reference docs:
- `<ClerkApp/>`
- `ClerkCatchBoundary()`
This PR documents them both:
- https://clerk-docs-git-remix-reference.clerkpreview.com/reference-remix/clerk-app
- https://clerk-docs-git-remix-reference.clerkpreview.com/reference-remix/clerk-catch-boundary
> Add Remix Reference Page

- src/pages/reference-js/authentication/_meta.json
- src/pages/reference-js/authentication/sign-in.mdx
This PR builds on top of #100 to add `window.Clerk` examples for the JavaScript examples of Sign In components
> docs: add window.Clerk examples

- src/components/AuthProvidersCards.tsx
- src/pages/users/authentication-providers/overview.mdx
This PR:
- Restyles `AuthProviderCards` to match the current docs and `FrameworkCards`
- Adjusts the cards' grid to be responsive in a similar way to the homepage cards
> chore: restyle auth provider cards to match current docs

- src/components/Table.tsx
- src/pages/reference-react/general/clerk-provider.mdx
This PR: 
- changes the color of the table dividers to match the current docs
- fixes a small typo
> chore: change table divider color

- src/components/CodeBlockTabs.tsx
This PR:
- Adds styles to the dropdown for dark mode
- Closes the menu when clicking elsewhere on the page
https://github.com/clerkinc/clerk-docs/assets/133695690/477f539e-0fec-4a32-ad96-39a620e5ce79
> chore: restyle codeBlockTab dropdown menu

- src/pages/reference-js/_meta.json
- src/pages/reference-js/organization-invitation.mdx
- src/pages/reference-js/organization/invitations.mdx
This PR adds the reference docs for the organization's invitation and deep links existing methods into the page
Preview: https://clerk-docs-git-clerk-js-organization-invitation.clerkpreview.com/reference-js/organization-invitation
> chore: add organization invitation docs page

- src/components/AuthProvidersCards.tsx
- src/components/Cards.tsx
- src/components/FrameworkCards.tsx
- tailwind.config.js
This PR fixes the arrow hover animation for the `Cards`, `FrameworkCards`, and `AuthProviderCards` components to reverse correctly instead of resetting.
https://github.com/clerkinc/clerk-docs/assets/133695690/ce43e2da-1943-438a-9eb7-48b841bc1ab4
> fix: change arrow animation to reverse correctly

- src/components/AuthProvidersCards.tsx
- src/components/Cards.tsx
- src/components/FrameworkCards.tsx
- src/components/Hero.tsx
- tailwind.config.js
This PR:
- Adjusts the card background and font colors to match the current docs
- Adds those colors to the tailwind config
- Fixes the `Hero` image behavior (and [error](https://nextjs.org/docs/messages/react-hydration-error)) so it does not default to light mode on refresh
- Adjusts `Hero` text to match design
> DOCS-233: Change colors to match current docs

- src/pages/quickstarts/full-stack/remix.mdx
The current [Remix Quick Start](https://clerk.com/docs/quickstarts/get-started-with-remix) mentions to:
> Disable ErrorBoundary
> Currently we are unable to support ErrorBoundaryV2 but will support this when Remix V2 is in general release, make sure that it is set to false in your remix.config.js
However, it still preserves `v2_routeConvention: true,`
Then later in the tutorial it is suggesting to create /sign-in/$ and /sign-up/$ wildcard routes; however, it is using the routes nested by file structure which is V1 routing instead of nesting by file name which is V2.
See: https://remix.run/docs/en/1.17.1/file-conventions/routes-files#splat-routes
This results in errors like
> No routes matched location "/sign-in/abc123" since the splat/wildcard route is not being recognized.
Change file …
> Use V2_RouteConventions

- src/pages/quickstarts/full-stack/remix.mdx
The code snippet for the "Retrieve Full User" example was using `createClerkClient` without importing the function. This makes the snippet incomplete.
Up until that point in the guide the user is only familiar with these two import locations: "@clerk/remix" and "@clerk/remix/ssr.server", neither of which export `createClerkClient`.
**This means at this point in the guide the user is blocked and would not know how to import `createClerkClient`**
I saw from this [upgrade documentation](https://clerk.com/docs/upgrade-guides/upgrade-remix-from-1.x-to-2.x) that appropriate  import is: `import { createClerkClient } from '@clerk/remix/api.server'`
I added imports to the snippet
> fix: add import of createClerkClient to "Retrieve Full User" example

- src/pages/index.mdx
This PR changes the width of the `Card` containers on the homepage so their width stays consistent at breakpoints.
> DOCS-240: Fix homepage cards responsiveness issue

- CONTRIBUTING.md
- README.md
Expands the contributing docs to explain how the documentation content is rendered in more detail. This should help others make meaningful, high-quality contributions.
> feat(docs): Expand contributing documentation, cleanup README

- docs/references/react/use-user.mdx
Makes some minor updates to the `useUser()` reference docs, and adds a section on reloading user data.
> feat: add reload user data section to useUser reference

- docs/users/metadata.mdx
Pull forward the changes from https://github.com/clerkinc/clerk-docs/pull/151 rebased onto the new repository structure.
> docs: Update Ruby SDK examples.

- docs/custom-flows/email-password.mdx
In the image below the correct import source is "next/navigation".
> docs: add correct import source for App Router code examples

- docs/quickstarts/remix.mdx
We recently introduced the repo level config env variables for `Remix`, as we have for `Next.js`. This PR updates the remix + clerk docs to reflect that.
PS: we need to do a release for a fix for this feature so I'll merge this when that's done.
> feat: Add docs for remix repo level config

- .github/workflows/revalidate.yml
- CONTRIBUTING.md
Adds a workflow to trigger revalidation of changed docs pages. It does this by detecting changed files and sending the changed files list in a POST request to our `revalidate-docs` endpoint. If the `manifest.json` file is changed, it will send a request with `"paths": "*"`, which will trigger revalidation of every path.
Requires https://github.com/clerkinc/clerk-marketing/pull/715 to be merged into the assembly branch.
> feat: adds workflow to trigger revalidation of docs pages

- .github/workflows/revalidate.yml
Fix escaping when sending `"*"` to the revalidate endpoint.
> fix: escaping of wildcard character

- docs/quickstarts/setup-clerk.mdx
remove copy that mentions steps when written inside a `<Steps />` component, because the steps component already numbers each step
e.g. 'step 1' when inside a `<Steps />` component
reproduce on /docs/quickstarts/setup-clerk
> remove copy that mentions steps when written inside a <Steps /> component

- CONTRIBUTING.md
- docs/references/backend/sessions/verify-session.mdx
- docs/references/ruby/available-methods.mdx
The previous docs for /docs/references/ruby/available-methods had incorrect links and outdated information. 
This PR
- Migrate this page from Sanity to MDX
- Updates the content
- Fixes an incorrect heading on /docs/references/backend/sessions/verify-session 
- Adds missing brackets on a `<Table />` component in the CONTRIBUTING.md
The previous Ruby content (written in Sanity):
https://github.com/clerkinc/clerk-docs/assets/98043211/3df7f459-e91a-4bed-853f-a2eca9f613c0
The table held redundant as well as incorrect information (the first table heading is labeled incorrectly, the methods for some of the endpoints are incorrect). I removed this table and instead link to the endpoints within each corresponding heading.
> migrate "ruby/available-methods" from sanity to mdx

- docs/components/authentication/sign-up.mdx
The previous syntax was causing JSX to be rendered, and it was incorrect JSX syntax. This was causing a deployment failure.
This PR updates the syntax to be correct.
> fix: use correct syntax in table to solve rendering error

- docs/backend-requests/handling/nextjs.mdx
- docs/manifest.json
/docs/backend-requests/handling/nextjs has redundant and outdated information (see below)
This PR removes that outdated page altogether.
A PR in the Marketing Repo is redirect our old path "/docs/request-authentication/nextjs" to the new page with updated information: "/docs/references/nextjs/auth-middleware".
> remove nextjs from 'backend-requests/handling'

- docs/quickstarts/setup-clerk.mdx
The official React docs no longer push for CRA for installation. We can cut out mentionings of "Create React App" and just reference "React app"
> DOCS-258 Remove references to Create React App

- docs/manifest.json
- docs/users/build-your-own-ui.mdx
/docs/users/build-your-own-ui has redundant and outdated information (see below)
https://github.com/clerkinc/clerk-docs/assets/98043211/07364fbb-b5f1-439c-8101-e0914a700cf4
This PR removes that outdated page altogether.
[A PR in the Marketing Repo](https://github.com/clerkinc/clerk-marketing/pull/743) is redirecting our old path "/docs/users/build-your-own-ui" to the new page with updated information: "/docs/custom-flows/use-sign-up"
> remove page; redirects to new content

- CONTRIBUTING.md
This PR
- Updates the copy to use the correct component (was `<Table />` when it should have been `<Tables />`)
- Explains the use of `<Tables />` in more detail
- Removes the use of `HeadingsMeta`, as styling should solely be controlled by our marketing repo (and hence, by our internal contributors).
Related to [this PR](https://github.com/clerkinc/clerk-marketing/pull/745)
> update explanation of use of tables

- CONTRIBUTING.md
- docs/authentication/overview.mdx
- docs/authentication/set-up-your-application.mdx
- docs/quickstarts/setup-clerk.mdx
Currently, we have our old set up guide still being rendered, and also referenced, in our docs at /docs/authentication/set-up-your-application
I have reviewed it to ensure that all the information on this page is somehow replicated/updated in the new docs.
Most of the information is now located at /docs/authentication/configuration/sign-up-options
This PR
- adds more information to our "Setup Clerk" guide to better help guide users to the resources they will need when setting up an application. The authentication section is especially helpful, because it will navigate users to where the "set-up-your-application" information now lives.
- removes the page set-up-your-application from being rendered. Navigating to this old path will redirect to our /quickstarts/setup-clerk guide thanks to …
> DOCS-255 Consolidate setup guides

- docs/account-portal/custom-redirects.mdx
- docs/account-portal/getting-started.mdx
- docs/account-portal/overview.mdx
- docs/account-portal/user-profile-org-profile.mdx
- docs/manifest.json
I think fallback redirects are better on the "getting started" page, because its something users should set up and learn about when getting started with the account portal.  I also added a section about direct links to the account portal pages, with specific examples for each type of instance.
> code review

- docs/security/vulnerability-disclosure-policy.mdx
Let's throw these links in code snippets so that our link checker doesn't think we are trying to route out to them ?
The errors were:
https://accounts.clerk.dev/ found on https://clerk.dev/docs/security/vulnerability-disclosure-policy (403 - FORBIDDEN)
https://api.clerk.dev/ found on https://clerk.dev/docs/security/vulnerability-disclosure-policy (404 - NOT FOUND)
Let me know what you think.
> fix for broken link GH action

- docs/advanced-usage/manual-jwt.mdx
Fixed `docs/advanced-usage/manual-jwt.mdx` for proper usage of the word `tamper` (tamper *with it* rather than tamper *it*).
> Proper usage of the word `tamper`

- docs/advanced-usage/satellite-domains.mdx
- docs/authentication/components/overview.mdx
- docs/authentication/components/sign-in.mdx
- docs/authentication/components/sign-up.mdx
- docs/authentication/overview.mdx
- docs/manifest.json
- docs/organizations/create-component.mdx
- docs/organizations/overview.mdx
- docs/organizations/profile-component.mdx
- docs/organizations/switcher-component.mdx
- docs/quickstarts/nextjs.mdx
- docs/references/javascript/sign-in/authenticate-with.mdx
- docs/references/javascript/sign-up/sign-up.mdx
- docs/references/javascript/types/deleted-object.mdx
- docs/references/javascript/types/oauth-provider.mdx
- docs/references/javascript/types/oauth-strategy.mdx
- docs/references/javascript/types/public-user-data.mdx
- docs/references/javascript/types/redirect-options.mdx
- docs/references/javascript/user/user.mdx
- docs/users/overview.mdx
- docs/users/user-button.mdx
- docs/users/user-profile.mdx
/components houses information on Clerk's prebuilt components
However, we also had /authentication/components/overview which housed redundant information on the prebuilt components. We also had [/organizations](/docs/organizations/create-component) which housed redundant information under a section titled "Components" and [/users](/docs/users/user-button) housed redundant information under a section titled "Prebuilt components".
This PR
- deletes these redundant pages, and instead, references to our /components documentation in the respective Overview pages. For example, /organizations no longer has a "Components" section with the `<UserButton />` and `<UserProfile />` pages. These pages already exist under /components/organization/* . Instead, /organizations/overview references these …
> DOCS-282 Consolidate component references

- docs/authentication/configuration/sign-in-options.mdx
This PR
- fixes an incorrect image extension (the image was optimized using squoosh which changed the extension from png to jpg)
- fixes the grammar on the heading "Allow users to sign in passwordlessly"
> update image extension; fix grammar on heading

- docs/integrations/webhooks.mdx
- docs/manifest.json
- docs/references/javascript/types/oauth-strategy.mdx
- docs/security/xss-leak-protection.mdx
Fixed the following names: 
`Javascript` -> `JavaScript`
`Typescript` -> `TypeScript`
`Github` -> `GitHub`
> fix: Brand names casing

- docs/references/backend/user/create-user.mdx
- docs/users/deleting-users.mdx
- docs/users/metadata.mdx
- docs/users/overview.mdx
This PR
- updates the content and includes links to respective references
- adds more examples for accessing the `deleteUser()` method
https://github.com/clerkinc/clerk-docs/assets/98043211/f6168fae-33ba-454e-b0b7-f1f56e65e9ed
> Migrate 'Deleting users' from Sanity to MDX

- docs/account-portal/custom-redirects.mdx
- docs/account-portal/direct-links.mdx
- docs/account-portal/getting-started.mdx
- docs/account-portal/user-profile-org-profile.mdx
- docs/authentication/configuration/sign-in-options.mdx
- docs/authentication/using-clerk-hosted-pages.mdx
- docs/components/clerk-provider.mdx
- docs/quickstarts/remix.mdx
This PR
- deletes the old "Using Clerk Hosted Pages" page
- updates "Hosted Pages" references to reference "Account Portal pages"
- updates a few titles to be more palatable - partially for OG Images
> DOCS-283 update hosted pages to now reference account portal

- docs/users/metadata.mdx
replaced `@clerk/clerk-node-sdk` with `@clerk/clerk-sdk-node` in example of set metadata in nodejs example 
at docs/users/metadata.
> fix package name in nodejs example in docs/users/metadata

- .gitignore
- docs/advanced-usage/satellite-domains.mdx
- docs/docs
- docs/quickstarts/nextjs.mdx
- docs/references/nextjs/auth-middleware.mdx
- docs/references/nextjs/trpc.mdx
Dependent on https://github.com/clerkinc/javascript/pull/1695 landing.
Updates the default middleware matcher and clarifies expected behavior.
related to JS-694
> feat(nextjs): Update middleware docs with updated matcher

- CONTRIBUTING.md
- docs/components/customization/localization.mdx
- docs/components/customization/overview.mdx
- docs/quickstarts/expo.mdx
- docs/quickstarts/fastify.mdx
- docs/quickstarts/gatsby.mdx
- docs/quickstarts/javascript.mdx
- docs/quickstarts/nextjs.mdx
- docs/quickstarts/react.mdx
- docs/quickstarts/remix.mdx
- docs/references/javascript/overview.mdx
- docs/references/nextjs/trpc.mdx
- docs/users/sync-data.mdx
This pull request updates all references to pnpm i and pnpm install when adding a package to pnpm add, as this is the preferred method mentioned in the PNPM documentation https://pnpm.io/cli/add
> fix: Use pnpm add instead of pnpm i or pnpm install

- docs/manifest.json
- docs/organizations/managing-roles.mdx
- docs/organizations/viewing-memberships.mdx
/docs/organizations/managing-roles
This PR
- updates the content and includes links to respective references
- adds a page dedicated to 'Viewing memberships', which has updated code examples from the '[useOrganizationList()](/docs/references/react/use-organization-list#use-organization-list)' page
https://github.com/clerkinc/clerk-docs/assets/98043211/3525b40e-e055-4108-a83c-2d76d0fac071
> Migrate 'Managing roles' from Sanity to MDX

- docs/organizations/multiple-orgs.mdx
/docs/organizations/multiple-orgs
This PR
- adds links to respective references
> Migrate 'Multiple orgs' from Sanity to MDX

- docs/backend-requests/overview.mdx
- docs/integrations/databases/wundgraph.mdx
/docs/backend-requests/overview
This PR
- adds links to respective references
- deletes the empty "Wundgraph" page... should be wundergraph, and the content is not here yet so we do not need this page.
https://github.com/clerkinc/clerk-docs/assets/98043211/969bea76-98e8-4a8b-a8c1-7b3b69d27973
> Migrate backend-requests 'Overview' from Sanity to MDX

- docs/custom-flows/embedded-magic-links.mdx
/docs/custom-flows/embedded-magic-links
This PR
https://github.com/clerkinc/clerk-docs/assets/98043211/a9de45ab-4c4e-411b-9c2a-54989ddbfef1
> Migrate embedded-magic-links from Sanity to MDX

- docs/account-portal/direct-links.mdx
- docs/account-portal/disable-account-portal.mdx
- docs/account-portal/getting-started.mdx
- docs/authentication/social-connections/apple.mdx
- docs/authentication/social-connections/line.mdx
In the docs, there is copy that has "->" for explaining navigation. We can do better by using links, and even using this symbol → in the case where a link cannot be used.
> DOCS-341 replace '->' with the arrow symbol or with links

- docs/manifest.json
- docs/references/ruby/overview.mdx
- docs/references/ruby/rack-rails.mdx
Migrates the /references/ruby pages from Sanity to MDX.
Adds the Ruby SDK repository to the /go nav
> Migrate /references/ruby from Sanity to MDX

- docs/deployments/overview.mdx
Presence of certain CAA DNS records on a root domain can conflict with instance deployment, if they prohibit both LetsEncrypt and Google Trust Services from issuing certificates for that domain.
> Document CAA DNS records in Deployment Troubleshooting section

- docs/manifest.json
- docs/references/go/other-examples.mdx
- docs/references/go/overview.mdx
- docs/references/go/verifying-sessions.mdx
Migrates the /references/go pages from Sanity to MDX.
Adds the Go SDK repository to the /go nav
> Migrate /references/go from Sanity to MDX

- docs/references/react/use-organization-list.mdx
- docs/references/react/use-organization.mdx
We exposed invitation from useOrganization from our sdks which replaces the deprecated `invitationList`.
> feat: Replace invitationList with invitations in useOrganization

- docs/troubleshooting/email-deliverability.mdx
Dmarc exmaple was missing `mailto:`
> Added mailto to DMARC example.

- docs/backend-requests/handling/gatsby.mdx
- docs/backend-requests/handling/go.mdx
- docs/backend-requests/handling/ruby-rails.mdx
🔎 [Old Go docs](https://clerk.com/docs/docs/backend-requests/handling/go)
🔎 [Old Gatsby docs](https://clerk.com/docs/docs/backend-requests/handling/gatsby)
🔎 [Old Ruby docs](https://clerk.com/docs/docs/backend-requests/handling/ruby-rails)
🔎 [New docs (this PR)](https://docs-preview-352.clerkpreview.com/docs)
This PR migrates the /backend-requests/handling pages for Go, Gatsby, and Ruby from Sanity to MDX.
> Migrate backend-requests from Sanity to MDX

- docs/references/react/overview.mdx
🔎 [Old Go docs](https://clerk.com/docs/references/react/overview)
🔎 [New docs (this PR)](https://docs-preview-353.clerkpreview.com/docs/references/react/overview)
This PR migrates the React reference overview page from Sanity to MDX.
Redundant information was cut and reference links were used as replacements.
> Migrate React reference overview from Sanity to MDX

- docs/references/react/use-auth.mdx
- docs/references/react/use-clerk.mdx
- docs/references/react/use-session-list.mdx
- docs/references/react/use-session.mdx
- docs/references/react/use-sign-in.mdx
- docs/references/react/use-sign-up.mdx
- docs/references/react/use-user.mdx
markdown was removed from SEO descriptions
in copy, we reference hooks like: `hook()`
table components were migrated to markdown tables
reference links were added where necessary, such as when referencing to the `Session` object.
code snippets were added where necessary.
correct parts of speech were used for sign in vs sign-in and sign up vs sign-up
> clean up react hook reference pages

- docs/integrations/analytics/google-analytics.mdx
- docs/integrations/databases/convex.mdx
- docs/integrations/databases/fauna.mdx
- docs/integrations/databases/firebase.mdx
- docs/integrations/databases/grafbase.mdx
- docs/integrations/databases/hasura.mdx
- docs/integrations/databases/nhost.mdx
- docs/integrations/databases/supabase.mdx
Many of the /integrations pages have `# Getting started` as their H1's
This PR updates the dedicated page's h1 and SEO title for better searchability on the site and better SEO.
> DOCS-342: fix h1's of /integrations pages for better SEO and clarity

- docs/references/javascript/clerk/create-organization.mdx
Update a reference to remove an extra character. Fixes a reported broken link.
> fix: broken create organization link in reference

- docs/testing/overview.mdx
URL https://clerk.com/docs/testing/e2e-testing doesn't exist
Also cleaned up some phrasing IMO
> Fix broken link on testing overview

- docs/components/customization/localization.mdx
Arabic translation is added in `@clerk/localizations@1.26.3`
> DOCS-400: Add Arabic to the list (ar-SA)

- docs/references/nextjs/auth-middleware.mdx
This PR addresses [this Linear ticket](https://linear.app/clerk/issue/DOCS-403/feedback-for-referencesnextjsauth-middlewareoptions).
Adds copy that specifies that middleware should be added to root folder.
Adds callout to address the NextJS middleware docs for more information on middleware in NextJS.
> DOCS-403 elaborate on Nextjs middleware

- docs/manifest.json
- docs/references/javascript/email-address/email-address.mdx
- docs/references/javascript/email-address/verification.mdx
- docs/references/javascript/phone-number/phone-number.mdx
- docs/references/javascript/phone-number/second-factor.mdx
- docs/references/javascript/phone-number/verification.mdx
- docs/references/javascript/web3-wallet/verification.mdx
- docs/references/javascript/web3-wallet/web3-wallet.mdx
Cleaning up the JavaScript reference docs.
This PR
- migrates components to markdown tables
- removes unnecessary imports
- adds links to references where necessary
- typical clean up / consistency thingssss
🔎 [Old email address page](https://clerk.com/docs/references/javascript/email-address/email-address)
🔎 [Old email address verification page](https://clerk.com/docs/references/javascript/email-address/verification)
🔎 [Old phone number page](https://clerk.com/docs/references/javascript/phone-number/phone-number)
🔎 [Old phone number verification page](https://clerk.com/docs/references/javascript/phone-number/verification)
🔎 [Old phone number second factor page](https://clerk.com/docs/references/javascript/phone-number/second-factor)
🔎 [Old web3 wallet …
> clean up javascript reference pages for email address, phone number, and web3 wallet

- docs/custom-flows/user-impersonation.mdx
- docs/organizations/metadata.mdx
- docs/references/javascript/clerk/clerk.mdx
- docs/references/javascript/user/user.mdx
- docs/troubleshooting/overview.mdx
- docs/upgrade-guides/progressive-sign-up.mdx
- docs/users/overview.mdx
The FAPI reference is heavily outdated. This PR removes any links to it; we can add links to the reference when it is back up to date.
Link to Slack discussion: https://clerkinc.slack.com/archives/C01QFRQNHSN/p1696009744964919
> DOCS-434 remove links to outdated FAPI reference

- docs/custom-flows/email-sms-otp.mdx
@alexisintech -- before I do a final edit/revision do you want the examples to be labelled as 'Next App Router'?. The file path/name, the `'use client'` and the use of 'next/navigation' are minor but specific to App Router. Or just call it Next.js?
> Added Next App Router examples to Email/OTP SignUp Custom Flow

- docs/backend-requests/handling/nodejs.mdx
In [DOCS-419](https://linear.app/clerk/issue/DOCS-419/%F0%9F%98%A2-feedback-for-backend-requestshandlingnodejs), the user asked "What are the options for ClerkExpressWithAuth()"
This PR adds copy to clarify that the middleware options listed at the bottom of the page can be used with any of the middleware addressed on the page.
> DOCS-419 clarify on where the middleware options can be used

- docs/references/backend/overview.mdx
- docs/references/backend/user/update-user.mdx
- docs/references/nodejs/overview.mdx
- docs/references/nodejs/token-verification.mdx
- docs/users/deleting-users.mdx
Fixes [DOCS-350](https://linear.app/clerk/issue/DOCS-350/change-clerk-to-clerkclient-in-all-node-examples) and [DOCS-191](https://linear.app/clerk/issue/DOCS-191/node-sdk-docs-mention-clerk-as-a-class)
This PR
- updates imports of the `clerk` object from the Node SDK to use `clerkClient` instead. All other SDK's import as `clerkClient` so we can do the same for the Node SDK in the name of consistency.
- fixes the custom instantiation of the Clerk object (was being called as a class, when it is simply a function)
The code examples were tested 👍
> DOCS-350 / DOCS-191 use clerkClient instead of clerk from node SDK

- docs/advanced-usage/clerk-idp.mdx
`-D` is the shorthand of the `--dump-header` option, while here we want the `-d` (shorthand for `--data`).
> fix: cURL command in OAuth IDP docs

- .github/workflows/revalidate.yml
This adds a `workflow_dispatch` trigger to the revalidate workflow
This outputs changed paths to GITHUB_STEP_SUMMARY
This updates the workflow trigger to only revalidate if the `ref_name` is `main`
> workflows(revalidate): output paths to summary

- docs/manifest.json
[DOCS-440](https://linear.app/clerk/issue/DOCS-440/feedback-for-referencesbackendorganizationcreate-organization) points out that [createOrganizationInvitation()](https://clerk.com/docs/references/backend/organization/create-organization-invitation) was not accessible through the nav.
The createOrganizationInvitation() option in the side nav was linked to the [incorrect page](https://clerk.com/docs/references/backend/organization/create-organization-membership).
> fix path for create-organization-invitation

- docs/references/nodejs/overview.mdx
[DOCS-427](https://linear.app/clerk/issue/DOCS-427/feedback-for-referencesnodejsoverview) points out that a variable is passed to the verifyClient() method but the variable is never declared.
This PR passes the correct variable to the method and also adds a necessary import.
This PR also adds <InjectKeys /> for where the Clerk secret key can be injected.
> DOCS-427 pass correct variable to verifyClient() in nodejs code example

- docs/custom-flows/sign-out.mdx
[DOCS-453](https://linear.app/clerk/issue/DOCS-453/%F0%9F%98%A2-feedback-for-custom-flowssign-out) expresses that the docs aren't clear on how to perform a sign out and redirect to a page after the sign out.
This PR adds copy and a code comment to clarify how the signOut method is used to sign out a user, and the NextJS router is used to redirect a user to a page after sign out is complete.
> DOCS-453 add copy and code comment to clarify on the sign out process

- docs/references/javascript/overview.mdx
[DOCS-448](https://linear.app/clerk/issue/DOCS-448/feedback-for-referencesjavascriptoverview) expresses confusion about the `load()` method called to instantiate ClerkJS.
This PR adds copy and a reference link to guide users to the `load()` reference docs, which describe the options that can be passed to this method.
> DOCS-448 add reference link for load() method

- docs/references/react/use-organizations.mdx
This PR migrates the useOrganizations page to MDX, and adds copy to mention that it's been deprecated in favor of useOrganization and useOrganizationList.
> migrate page from sanity to mdx; add copy about being deprecated

- docs/references/go/verifying-sessions.mdx
The previous examples were using the old/deprecated middlewares.
> chore: Update Go token verification examples

- docs/quickstarts/nextjs.mdx
- docs/references/nextjs/auth.mdx
- docs/references/nextjs/current-user.mdx
From the [linear issue](https://linear.app/clerk/issue/DOCS-336/use-auth-example-before-getauth-example): "The first server side section begins with only getAuth(). Based on support questions at least, the vast majority of customers are using Next 13 + App Router. It feels like we should start the Server Side content with auth() as that's the preferred way with App router."
> DOCS-336 lead examples with app router

- docs/references/backend/invitations/create-invitation.mdx
[DOCS-469](https://linear.app/clerk/issue/DOCS-469/feedback-for-referencesbackendinvitationscreate-invitation) mentions how the docs are missing the possible parameter `publicMetadata`
This PR adds the param to the table of params, and adds example of its usage
> DOCS-469 add publicMetadata param and example to createInvitation

- docs/components/authentication/sign-in.mdx
- docs/components/authentication/sign-up.mdx
- docs/components/organization/create-organization.mdx
- docs/components/organization/organization-list.mdx
- docs/components/organization/organization-profile.mdx
- docs/components/organization/organization-switcher.mdx
- docs/components/user/user-button.mdx
- docs/components/user/user-profile.mdx
[DOCS-463](https://linear.app/clerk/issue/DOCS-463/%F0%9F%98%A2-feedback-for-componentsuseruser-button) and [DOCS-479](https://linear.app/clerk/issue/DOCS-479/%F0%9F%98%A2-feedback-for-referencesjavascriptclerkuser-buttonuser-button) are feedback tickets from users that express confusion on how to customize Clerk components.
This PR adds a section titled `Customization` to each of the customizable Clerk component pages. This section guides users to our customization docs.
> DOCS-487 add copy that guides users to our component customization docs

- docs/components/customization/localization.mdx
[DOCS-483](https://linear.app/clerk/issue/DOCS-483/feedback-for-componentscustomizationlocalization) includes feedback from a user who got a syntax error when trying to import a localization. Their import looked like: `import { zh-CN } from '@clerk/localizations'`
This PR adds copy and code comments to clarify how to import locales.
> DOCS-483 clarify on how to import localizations

- docs/advanced-usage/satellite-domains.mdx
- docs/quickstarts/nextjs.mdx
- docs/references/nextjs/auth-middleware.mdx
- docs/references/nextjs/trpc.mdx
Support continues getting tickets of users struggling with configuring their middleware, specifically where to place their middleware file.
This PR expands on the copy that explains where to place the middleware.ts file
> DOCS-488 clarify on where to place middleware.ts

- docs/integrations/databases/fauna.mdx
Fauna changed the URL to their user-roles page and the old one is 404ing.
Broken Link
https://docs.fauna.com/fauna/current/cookbook/security/user-roles
Working Link
https://docs.fauna.com/fauna/current/cookbook/advanced/security/user-roles
> fix: update broken link on fauna integration page

- docs/components/organization/organization-profile.mdx
- docs/components/user/user-profile.mdx
This PR adds a small sentence to point to the Custom pages documentation at the bottom of `UserProfile` and `OrganizationProfile` pages.
> Add a reference to Custom Pages docs in UserProfile and OrganizationProfile pages

- docs/references/nextjs/read-session-data.mdx
This broken link was reported on the #broken-links-alerts Slack channel and can be found on [this page](https://clerk.com/docs/references/nextjs/read-session-data) as `currentUser()`.
> Fix URL for `currentUser`

- docs/deployments/migrate-from-firebase.mdx
The current command does not include the `npm install` / `npm i`.
> Fix node-fetch@2 install command on firebase migration docs

- docs/quickstarts/fastify.mdx
Just fixed a small typo in `/docs/quickstarts/fastify.mdx`
dotenv was spelled `dontenv`
> Small typo in fastify quickstart

- docs/quickstarts/react.mdx
Quick fix for indentation in the React quickstart.
> Fix indentation in `react.mdx`

- docs/quickstarts/expo.mdx
"At the moment only expo android/iOS outputs will work with clerk. We should make sure there's a prominent note in the quickstart about this. We should also make sure we add a link to productlane where people can upvote the feature to this callout 😁 https://feedback.clerk.com/roadmap/fb56a8db-763a-4e0d-a4b2-f8a453be195c"
This PR adds a `<Callout />` component to let users know that Clerk currently only supports Expo for mobile outputs, and that users can upvote the addition of web support at the link provided.
🔎 [Current Expo page](https://clerk.com/docs/quickstarts/expo#use-clerk-with-expo)
🔎 [This PR's Expo page](https://docs-preview-461.clerkpreview.com/docs/quickstarts/expo)
> DOCS-478 add callout about expo SDK only supporting mobile output

- docs/components/authentication/sign-in.mdx
- docs/components/customization/localization.mdx
- docs/components/customization/overview.mdx
- docs/components/customization/themes.mdx
- docs/components/customization/variables.mdx
Currently, the [Themes](https://clerk.com/docs/components/customization/themes) page shows code examples of how to import themes, but not where to import, nor how to use them.
This PR adds a section titled "Usage" and links users to the [Appearance](https://clerk.com/docs/components/customization/overview#using-a-pre-built-theme) prop page where it's explained how the appearance prop is used to change the theme of a component/all components.
Also, per [this Slack discussion](https://clerkinc.slack.com/archives/C05BEL0P7M4/p1698964339477739), more examples were added to cover different use cases for the `appearance` and `variables` props.
This PR adds examples for
- Passing a theme to `<ClerkProvider />` (*all* Clerk components)
- passing a single theme to *all* components
- passing an …
> DOCS-422 clarify how/where to import themes; add examples on how to use `appearance` and `variables` props

- docs/authentication/configuration/session-options.mdx
Deleted some extra text that didn't need to be there
> Fix copy-paste error in Session options docs

- docs/advanced-usage/using-proxies.mdx
- docs/authentication/social-connections/linkedin.mdx
- docs/custom-flows/magic-links.mdx
- docs/custom-flows/oauth-connections.mdx
- docs/custom-flows/saml-connections.mdx
- docs/custom-flows/user-impersonation.mdx
- docs/quickstarts/javascript.mdx
- docs/references/javascript/clerk/session-methods.mdx
- docs/references/javascript/organization/invitations.mdx
- docs/references/javascript/organization/members.mdx
- docs/references/javascript/organization/organization.mdx
- docs/references/javascript/overview.mdx
- docs/references/javascript/types/oauth-strategy.mdx
- docs/references/javascript/user/user.mdx
- docs/references/nextjs/with-clerk-middleware.mdx
- docs/references/nodejs/overview.mdx
- docs/references/nodejs/token-verification.mdx
- docs/references/ruby/overview.mdx
- docs/testing/cypress.mdx
This PR adds `<Callout />` components with `type="danger"` (instead of `type="info"`) to better highlight that something is deprecated. This PR also adds "(deprecated)" copy where necessary (in places that deprecated items were mentioned).
This PR also updates practices in reflection of [these major updates](https://github.com/clerk/javascript/blob/main/packages/nextjs/CHANGELOG.md#500-alpha-v50):
- use NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY instead of NEXT_PUBLIC_CLERK_FRONTEND_API env variable
- use NEXT_PUBLIC_CLERK_JS_VERSION instead of CLERK_JS_VERSION
- use CLERK_SECRET_KEY instead of CLERK_API_KEY
- use publishableKey instead of frontendApi
- use @clerk/nextjs instead of @clerk/nextjs/ssr
- use @clerk/nextjs instead of @clerk/nextjs/api
- use middleware with authMiddleware instead of …
> clarify on deprecated content

- docs/components/unstyled/sign-out-button.mdx
A [user feedback ticket](https://linear.app/clerk/issue/DOCS-541/%F0%9F%98%A2-feedback-for-componentsunstyledsign-out-button) expressed that our docs "need examples how to logout from all sessions".
This PR
- fixes headings (broke a11y as they were in the wrong order)
- adds a section on "multi-session usage" with 
- code examples on how to utilize the `signOutOptions` property for signing out of a specific session in a multi-session application. (🔎 [see the updated section here](https://docs-preview-472.clerkpreview.com/docs/components/unstyled/sign-out-button#sign-out-of-a-specific-session))
- code examples on how to utilize the `signOutCallback` property for signing out of all sessions in a multi-session application. (🔎 [see the updated section …
> docs-541 add code examples on how to sign out of a session in a multisession app

- STYLEGUIDE.md
Hi!
This adds "How to abbreviate a term" and some instructions about "Jargon" to the styleguide.
I've used https://developers.google.com/style/abbreviations and https://developers.google.com/style/jargon to help me with that (in case we want to expand this since my addition is the minimal one)
> chore: Additions to styleguide

- docs/references/backend/organization/get-organization-list.mdx
- docs/references/backend/organization/get-organization-membership-list.mdx
- docs/references/backend/organization/get-pending-organization-invitation-list.mdx
- docs/references/backend/user/get-count.mdx
[Feedback from a user](https://linear.app/clerk/issue/DOCS-542/feedback-for-referencesbackendorganizationget-organization-list) on our [`getOrganizationList`](https://clerk.com/docs/references/backend/organization/get-organization-list) page asks "Where can I find information on the query I think document is incomplete?" 
This PR adds examples on how to the `query` param, as well as other needed examples for backend SDK methods.
> DOCS-542 add examples of how to use different params for backend sdk methods

- docs/manifest.json
This PR adds [Hono](https://github.com/honojs/middleware/tree/main/packages/clerk-auth) to the list of the community SDKs.
> Add Hono to Community SDKs

- docs/security/vulnerability-disclosure-policy.mdx
- Remove extra whitespace
- Add consistent punctuation
- s/an/and/
> Fix typo in Vulnerability Disclosure Policy

- docs/organizations/overview.mdx
[Feedback from a user](https://linear.app/clerk/issue/DOCS-511/feedback-for-organizationsoverview) about the [Organizations overview](https://clerk.com/docs/organizations/overview) states "This page doesn't indicate if there's a limit regarding how many organizations a person can belong to."
This PR adds the necessary information - gathered from [this Slack discussion](https://clerkinc.slack.com/archives/C05BEL0P7M4/p1698941780015749).
> DOCS-511 add information on how many orgs a user can belong to vs. create

- docs/components/unstyled/sign-out-button.mdx
The code examples use the `signOut()` method from the `useClerk()` hook, not the `useAuth()` hook. 
Because our documentation on [multi-session applications](https://clerk.com/docs/custom-flows/multi-session-applications#sign-out-all-sessions) uses `useClerk()` in the code examples, we will also pull `signOut()` from `useClerk()` on this page, in the name of consistency.
> fix incorrect hook reference

- docs/references/react/use-organization-list.mdx
Fixes error in the description of the `fetchNext` variable in the `PaginatedResources` section.
> Fix typo in useOrganizationList

- docs/quickstarts/nextjs.mdx
This PR updates the Nextjs Quickstart to replace the old `NextjsQuickstartHero` with the new reusable MDX component `<TutorialHero />` (created in [this PR](https://github.com/clerk/clerk-marketing/pull/819)).
> Note: builds for this may fail, as it is relying on the merge of the mentioned PR. To test, you must run the marketing repo with the branch aa/DOCS-527 with the docs repo opened on branch aa/DOCS-527 (and run using `yarn dev:docs`) But for convenience, I have provided screenshots below.
> Use <TutorialHero /> component in NextJS quickstart header

- docs/authentication/social-connections/linkedin-oidc.mdx
- docs/authentication/social-connections/linkedin.mdx
LinkedIn doesn't issue refresh tokens by default, only if you're approved as a Marketing Developer Platform (MDP) partner. I've added a note to clarify this on both the new and deprecated provider pages, for those who need this information.
Previews:
* https://docs-preview-489.clerkpreview.com/docs/authentication/social-connections/linkedin-oidc#enable-open-id-connect
* https://docs-preview-489.clerkpreview.com/docs/authentication/social-connections/linkedin#configuring-linked-in-social-connection
> feat: Add note about MDP for LinkedIn OAuth provider

- docs/authentication/saml-at-clerk.mdx
Fixes a broken image on the [SAML at Clerk](https://clerk.com/docs/authentication/saml-at-clerk#saml-at-clerk-beta) page, under "[Prerequisites](https://clerk.com/docs/authentication/saml-at-clerk#prerequisites)".
Before fix ([link to broken page](https://clerk.com/docs/authentication/saml-at-clerk#prerequisites)):
After fix ([link to updated page](https://docs-preview-505.clerkpreview.com/docs/authentication/saml-at-clerk#saml-at-clerk-beta)):
> DOCS-670 fix broken image

- docs/references/nextjs/auth-middleware.mdx
[DOCS-525](https://linear.app/clerk/issue/DOCS-525/expand-on-authmiddleware-property-descriptions) states "User testing participants wondered about what audiences and clock skews are. This is an opportunity to expand on these topics or link to appropriate pages for all obscure properties."
🔎 [Old page](https://clerk.com/docs/references/nextjs/auth-middleware#options)
🔎 [New page](baking)
> DOCS-525 add explanations for audiences and clock skew

- docs/references/ruby/available-methods.mdx
Our broken link checker in Slack notified us that we had a broken link on the Ruby "Available methods" page under the section "SMS Messages". This is because the SMS POST endpoint from the backend API is now fully removed.
This PR removes the broken link and updates the resource to be marked as deprecated.
🔎 [Link to the exact section](https://clerk.com/docs/references/ruby/available-methods#sms-messages)
🔎 [New page]()
> remove broken link and updated deprecated backend resource

- docs/custom-flows/user-impersonation.mdx
Super quick fix - our policy is to use neutral pronouns in examples like this in Clerk's docs
> Remove gendered pronoun from example

- docs/components/unstyled/sign-out-button.mdx
[DOCS-674](https://linear.app/clerk/issue/DOCS-674/feedback-for-componentsunstyledsign-out-button) is a user feedback ticket that states 
"minor typo in code examples:
CURRENT (with typo):
<SignOutButton>
<button>Sign in with Clerk</button>
</SignOutButton>
DESIRED (fixed)
<SignOutButton>
<button>Sign out with Clerk</button>
</SignOutButton>"
The user suggested we update it to "Sign out with Clerk". I would like to update it to simply "Sign out" because the user would have already "signed in with Clerk" and it seems redundant to say "with Clerk" again.
This PR fixes all instances where the text is incorrect for a sign-out button.
And thank you to Greg for leaving the feedback that incited these changes 💙
> DOCS-674 fix incorrect text in sign-out button

- docs/references/overview.mdx
[DOCS-649](https://linear.app/clerk/issue/DOCS-649/%F0%9F%98%A2-feedback-for-referencesoverview) is a user feedback ticket for the [References Overview page](https://clerk.com/docs/references/overview) and it says "It’s a page for api reference but there’s literally no api docs here, just language SDKs, madness".
This PR updates the overview page to not mention "APIs" at all.
> DOCS-649 remove use of 'API' from SDK reference overview

- docs/quickstarts/nextjs.mdx
ClerkProvider can now render in client components as well.  We can remove this callout:
> `<Callout type="warning">`
The root layout is a server component. If you plan to use the `<ClerkProvider />` outside the root layout, it will need to be a server component as well.
`</Callout>`
This PR also:
- adds a direct link to the API Keys page in the Clerk Dashboard when talking about api keys.
- adds copy that mentions the account portal feature, in case users need more information about the pages that Clerk provides OOTB
> DOCS-729 remove callout about clerkprovider; other small updates

- CONTRIBUTING.md
- scripts/check-links.mjs
Adds an `EXCLUDE_LIST` to the link checker so that URLs that are hosted on the marketing site or that are other docs (e.g. BAPI docs) are not marked as missing.
> fix: Add exclude list to link checker

- docs/manifest.json
Add a link pointing to the FAPI OpenAPI documentation hosted in Redocly.  The Clerk Marketing Site will reverse proxy this URL back to Redocly. 
This is an absolute URL since reverse proxying will only work in production.
> Add link to FAPI API docs

- CONTRIBUTING.md
- docs/quickstarts/nextjs.mdx
[PR-845 in the marketing repo](https://github.com/clerk/clerk-marketing/pull/845) updates the `<TutorialHero />` component to be used in non-quickstart tutorials. The PR updates a prop in the component.
This PR updates that prop where necessary.
> **Note** this build will fail until PR-845 is merged.
> Update prop for <TutorialHero /> component

- docs/references/nextjs/authentication-object.mdx
The `organization` object was still present in the doc for the Authentication Object. This is no longer present on the object, so removed from the docs.
> Removed organization property -- no longer present

- docs/components/customization/localization.mdx
Fixed a typo in Czech locale and added missing Portuguese locale according to: https://github.com/clerk/javascript/blob/main/packages/localizations/src/index.ts
> Update list of Localizations

- docs/manifest.json
- docs/quickstarts/nextjs.mdx
- docs/references/nextjs/usage-with-older-versions.mdx
- package-lock.json
Docs PR for https://github.com/clerk/javascript/pull/2292. Checker that install command will only ever install v4: https://jubianchi.github.io/semver-check/#/^4.0.0/5.0.0
Should only be merged once the PR is published.
Previews:
- [Quickstart](https://docs-preview-543.clerkpreview.com/docs/quickstarts/nextjs#next-steps)
- [Use Clerk with Next.js 12 and older](https://docs-preview-543.clerkpreview.com/docs/references/nextjs/usage-with-older-versions)
> feat: Add "Use Clerk with Next.js 12 and older" page

- docs/custom-flows/use-sign-up.mdx
Reverts clerk/clerk-docs#530
Accidentally merged [PR-530](https://github.com/clerk/clerk-docs/pull/530) which switched `next/router` to `next/navigation`
This is incorrect, as `next/navigation` is used in App Router, and these are Pages Router examples (so the original code was correct).
> Revert "Update use-sign-up.mdx"

- docs/guides/basic-rbac.mdx
- docs/manifest.json
suggestions for [PR-577](https://github.com/clerk/clerk-docs/pull/557) include
- updated screenshots (larger and optimized as webp)
- adds the guides section and this page to the manifest (sidenav)
- requires [this PR in the marketing repo](https://github.com/clerk/clerk-marketing/pull/862) to be merged as it adds the necessary icon for this sidenav addition
- adds an explanation to why a user would need to build an RBAC (control which users access certain parts of their app, using Clerk's roles and publicMetadata features)
- removes mention of `src` directory - users that use the `src` directory will understand that this is their root folder
> review suggestions for PR-557 (RBAC)

- docs/references/nextjs/auth.mdx
Fixes missing links in the [`auth()`](https://clerk.com/docs/references/nextjs/auth) docs.
🔎 [Updated auth() page](https://docs-preview-576.clerkpreview.com/docs/references/nextjs/auth#auth)
Screenshot of the issue before this PR (notice the [auth-object] instead of a link):
> fix missing links in auth() docs

- docs/references/go/overview.mdx
a user wrote into support stating: 
_The Go example page on your main site contains an incorrect URL for the go module "clerk" instead of "clerkinc". This was a headache to figure out and actually fix, as it really gave a confusing error and I had to purge some directories to get Go to forget the mistake. (The GitHub repo Readme has the correct URL)._
changed the import and module to `import "github.com/clerkinc/clerk-sdk-go/clerk"` and `$ go get github.com/clerkinc/clerk-sdk-go`, respectively so it matches the [Go SDK README ](https://github.com/clerk/clerk-sdk-go)
> Update Go imports

- docs/components/control/authenticate-with-callback.mdx
- docs/components/control/clerk-loaded.mdx
- docs/components/control/clerk-loading.mdx
- docs/components/control/multi-session.mdx
- docs/components/control/redirect-to-createorganization.mdx
- docs/components/control/redirect-to-organizationprofile.mdx
- docs/components/control/redirect-to-signin.mdx
- docs/components/control/redirect-to-signup.mdx
- docs/components/control/redirect-to-userprofile.mdx
- docs/components/control/signed-in.mdx
- docs/components/control/signed-out.mdx
- docs/integrations/databases/supabase.mdx
- docs/references/react/use-session-list.mdx
- docs/testing/postman-or-insomnia.mdx
During the content audit (visually scanning each page), I found inconsistencies and mistakes.
This PR
- adds `<InjectKeys />` where necessary in order to expose publishable keys
- updates text to be consistent across examples
- assigns syntax to a code snippet (was missing one altogether)
> minor docs fixes found during content audit

- docs/organizations/verify-user-permissions.mdx
This calls out a critical piece (`OrganizationSwitcher`) in the docs — AFAICT, _"basically roles n permissions will not work unless you also use `OrganizationSwitcher`"_
I was attempting to use the new roles/permissions functionality, and was very confused by what the docs were laying out, and what I was seeing in my dev app. 
And I only chanced upon this via https://organizations-demo.clerk.app/.
> Add callout to `OrganizationSwitcher`

- docs/references/nextjs/current-user.mdx
- docs/references/nextjs/read-session-data.mdx
- docs/references/nextjs/route-handlers.mdx
- docs/references/nextjs/server-actions.mdx
[DOCS-736](https://linear.app/clerk/issue/DOCS-736/small-correction-for-useuser-types) provides information about the current documentation errors for currentUser().
Currently, the docs state that currentUser() returns the same User object as useUser(). However, currentUser() returns a different [BAPI User object](https://clerk.com/docs/reference/backend-api/tag/Users#operation/GetUser) while useUser() returns the expected [FAPI User](https://clerk.com/docs/references/javascript/user/user#user) object.
This PR updates the docs to correctly explain the return type of currentUser().
> DOCS-736 Fix currentUser return type

- docs/users/sync-data.mdx
[DOCS-5143](https://linear.app/clerk/issue/DOCS-5143/feedback-for-userssync-datasync-clerk-data-to-your-backend-with) points out an inconsistency of the endpoint being `/api/webhook` but is listed as `/api/webhooks` in one of the endpoints references.
And thank you to pierreouannes for leaving the feedback that incited these changes 💙
> DOCS-5143 fix misspelling of endpoint

- .remarkrc
- docs/references/javascript/overview.mdx
[DOCS-743](https://linear.app/clerk/issue/DOCS-743/feedback-for-referencesjavascriptoverview-gl=1beng7r-gcl) is a user feedback ticket that expressed trouble finding their publishable key.
This PR adds instructions on how to locate the publishable key.
> DOCS-743 add instructions on how to find the publishable key

- .remarkrc
- docs/backend-requests/handling/manual-jwt.mdx
[DOCS-735](https://linear.app/clerk/issue/DOCS-735/%F0%9F%98%A2-feedback-for-backend-requestshandlingmanual-jwtmanual-jwt) is a user feedback ticket that says "I can decoded token but it doesn't contain user_id."
At [the bottom of the Manual JWT docs](https://clerk.com/docs/backend-requests/handling/manual-jwt#example-usage), it mentions "Once the token is completely validated, you then have a valid `session` and `user_id` that you can use in your application." 
This is not correct; the token includes `sid` and `sub` properties, not `session` and `user_id` properties.
This PR updates the text to be accurate.
And special thank you to matko.klaic for leaving the feedback that incited these changes 💙
> DOCS-735 fix text to accurately reference sid and sub

- docs/references/backend/organization/get-organization-membership-list.mdx
- docs/references/backend/organization/get-pending-organization-invitation-list.mdx
[DOCS-5155](https://linear.app/clerk/issue/DOCS-5155/fix-a-typo) points out a typo on the [webhooks](https://clerk.com/docs/integrations/webhooks?_gl=1*ymomuh*_gcl_au*NTAyODk3MTk3LjE3MDMyNDYwNDY.*_ga*MTA0MTczOTc4My4xNzAzMjQ2MDQ2*_ga_1WMF5X234K*MTcwNDM1MjkzMC4zLjEuMTcwNDM1NDYxOC4wLjAuMA) page.
I couldn't find it, but ctrl + f'ing "orgna" I found other typos.
> fix organization typos

- docs/components/authentication/sign-in.mdx
- docs/references/javascript/clerk/sign-in.mdx
[DOCS-778](https://linear.app/clerk/issue/DOCS-778/feedback-for-referencesjavascriptclerksign-in) is a user feedback ticket that states: 
> Pretty confusing that this component is only documented under the JavaScript SDK and not under React, Next.js etc. Of course, these are also based on JavaScript, but my first instinct is to look in the Next.js docs rather than JavaScript, as there are often more specialised solutions for these frameworks.
I only noticed this change in the docs because a new employee couldn't find this component without me telling him about it.
This PR serves to more clearly differentiate between the two references. In this PR:
[SignIn component reference preview]()
- adds the JS reference examples for mounting the SignIn component to the component reference docs …
> DOCS-778 differentiate between the component reference and JS reference for the SignIn component

- docs/guides/force-organizations.mdx
- docs/manifest.json
- docs/organizations/overview.mdx
A lengthy review/update to the Force Organizations guide that is better done in a separate PR rather than cumbersome github code review suggestions.
- reorganizes sections/renames sections to be more clear and overall editorial pass
- adds a section to organizations/overview that explains how to enable organizations.
> "force organizations" guide suggestions

- docs/guides/force-organizations.mdx
- docs/manifest.json
- docs/organizations/overview.mdx
This PR adds a step by step guide, explaining why and how you can properly hide a user's "personal account" and force them into an organization instead
> feat: Guide for forcing organizations

- docs/authentication/social-connections/google.mdx
I think this was the issue but lmk if not
image broken here: https://clerk.com/docs/authentication/social-connections/google#block-email-subaddresses
> Fix broken image for Google block email subaddresses

- docs/users/sync-data.mdx
This PR aims to fix a typo in a code comment located on the sync-data page. The typo was in a comment in the catch block of the code sample on creating an endpoint in the user's application.
> Fix typo in code comment in documentation

- docs/references/backend/sessions/authenticate-request.mdx
Found a small spelling error while browsing the docs. Should refer to the `PEM` public key. not ~~PRM~~.
> Fix spelling error

- docs/references/backend/invitations/create-invitation.mdx
Missing documentation for `clerkClient.invitations.createInvitation` params `notify` and `ignoreExisting`
Copy was copied from the [BAPI reference](https://clerk.com/docs/reference/backend-api/tag/Invitations#operation/CreateInvitation!path=notify&t=request)
> documented notify and ignoreExisting for createInvitation

- docs/custom-flows/forgot-password.mdx
[DOCS-730](https://linear.app/clerk/issue/DOCS-730/edit-forgot-reset-password-copy) was a user complaint about the copy in the introductory sentence of the guide. It read "Clerk's [prebuilt components](https://clerk.com/docs/components/overview) have options that you can configure to help your users who have forgotten a password." This is not true, there are no options to configure in prebuilt components - they handle forgot/reset password out of the box. Non-configurable.
As I was updating the copy, I realized this code example is also very out of date and needed some love. It's definitely rough and not perfect, but it's better.. and functional! and that's what counts :~)
> DOCS-730 edit forgot password guide

- docs/references/javascript/sign-in/sign-in.mdx
- docs/references/react/use-sign-in.mdx
[This user feedback ticket](https://linear.app/clerk/issue/DOCS-5150/double-check-that-referencesreactuse-sign-in-works) claimed our useSignIn docs were not working/outdated
Taking a look at the [useSignIn](https://clerk.com/docs/references/react/use-sign-in) doc, I have updated it's overall structure to introduce the hook and its returns first so that users can understand the hook before taking a look at its usage. Its "Usage" section got reorganized as well, removing redundant code examples that already exist in our "Custom flows" docs. Now, this "Usage" section will link to the appropriate place in the docs, so that users can be guided to the entire section for building custom flows, and understand custom flows fully in their context instead of viewing an incomplete, dead end code …
> DOCS-5150 update SignIn and useSignIn docs

- docs/authentication/configuration/restrictions.mdx
[DOCS-653](https://linear.app/clerk/issue/DOCS-653/clarify-that-allow-and-block-lists-block-sign-up-and-sign-ins) reports user complaints on the copy not being clear.
Roy stated "The part you highlighted @nabors does say 'access' but other areas, like the previous sentence, explicitly say "sign-up". This seems to be the confusion with customers."
This PR updates the copy accordingly
> DOCS-653 update copy to clarify that allowlists allow/block sign-ups

- docs/references/react/add-react-router.mdx
At create layouts session, there is a typo at 'componnets',
> docs: typo fix

- docs/references/javascript/sign-up/sign-up.mdx
- docs/references/react/use-sign-up.mdx
[This user feedback ticket](https://linear.app/clerk/issue/DOCS-5292/%F0%9F%98%A2-feedback-for-referencesreactuse-sign-upuse-sign-up) wrote, "needs to attempt verify email code before creating a user"
Taking a look at the [useSignUp](https://clerk.com/docs/references/react/use-sign-up) doc, I have updated it's overall structure to introduce the hook and its returns first so that users can understand the hook before taking a look at its usage. Its "Usage" section got reorganized as well, removing redundant code examples that already exist in our "Custom flows" docs. Now, this "Usage" section will link to the appropriate place in the docs, so that users can be guided to the entire section for building custom flows, and understand custom flows fully in their context instead of viewing an …
> DOCS-5292 add missing property to SignUp; update useSignUp

- docs/integrations/databases/hasura.mdx
Use the destructured `getToken` and remove the undefined `user` in the Apollo example for Hasura
> fix: remove undefined `user` in Apollo example

- docs/backend-requests/resources/session-tokens.mdx
- docs/guides/force-organizations.mdx
- docs/organizations/create-roles-permissions.mdx
- docs/organizations/verify-user-permissions.mdx
- docs/references/nextjs/auth.mdx
- docs/references/nextjs/authentication-object.mdx
This PR
🔎 [Session tokens](https://docs-preview-688.clerkpreview.com/docs/backend-requests/resources/session-tokens)
- moves the `act` token to the appropriate section (it was under organization claims, and that's not correct!)
🔎 [Verify the active user's permissions in an organization](https://docs-preview-688.clerkpreview.com/docs/organizations/verify-user-permissions)
- adds reference links for new has() and protect() sections
- fixes incorrect heading tags (they were not incremental)
🔎 [auth()](https://docs-preview-688.clerkpreview.com/docs/references/nextjs/auth)
- move return type of `auth()` to top of page, right under `auth()`'s explanation. users should fully understand what the helper is and what it returns before exploring examples of it.
- added sections that explain the …
> DOCS-5339 create references for has and protect helpers

- CONTRIBUTING.md
- docs/advanced-usage/using-proxies.mdx
- docs/backend-requests/handling/go.mdx
- docs/components/control/authenticate-with-callback.mdx
- docs/components/control/clerk-loaded.mdx
- docs/components/control/clerk-loading.mdx
- docs/components/control/multi-session.mdx
- docs/components/control/redirect-to-createorganization.mdx
- docs/components/control/redirect-to-organizationprofile.mdx
- docs/components/control/redirect-to-signin.mdx
- docs/components/control/redirect-to-signup.mdx
- docs/components/control/redirect-to-userprofile.mdx
- docs/components/control/signed-in.mdx
- docs/components/control/signed-out.mdx
- docs/integrations/databases/convex.mdx
- docs/integrations/databases/supabase.mdx
- docs/quickstarts/fastify.mdx
- docs/quickstarts/gatsby.mdx
- docs/quickstarts/javascript.mdx
- docs/quickstarts/nextjs.mdx
- docs/quickstarts/react.mdx
- docs/quickstarts/redwood.mdx
- docs/quickstarts/remix.mdx
- docs/references/go/overview.mdx
- docs/references/go/verifying-sessions.mdx
- docs/references/javascript/overview.mdx
- docs/references/nextjs/trpc.mdx
- docs/references/nodejs/overview.mdx
- docs/references/ruby/overview.mdx
[DOCS-699](https://linear.app/clerk/issue/DOCS-699/revisit-copy-for-environment-keys) reads:
So something like, "If you are signed into your Clerk Dashboard, you can copy your keys below. Otherwise, you can find your keys in the Clerk Dashboard on the [API Keys](link) page."
---
This PR
- fixes broken injectkeys instances
- adds copy wherever injectkeys is used that explains its usage
> DOCS-699 fix broken injectkeys instances; add copy that explains injectkeys usage

- docs/backend-requests/making/jwt-templates.mdx
Fixes the example for [conditional expressions](https://clerk.com/docs/backend-requests/making/jwt-templates#conditional-expressions) so that it uses the same key: `has_verified_contact_info`
> fix: jwt templates example consistency on has_verified_contact_info

- docs/components/customization/layout.mdx
[DOCS-5325](https://linear.app/clerk/issue/DOCS-5325/feedback-for-componentscustomizationlayout) reads:
hello, the socialButtonsVariant properties are incorrect.
It should be "auto" | "iconButton" | "blockButton"
---
This PR updates the `socialButtonsVariant` type accordingly.
and a special thank you to nirmal.patel for the feedback that incited these changes 💙
> DOCS-5325 update socialButtonsVariant type

- docs/quickstarts/nextjs.mdx
- very minor update: updating order of info - publishable key is introduced first in the snippet, so i'm moving it to be introduced first in the copy.
- fixed a typo where it says "contain your both." will now say "contain your keys."
- looks like our formatters are fighting 🤭 we use tab size = 2
- removed a card about using nextjs with 12 or older. not really important for a user's learning journey.
> /quickstarts/nextjs: fix typos; remove unnecessary card from 'more resources'

- docs/manifest.json
- docs/references/backend/sessions/get-session-list.mdx
- docs/references/javascript/organization-domain.mdx
- docs/references/javascript/session-with-activities.mdx
- docs/references/javascript/session.mdx
- docs/references/javascript/types/overview.mdx
- docs/references/javascript/types/session-status.mdx
- docs/references/javascript/user/create-metadata.mdx
- docs/references/javascript/user/password-management.mdx
- docs/references/javascript/user/totp.mdx
- docs/references/javascript/web3-wallet/verification.mdx
[DOCS-676](https://linear.app/clerk/issue/DOCS-676/types-section-on-javascript-reference-pages-need-to-be-consolidated) reads:
Many of the JavaScript reference pages have a "Types" section that has redundant information. We have /references/javascript/types to house types references. For example, https://clerk.com/docs/references/javascript/session#types has PublicUserData and SessionStatus sections, yet the /references/javascript/types context has a dedicated page for PublicUserData that we can simply link to. And SessionStatus is used on other reference pages, so a dedicated page for this type can be created and then also linked to.
We should ensure that types *that are reused on multiple different pages* have a dedicated page under `/references/javascript/types`.
We should also create …
> DOCS-676 abstract types from references pages

- docs/references/backend/client/get-client-list.mdx
- docs/references/backend/sessions/verify-session.mdx
- docs/references/javascript/user/user.mdx
[DOCS-5420](https://linear.app/clerk/issue/DOCS-5420/feedback-for-referencesbackendsessionsverify-session) is a user feedback ticket that reads:
"I'm getting an operation_deprecated error when using this, so if this operation is deprecated, please update the docs!"
special thanks to yassinosesafraoui for the feedback that incited these changes 💙
> DOCS-5420 add deprecation warnings

- docs/references/javascript/clerk/sign-in.mdx
user wrote into support:
> error in your documentation:
> 
> https://clerk.com/docs/references/javascript/clerk/sign-in#mount-sign-in-usage 
> 
> The code on line 16 should read:
> 
> `"window.Clerk.mountSignIn(signInComponent, {"`
> 
> and not
> 
> `"window.Clerk.openSignIn(signInComponent, {"`
> Fix mountSignIn example

- docs/guides/force-organizations.mdx
- docs/references/react/use-auth.mdx
- docs/references/react/use-clerk.mdx
- docs/references/react/use-organization-list.mdx
- docs/references/react/use-organization.mdx
- docs/references/react/use-session-list.mdx
- docs/references/react/use-session.mdx
- docs/references/react/use-sign-in.mdx
- docs/references/react/use-sign-up.mdx
- docs/references/react/use-user.mdx
Follow new formatting of introducing a function, its params, its returns, and THEN examples of usage. NO custom flows should be on these reference pages. And as these are React references, the Next.js examples are being removed for now.
🔎 [docs/references/react/use-auth](https://docs-preview-715.clerkpreview.com/docs/references/react/use-auth)
🔎 [docs/references/react/use-clerk](https://docs-preview-715.clerkpreview.com/docs/references/react/use-clerk)
🔎 [docs/references/react/use-organization-list](https://docs-preview-715.clerkpreview.com/docs/references/react/use-organization-list)
🔎 [docs/references/react/use-organization](https://docs-preview-715.clerkpreview.com/docs/references/react/use-organization)
🔎 [docs/references/react/use-session](https://docs-preview-715.clerkpreview.com/doc …
> (core1) DOCS-5394 Update React references

- docs/references/nextjs/auth.mdx
- docs/references/nextjs/authentication-object.mdx
- update incorrect information - `protect()` doesn't throw an error, it redirects users to the sign-in page
- add missing information
- add missing example for demonstrating an authentication check
> (core1) update protect docs

- docs/upgrade-guides/url-based-session-syncing.mdx
The hyperlink didnt include C from Clerk, minor fix made.
> Hyperlink url-based-session-syncing

- CONTRIBUTING.md
- docs/references/go/other-examples.mdx
- docs/references/go/overview.mdx
- docs/references/go/verifying-sessions.mdx
We got some [feedback](https://github.com/clerk/clerk-docs/pull/712#issuecomment-1960838167) from Giannis regarding the /verifying-sessions document in [this PR](https://github.com/clerk/clerk-docs/pull/712):
> Hey @alexisintech, you are correct. The middleware functions are supposed to work in an HTTP server context.
> 
> We offer these middleware as helpers. They are using the jwt.Verify method internally. The Verify method is the primitive/core function here and the middleware is a convenience method around token verification in an HTTP server.
> 
> Most of the times, there's no need to reach out to Verify directly, but in case you want total control over the verification process, or you want to verify a token in a non-HTTP context, you can use Verify directly.
> 
> Hope that makes it …
> Verifying sessions in Go (review)

- docs/references/javascript/clerk/sign-in.mdx
- docs/references/javascript/clerk/sign-up.mdx
copied updates from core 2 JS updates, because as core 1 stands, the code examples were highlighted incorrectly and this page was kinda JANK.
> (core 1) update JS references for sign-in and sign-up

- docs/manifest.json
- docs/references/go/overview.mdx
The sidenav title for the page was inconsistent with the actual title of the page. The path is "other-examples" and is also inconsistent, but this can addressed in the upcoming IA. No need for adding a redirect right now.
Also, I apologize for these edits slipping through the cracks in the initial PR - but I want this doc as polished as possible since we are currently marketing it!
> update Go overview; update manifest for consistency in title and sidenav title

- docs/guides/image-optimization/imageurl-image-optimization.mdx
- docs/manifest.json
- docs/references/javascript/organization/organization.mdx
- docs/references/javascript/types/public-user-data.mdx
- docs/references/javascript/user/user.mdx
This PR:
- Adds a guide that documents our Image Optimization options
- [Preview](https://docs-preview-748.clerkpreview.com/docs/guides/image-optimization/imageurl-image-optimization)
- Adds a link to this guide everywhere it's relevant in the docs. Check where it says `imageUrl` on these pages:
- [PublicUserData](https://docs-preview-748.clerkpreview.com/docs/references/javascript/types/public-user-data#properties)
- [User](https://docs-preview-748.clerkpreview.com/docs/references/javascript/user/user)
- [Organization](https://docs-preview-748.clerkpreview.com/docs/references/javascript/organization/organization#properties)
> Add an Image Optimization guide

- docs/components/customization/user-profile.mdx
[DOCS-5412](https://linear.app/clerk/issue/DOCS-5412/%F0%9F%98%A2-feedback-for-componentscustomizationuser-profile) is a user feedback ticket that complains: "Unsure on how the custom page works, the code provided doesn't work".
The purpose of this PR is to not only fix the code examples to be standalone, copyable, working examples, but to update the entire guide to better explain how to use this feature.
🔎 [Preview](https://docs-preview-751.clerkpreview.com/docs/components/customization/user-profile)
- removed next.js pages, react and remix examples, as they were the exact same as next.js app router example. added this copy to the top of the guide: "For the sake of this guide, examples are written for Next.js App Router but they are supported by any React meta framework, such as Remix or …
> OVERHAUL /docs/components/customization/user-profile

- docs/references/nextjs/auth-middleware.mdx
[DOCS-5427 ](https://linear.app/clerk/issue/DOCS-5427/feedback-for-referencesnextjsauth-middleware) is a user feedback ticket that says:
>"You can also use regex to match routes. The following is an example of a negative assertion that makes only the /admin route protected."
>
>The example regex given does not match "/admin" exactly, only "/admin/...", meaning [site.com/admin](http://site.com/admin) is still a public route
This PR fixes the broken example ! Tested with @jescalan
> DOCS-5427 fix broken authMiddleware example

- docs/references/javascript/clerk/clerk.mdx
- docs/references/javascript/clerk/organization-methods.mdx
- docs/references/javascript/clerk/redirect-methods.mdx
Part of the JavaScript revamp project: JS Quickstart recently got updated with how users can use JS: npm module vs script tag. Examples need to be updated accordingly. Also, we have a lot of user feedback requesting that JavaScript docs show specific examples on how to use each method on a class, etc.
🔎 https://docs-preview-763.clerkpreview.com/docs/references/javascript/clerk/clerk
> DOCS-5475 update /javascript/clerk/clerk

- docs/backend-requests/making/custom-session-token.mdx
[DOCS-5438](https://linear.app/clerk/issue/DOCS-5438/feedback-for-backend-requestsmakingcustom-session-token) is a user feedback ticket that reads: "I don't see how to use CustomJwtSessionClaims successfully; is this references somewhere else in Clerk?"
This PR serves to adds more context about creating and using `CustomJwtSessionClaims`. It also updates the rest of the tutorial.
> DOCS-5438 Provide more context to the custom session token guide

- docs/references/nextjs/auth-middleware.mdx
This PR addresses a minor oversight in our documentation where an essential import statement was missing from one of the provided code blocks.
> Fix: Added missing import Statement in doc

- docs/integrations/databases/supabase.mdx
This PR improves the supabase integration guide by making it a detailed tutorial.
It now includes:
- Up to date instructions for creating RLS policies that are compatible with Clerk
- A simpler explanation of why RLS policies don't work with Clerk without a workaround
- Removed unnecessary (and out of date) screenshots
- A detailed code sample with step-by-step explanations
**[See the preview here](https://docs-preview-707.clerkpreview.com/docs/integrations/databases/supabase)**
The current structure keeps all the content in one page by making the RLS info part of the tutorial. I did this because I think the most common use case for supabase + clerk will require knowing the RLS workaround.
I have another commit that has a separate page for the RLS workaround and a page with a slightly …
> Update supabase integration guide

- docs/references/backend/overview.mdx
Reverts clerk/clerk-docs#772
This change was made to core-2 docs as it's a core-2 update. It should not be made to the core-1 docs.
> Revert "use the right import for clerkClient"

- docs/authentication/social-connections/linkedin-oidc.mdx
- docs/authentication/social-connections/x-twitter.mdx
- docs/deployments/exporting-users.mdx
- docs/guides/authjs-migration.mdx
- docs/guides/force-organizations.mdx
- docs/integrations/databases/convex.mdx
- docs/integrations/databases/supabase.mdx
- docs/quickstarts/javascript.mdx
- docs/quickstarts/nextjs.mdx
- docs/quickstarts/react.mdx
- docs/references/backend/invitations/get-invitation-list.mdx
- docs/references/backend/invitations/revoke-invitation.mdx
This is a companion to the clerk-marketing PR that adds all H1 conent to the SEO title of the page.
This needs to be approved first before merging that one. There is no risk of showing duplicate titles on these pages, as Clerk marketing already shows **either** the frontmatter title or the H1.
[Clerk Marketing PR here](https://github.com/clerk/clerk-marketing/pull/901)
If you want to ensure this is the full list of pages with missing H1s, follow these instructions in the `clerk-marketing` repo:
**In `lib/docs/scripts/index-content.mts`**
1. Add `data` to the options on line 142, so it looks like this:
```
.use(remarkPluginExtractSearchRecords, { records, data })
```
**In `lib/docs/plugins/remark-plugin-extract-search-records.mts`**
1. Add `data` to the …
> Add H1s to all docs where they're missing

- docs/components/customization/organization-profile.mdx
Recently, the /customization/user-profile docs page got a complete overhaul. Details are in this PR: https://github.com/clerk/clerk-docs/pull/751
We need to also update the /customization/organization-profile docs page for consistency!
> DOCS-5488 overhaul /customization/organization-profile page

- docs/references/nextjs/with-clerk-middleware.mdx
[DOCS-5835](https://linear.app/clerk/issue/DOCS-5835/clerkmiddleware-search-in-docs-shows-results-for-the-now-removed)
> DOCS-5835 add deprecated to withClerkMiddleware title for search purposes

- docs/authentication/configuration/session-options.mdx
- docs/custom-flows/multi-session-applications.mdx
- docs/manifest.json
[DOCS-5373](https://linear.app/clerk/issue/DOCS-5373/update-copy-that-explains-inactivity-timeout) calls to "Update copy that explains Inactivity Timeout"
While updating the copy, I went ahead and updated the entire page as it needed.
- Removed unnecessary screenshots
- Removed redundant information like the "customize session token" section - we have a whole guide for this
- Removed redundancy from the multi-session application section and the multi-session custom flow guide, resulting in an update of the custom flow guide as there was some outdated information
- Updates the "Customize your session token" guide's name in the nav to match the page's title (they weren't consistent)
> D0CS-5373 Update session-options and multi-session custom flow guides

- docs/manifest.json
This PR fixes a simple typo in the URL for sign in and sign up options which currently 404s: https://clerk.com/docs/authentication/configuration/sign-u[-sign-in-options
> fix: Fix typo in Sign-up and sign-in options URL

- docs/authentication/saml/overview.mdx
- docs/custom-flows/saml-connections.mdx
- docs/manifest.json
Move SAML to its own dedicated authentication section as we are planning to add dedicated guides per provider and also more pages for various flows
Note: I will make sure to update any old link with the new ones across our stack
> Move SAML to its own dedicated authentication section

- docs/quickstarts/nextjs.mdx
https://clerkinc.slack.com/archives/C01QFRQNHSN/p1710819675732039
**Deploy preview will fail** as this PR requires [this PR in the marketing repo
](https://github.com/clerk/clerk-marketing/pull/912) to get merged to prod
Testing the `<SignedIn>` vs `<SignedOut>` components would require your backend to be set up. For that reason, I demonstrate them working in this video:
https://github.com/clerk/clerk-docs/assets/98043211/9f0e09a5-22c1-4b80-a0f7-7c31ba678eb1
> (WIP) Update Next.js Quickstart

- docs/advanced-usage/using-proxies.mdx
- docs/components/authentication/sign-in.mdx
- docs/components/authentication/sign-up.mdx
- docs/components/organization/create-organization.mdx
- docs/components/organization/organization-list.mdx
- docs/components/organization/organization-profile.mdx
- docs/components/organization/organization-switcher.mdx
- docs/components/user/user-button.mdx
- docs/components/user/user-profile.mdx
- docs/custom-flows/user-impersonation.mdx
- docs/quickstarts/javascript.mdx
- docs/references/javascript/clerk/organization-methods.mdx
- docs/references/javascript/organization-invitation.mdx
- docs/references/javascript/organization/domains.mdx
- docs/references/javascript/organization/invitations.mdx
- docs/references/javascript/organization/members.mdx
- docs/references/javascript/organization/membership-request.mdx
- docs/references/javascript/organization/organization.mdx
- docs/references/javascript/overview.mdx
- docs/references/javascript/user/create-metadata.mdx
- docs/references/javascript/user/password-management.mdx
- docs/references/javascript/user/totp.mdx
- docs/references/javascript/user/user.mdx
- docs/users/metadata.mdx
This PR updates JS examples to include appropriate installation/Clerk instantiation instructions. It injects the Frontend API URL into `<script>` ClerkJS instantiation. It also removes installations instructions from the JS reference overview, and points users to the quickstart for detailed instructions.
> Update JS examples to follow new JS quickstart installation instructions

- docs/deployments/changing-domains.mdx
Just a small callout. Based on customer feedback:
> It would be good to mention either how to add a custom domain for a development environment, or state that it's not possible. Thank you!
(https://linear.app/clerk/issue/DOCS-5442/add-a-note-about-how-users-cannot-change-domains-for-dev-instances)
> Add note about how users cannot change domains for dev instances

- docs/authentication/saml/authentication-flows.mdx
- docs/manifest.json
Introduce a new page that explains how the two different authentication flows, SP-initiated and IdP-initiated, work and their differences
> SAML SP-initiated and IdP-initiated flows

- docs/manifest.json
We change the menu ordering of the SAML pages and place the SAML provider guides at the bottom in order to be aligned with OAuth
> Modify SAML provider guides ordering

- docs/references/backend/organization/get-organization-list.mdx
[User feedback ticket](https://linear.app/clerk/issue/DOCS-5972/feedback-for-referencesbackendorganizationget-organization-list) pointed out ugly spacing in code snippet
> DOCS-5972 fix spacing in getOrganizationList() code snippet

- docs/deployments/migrate-from-firebase.mdx
[User feedback ticket](https://linear.app/clerk/issue/DOCS-749/adjust-copy-about-rate-limits-on-firebase-migration-page) reminds Docs that we should link to *our* and *firebase's* rate limit pages.
> DOCS-749 update copy around rate limits in firebase migration guide

- docs/references/backend/invitations/get-invitation-list.mdx
- docs/references/backend/sessions/get-session-list.mdx
- docs/references/backend/user/get-organization-membership-list.mdx
Changes:
- Add pagination params in invitations/get-invitation-list
- Update limit description for sessions & users to be consistent with the other APIs
> [DOCS-6039] Add pagination params in invitations/get-invitation-list

- docs/authentication/configuration/sign-up-sign-in-options.mdx
- docs/custom-flows/forgot-password.mdx
- docs/security/password-protection.mdx
Note:
Replaces all instances of "leaked" with "compromised" as it is the wording we use in the dashboard.
> Docs for rejecting compromised passwords on sign-in

- docs/backend-requests/resources/rate-limits.mdx
- docs/references/nextjs/current-user.mdx
From [this ticket](https://linear.app/clerk/issue/DOCS-5112/update-rate-limiting-page):
🔎 https://docs-preview-871.clerkpreview.com/docs/backend-requests/resources/rate-limits
🔎 https://docs-preview-871.clerkpreview.com/docs/references/nextjs/current-user
> DOCS-5112 update rate limiting doc

- docs/references/nextjs/custom-signup-signin-pages.mdx
**UI Component docs directly include the required `/` in examples:**
https://beta.clerk.com/docs/components/authentication/sign-in
https://beta.clerk.com/docs/components/authentication/sign-up
> Add missing slashes to path prop in custom-signup-signin-pages.mdx

- docs/users/overview.mdx
[User feedback ticket](https://linear.app/clerk/issue/DOCS-6094/%F0%9F%98%A2-feedback-for-usersoverview) for [/docs/users/overview](https://clerk.com/docs/users/overview) reads:
> not clear mentioning of page links.
I went ahead and cleaned this page up a bit - it's fine for now, but it's just one of those weird conceptual pages that will definitely get another look at after the IA rework
🔎 [Users overview](https://docs-preview-892.clerkpreview.com/docs/users/overview)
> DOCS-6094 update users overview

- docs/references/react/add-react-router.mdx
[User feedback ticket](https://linear.app/clerk/issue/DOCS-6079/feedback-for-referencesreactadd-react-router) reads:
> Hi Folks,
>
> I had to use glob routes (i.e path: "/sign-in/*") instead of what's in here - otherwise I got redirected to a non-existent "/sign-in/factor-one" path :)
>
> Hopefully that helps others!
>
> Nik
🔎 [React router guide](https://docs-preview-893.clerkpreview.com/docs/references/react/add-react-router#wire-layouts-and-routes-up-with-create-browser-router)
> DOCS-6079 fix paths for /sign-in and /sign-up when used with React Router

- docs/components/control/clerk-loaded.mdx
- docs/components/control/clerk-loading.mdx
[User feedback ticket](https://linear.app/clerk/issue/DOCS-6057/add-app-router-example-to-clerkloading-reference) for https://clerk.com/docs/components/control/clerk-loading reads:
> I want with app router
Please check the code example and make sure I wrote the App Router example to use ClerkLoading correctly
> DOCS-6057 add app router example to clerkloading reference

- docs/components/authentication/sign-in.mdx
- docs/components/authentication/sign-up.mdx
[DOCS-6072](https://linear.app/clerk/issue/DOCS-6072/add-link-to-creating-custom-sign-inup-pages-to-the-components-page) reads:
> On [the component page for sign up/in](https://clerk.com/docs/components/authentication/sign-in), we show a short example of "framework usage", but it's not complete like [the full instructions](https://clerk.com/docs/references/nextjs/custom-signup-signin-pages) - perhaps we can expand or just link to the full instructions here? 
>
> This came directly from [a user report](https://app.plain.com/workspace/w_01GT53BQWV3DFW6ECTWZNQ1E9K/thread/th_01HT3BSAFDVZ6TTYAW7P7KZ5K2?entryId=t_01HTJVMDMDR5P2EJ1X9CSD1CK8)
🔎 [Sign in component](https://docs-preview-894.clerkpreview.com/docs/components/authentication/sign-in#usage-with-frameworks)
🔎 [Sign up …
> DOCS-6072 update usage examples for sign in and sign up components

- docs/components/authentication/sign-in.mdx
- docs/components/authentication/sign-up.mdx
Adds a callout for the redirect behaviour when using `<SignIn />` or `<SignUp />` components when a user already has an active session.
This is similar to the message we log in development. However, it's easy to miss at times and results in recurring support tickets:
> Call out redirect behaviour for active sessions

- docs/references/nextjs/trpc.mdx
`AuthObject`, `SignedInAuthObject` and `SignedOutAuthObject` types were removed so the existing example is wrong.
We can infer the type returned.
> fix: Auto infer AuthObject type in trpc setup

- docs/deployments/changing-domains.mdx
- docs/deployments/deploy-to-vercel.mdx
- docs/deployments/environments.mdx
- docs/deployments/set-up-preview-environment.mdx
- docs/deployments/set-up-staging.mdx
- docs/deployments/staging-alternatives.mdx
- docs/manifest.json
This pr:
- [Adds a "Staging environment" guide](https://docs-preview-900.clerkpreview.com/docs/deployments/set-up-staging) that talks about setting up a new Clerk app with a new domain that will act as a user's "staging environment"
- [Adds a kind of hidden "Staging alternatives" guide](https://docs-preview-900.clerkpreview.com/docs/deployments/staging-alternatives) that talks about setting up a subdomain for your production app to use as "staging"
- [Adds a preview environment guide](https://docs-preview-900.clerkpreview.com/docs/deployments/set-up-preview-environment) that talks about the two approaches for preview environments:
- Sharing production credentials by using Vercel's Preview Deployment Suffix feature
- Using development API keys for a preview deployment
- [Updates the …
> Staging and preview guides

- docs/deployments/changing-domains.mdx
- docs/deployments/overview.mdx
While adding guides for "Staging environments with Clerk" and "Preview deployments", I noticed the /deployments guides need some love.
🔎 [Deploy your Clerk app to production](https://docs-preview-913.clerkpreview.com/docs/deployments/overview)
🔎 [Change domain or subdomain](https://docs-preview-913.clerkpreview.com/docs/deployments/changing-domains)
> Remove screenshots from deployments docs

- docs/references/react/add-react-router.mdx
Without waiting for loading to complete, the useEffect was always forwarding to `/sign-in` , added isLoading to dependency and forward only when loading is complete and userId doesn't exist.
> Added isLoading to useEffect deps.

- docs/upgrade-guides/core-2/overview.mdx
- docs/upgrade-guides/long-term-support.mdx
Small update to correctly set the date on our long-term support doc. Also fixes typos on overview page
> chore: Update long-term-support doc

- docs/quickstarts/remix.mdx
This PR changes the `.env.local` file to `.env` for the Remix quick start guide.
> Change env file name for Remix Quickstart

- docs/references/backend/organization/get-organization-list.mdx
This documents the `orderBy` parameter for the `getOrganizationList()` function.
The parameter was previously missing from the SDK, and it's being added in https://github.com/clerk/javascript/pull/3164
> feat: Document `orderBy` param of `getOrganizationList()`

- docs/integrations/webhooks/sync-data.mdx
Minor typo in [Webhooks example](https://clerk.com/docs/integrations/webhooks/sync-data#create-the-endpoint-in-your-application) page
> docs: Minor typo fix

- docs/custom-flows/email-password.mdx
Current javascript example for sign in generates 
```
{"errors":[{"message":"is unknown","long_message":"email_address is not a valid parameter for this request.","code":"form_param_unknown","meta":{"param_name":"email_address"}}],"clerk_trace_id":"89afc5e93845ef1e7bedb54ab80e3ef7"}
```
Should be `identifier` instead of `emailAddress`. Also there was no `setActive` function defined.
> Fix email and password example for javascript

- docs/guides/add-onboarding-flow.mdx
- docs/references/nextjs/auth-middleware.mdx
- docs/upgrade-guides/core-2/nextjs.mdx
We list `authMiddleware` as being imported from `@clerk/nextjs`. This is wrong. It's from `@clerk/nextjs/server`.
> Fix authMiddleware imports in the docs

- docs/upgrade-guides/url-based-session-syncing.mdx
Cleans up and re-frames our url-based-session-syncing doc to communicate that this feature is on by default and cannot be opted out of, except in apps older than Dec 6 2022
> Update url-based-session-syncing guide

- docs/references/nextjs/auth.mdx
- docs/references/nextjs/get-auth.mdx
https://linear.app/clerk/issue/DOCS-6075/link-to-auth-docs-from-getauth-page-and-vice-versa
🔎 [getAuth()](https://docs-preview-903.clerkpreview.com/docs/references/nextjs/get-auth)
🔎 [auth()](https://docs-preview-903.clerkpreview.com/docs/references/nextjs/auth)
> DOCS-6075 Add reference to auth in getAuth doc

- docs/deployments/clerk-environment-variables.mdx
- docs/guides/add-onboarding-flow.mdx
- docs/references/nextjs/overview.mdx
- docs/upgrade-guides/core-2/chrome-extension.mdx
- docs/upgrade-guides/core-2/expo.mdx
- docs/upgrade-guides/core-2/javascript.mdx
- docs/upgrade-guides/core-2/nextjs.mdx
- docs/upgrade-guides/core-2/react.mdx
- docs/upgrade-guides/core-2/remix.mdx
[Request from this thread](https://clerkinc.slack.com/archives/C01QFRQNHSN/p1713890512288219)
- Also fixes broken links to the custom-redirects guide, which was breaking the linter
> Replace authMiddleware where appropriate

- docs/components/authentication/sign-in.mdx
- docs/components/authentication/sign-up.mdx
- docs/components/organization/create-organization.mdx
- docs/components/organization/organization-profile.mdx
- docs/components/user/user-profile.mdx
- docs/deployments/clerk-environment-variables.mdx
- docs/guides/routing.mdx
- docs/manifest.json
- docs/upgrade-guides/core-2/chrome-extension.mdx
- docs/upgrade-guides/core-2/expo.mdx
- docs/upgrade-guides/core-2/javascript.mdx
- docs/upgrade-guides/core-2/nextjs.mdx
- docs/upgrade-guides/core-2/react.mdx
- docs/upgrade-guides/core-2/remix.mdx
Adds guide on routing in Clerk.
Updates places where `path` is defined for Next.js and Remix examples and it's inferred and no longer required to be explicitly set.
Updates upgrade guides accordingly.
> Path prop not required for Next.js or Remix

- docs/authentication/configuration/email-sms-templates.mdx
The old links now redirect to the [redactor home page](https://imperavi.com/redactor/).
It's worth noting that the new links have a `/legacy/` path, and Revolvapp is now listed as "legacy" [on the imperavi home page](https://imperavi.com/#:~:text=Redactor%20Classic-,Revolvapp,-Books)
> Updating links to revolvapp product and docs.

- .github/workflows/revalidate.yml
When pull requests are updated we grab the changed files in the `docs` directory (using [`tj-actions/changed-files`](https://github.com/marketplace/actions/changed-files)) and send them to the `/docs/revalidate` [endpoint](https://github.com/clerk/clerk/blob/main/src/app/docs/revalidate/route.ts):
```bash
curl -X POST https://clerk.com/docs/revalidate \
-H "Content-Type: application/json" \
-H "Authorization: Bearer SECRET" \
-d "{\"files\": [\"docs/quickstarts/nextjs.mdx\"], \"pr\": 890}"
```
> Reinstate revalidate workflow for PR previews

- .github/workflows/revalidate.yml
Granular PR preview revalidation doesn't seem to be working as expected so updating the workflow to revalidate all PR preview pages for now.
The revalidation payload below will cause the `/docs/revalidate` endpoint to call `revalidatePath('/(website)/docs/pr/[number]', 'layout')` ([docs](https://nextjs.org/docs/app/api-reference/functions/revalidatePath))
```json
{"paths": [["/(website)/docs/pr/[number]", "layout"]]}
```
> Revalidate entire `docs/pr/[number]` layout on PR synchronise

- docs/custom-flows/email-password.mdx
This pr:
- Updates our instructions on enabling authentication options. The current steps lead to a 422 error.
- Adds a React import to the React examples to prevent errors
- Clarifies that user credentials will be stored in Clerk, but other services can still be used with Clerk auth
These are all in response to user feedback [you can find in this linear issue](https://linear.app/clerk/issue/DOCS-6138/test-and-update-our-custom-flows-email-password-docs).
> Update email-password custom flows guide

- docs/quickstarts/nextjs.mdx
I've seen a few people on Twitter say they miss where middleware should be placed if using /src. 
I'm hoping this makes that a bit more clear by breaking both options into separate bullet points.
> Tweak to middleware section in Next.js guide

- docs/deployments/clerk-environment-variables.mdx
This PR:
- Explains that our env vars work with meta-frameworks, and pure React users should stick to the ClerkProvider props ([per this discussion](https://clerkinc.slack.com/archives/C04KENP2GFL/p1712946780211689?thread_ts=1712946018.335729&cid=C04KENP2GFL))
- Removes React env var examples, as VITE env vars would only work for users deploying React with Vite
> Update env var guide

- docs/authentication/saml/azure.mdx
- docs/authentication/saml/custom-provider.mdx
- docs/authentication/saml/google.mdx
- docs/authentication/saml/okta.mdx
- docs/authentication/social-connections/linkedin-oidc.mdx
- docs/authentication/social-connections/x-twitter.mdx
- docs/elements/guides/sign-in.mdx
- docs/elements/guides/sign-up.mdx
- docs/guides/authjs-migration.mdx
- docs/guides/force-organizations.mdx
- docs/integrations/databases/convex.mdx
- docs/integrations/databases/firebase.mdx
- docs/integrations/databases/supabase.mdx
- docs/integrations/webhooks/sync-data.mdx
- docs/quickstarts/javascript.mdx
- docs/quickstarts/nextjs.mdx
- docs/quickstarts/react.mdx
- docs/references/nextjs/trpc.mdx
- docs/references/react/add-react-router.mdx
We can now set the `icon` for a `TutorialHero` link, which references one of the [available icons](https://github.com/clerk/clerk/blob/main/src/app/(website)/docs/icons.tsx)
This PR adds icons where they were missing, and specifies the icon explicitly where before the icon was automatically picked
Updated pages:
- [/docs/authentication/saml/azure](https://clerk.com/docs/pr/995/authentication/saml/azure)
- [/docs/authentication/saml/custom-provider](https://clerk.com/docs/pr/995/authentication/saml/custom-provider)
- [/docs/authentication/saml/google](https://clerk.com/docs/pr/995/authentication/saml/google)
- [/docs/authentication/saml/okta](https://clerk.com/docs/pr/995/authentication/saml/okta)
- [/docs/authentication/social-connections/linkedin-oidc](https://clerk.com/docs/pr/995/authen …
> Add explicit `icon` to `TutorialHero` links

- docs/elements/examples/sign-in.mdx
- docs/elements/examples/sign-up.mdx
- docs/elements/guides/sign-in.mdx
- docs/elements/guides/sign-up.mdx
- docs/elements/guides/styling.mdx
- docs/elements/overview.mdx
- docs/elements/reference/common.mdx
Remove repetitive note about `moduleResolution` from code blocks (made every code block extra wide + messed up line highlighting) and move it to package install steps. Those install steps were missing from the guides.
> Elements: Guide improvements

- docs/backend-requests/handling/nodejs.mdx
- docs/references/nodejs/overview.mdx
WARNING: In contrast to what the contributing guidelines say, I was NOT able to run `npm install` (and thus `npm run lint` ) because `npm install` errored out with `ReferenceError: unzipper is not defined` in the `\node_modules\@vvago\vale` folder (I'm on Windows). Despite that, I think a pull request might help you more than a simple issue.
---
This pull request
- adds the missing CLERK_PUBLISHABLE_KEY to the NodeJS reference page
- mentions CLERK_PUBLISHABLE_KEY on the backend requests page for nodejs
I think this change is important because when this env variable is not set, every expressjs authentication middleware errors out saying "Publishable key not valid". I just experienced this myself. It took me 30 minutes before seeing that the readme of the npm package …
> Nodejs reference: Add missing publishable key

- CONTRIBUTING.md
- docs/manifest.json
- docs/manifest.schema.json
This PR documents the new `target` property for manifest nav links, and adds `"target": "_blank"` to the following nav links:
- Troubleshooting > Community Discord
- Troubleshooting > Contact Support
- Backend API
- Frontend API
> Document `target` property for nav links and apply to some links in manifest

- docs/elements/guides/sign-in.mdx
- docs/elements/guides/sign-up.mdx
This PR adds an explicit `icon` property for the "Install Clerk Elements" link used in the `TutorialHero` on the following pages:
- [Build a sign-in flow with Clerk Elements](https://clerk.com/docs/elements/guides/sign-in)
- [Build a sign-up flow with Clerk Elements](https://clerk.com/docs/elements/guides/sign-up)
We have some logic in `clerk/clerk` that selects an icon automatically based on the link text, but I want to remove this and require setting the `icon` property if you want to display an icon. I also think this icon (which matches the "Elements" nav item) is better than the generic "clerk" one in this context
| - | - |
| ![CleanShot 2024-05-10 at 11 09 34@2x](https://github.com/clerk/clerk-docs/assets/2615508/605cbd7d-e4e0-4a4d-8459-e19cf2e4e36e) | ![CleanShot …
> Add explicit `icon` for "Install Clerk Elements"

- docs/manifest.json
- docs/manifest.schema.json
Just moving the `icon` property above `items` in the manifest because when `items` is a large array the `icon` prop gets shunted way down and it can be hard to find/figure out which item the icon belongs to
This PR also adds `link` to the list of available icons since it was added in https://github.com/clerk/clerk/pull/376
> Tweak manifest formatting

- docs/references/backend/overview.mdx
- docs/references/javascript/types/clerk-backend-api-response.mdx
- docs/references/nodejs/overview.mdx
[This plain issue](https://app.plain.com/workspace/w_01GT53BQWV3DFW6ECTWZNQ1E9K/thread/th_01HTJD9HCQFTGG0EEFA3N5KPAW/) has the following note:
> We need to make it clear in our docs for backend and node sdk that if there's an error, the methods won't throw, they will instead return the error.
This PR handles that.
> Update backend docs to explain error handling

- docs/components/overview.mdx
Follow up to #1020: I accidentally left some escapes in `docs/components/overview.mdx` that shouldn't be there and are causing the build to fail 🤦‍♂️
> Remove backtick escapes that were accidentally left in

- docs/elements/examples/shadcn-ui.mdx
- Adds section to shadcn/ui examples for how to use OTP input
- Updates OTP input codeblocks with latest demo
Preview: https://clerk.com/docs/pr/1029/elements/examples/shadcn-ui#otp-input
> feat(elements): add shadcn otp demo section

- docs/quickstarts/remix.mdx
- Remove duplicate Meta declarations (Same values set in both function and in html)
- Chose to keep values in function over HTML since then all meta is the same location
- Rename `routes/_index.html` to `routes/_index.tsx`
-  Given it is an "index" route, it is likely never intended to show in the url. This means it should be prefixed with underscore. This also more closely matches with structure of default remix application
- Remove extra empty lines
> docs: minor clean up for remix.mdx

- docs/custom-flows/error-handling.mdx
- docs/manifest.json
- docs/references/javascript/types/clerk-api-error.mdx
https://clerk.com/docs/pr/1034/custom-flows/error-handling
> update error handling for custom flows guide

- docs/elements/examples/shadcn-ui.mdx
This PR uses the `var(--light, lightValue) var(--dark, darkValue)` [trick](https://lightningcss.dev/transpilation.html#light-dark()-color-function) to set the background colour for the Elements shadcn/ui demos. This prevents the background colour from initialising with the incorrect colour.
**Before**
https://github.com/clerk/clerk-docs/assets/2615508/68c4ca75-ad37-4fc8-899d-a4268b336673
**After**
https://github.com/clerk/clerk-docs/assets/2615508/7a95b775-5497-47a9-be41-8ebeb2cae210
> Adapt demo placeholder background colour to active theme

- docs/quickstarts/nextjs.mdx
https://clerk.com/docs/pr/1061/quickstarts/nextjs
Remove create homepage step:
Per this discussion: https://clerkinc.slack.com/archives/C01QFRQNHSN/p1716128555906809
Many users will already have a Next.js application running, and won't really need the create a homepage step.
Add clerk-middleware to next steps:
Per this discussion: https://clerkinc.slack.com/archives/C01QFRQNHSN/p1716128688058099
Clerk middleware should be called out so that users can be directed on how to protect routes.
> (/quickstarts/nextjs) remove create homepage step; add clerk middleware to next steps

- docs/references/go/verifying-sessions.mdx
https://linear.app/clerk/issue/DOCS-6378/feedback-for-referencesgoverifying-sessions
Update docs here to show how to use the user ID from the jwt claims to get the user object
> DOCS-6378 Add example of getting user obj using Go sdk in verifying sessions doc

- docs/troubleshooting/email-deliverability.mdx
We should avoid saying we'll have users "set `SPF` records". Instead, mention that we'll have them set up various records, which will configure `SPF` among other things. Based on this slack discussion: https://clerkinc.slack.com/archives/C053FSYKAH1/p1716485775889239?thread_ts=1716216870.321359&cid=C053FSYKAH1
> Update email deliverability docs

- docs/integrations/databases/neon.mdx
The dependencies won't install if the React package isn't 18.3.**
> (/integrations/databases/neon) add instructions for updating react package

- docs/integrations/databases/neon.mdx
There was a leftover firebase mention in the Neon post, this PR removes it. Also, resolves an npm package install.
> [Edit] - remove firebase mention from Neon-Clerk tutorial

- docs/upgrade-guides/core-2/backend.mdx
The prior docs stated that functions like decodeJwt were to be imported from @clerk/backend/tokens, though @clerk/backend/jwt is the correct address based on installing @clerk/backend@^1.2.1
> Correct the path to JWT-related functions

- docs/upgrade-guides/long-term-support.mdx
- docs/upgrade-guides/sdk-versioning.mdx
This adds the minimum supported Node.js version + browser vendors to the LTS page.
Fixes SDK-1618
> feat: Add browser + Node.js compat to LTS page

- docs/manifest.json
- docs/manifest.schema.json
Related PR for adding the icon: https://github.com/clerk/clerk-marketing/pull/920
> Introduce Clerk Koa SDK (community)

- docs/references/backend/allowlist/get-allowlist-identifier-list.mdx
- docs/references/backend/invitations/get-invitation-list.mdx
- docs/references/backend/organization/get-organization-invitation-list.mdx
- docs/references/backend/redirect-urls/get-redirect-url-list.mdx
- docs/references/backend/sessions/get-session-list.mdx
- docs/references/backend/types/paginated-resource-response.mdx
We mention that `PaginatedResourceResponse` [only returns the first 10 items by default](https://clerk.com/docs/references/backend/types/paginated-resource-response?utm_source=www.google.com&utm_medium=referral&utm_campaign=none#returns), but in a couple instances this is not the case.
I've updated `PaginatedResourceResponse` page to mention this, and updated the individual backend sdk methods pages to say they return a list of "all" items, or to drop the word "all" where appropriate.
This is based on both the JavaScript SDK and the [Backend API](https://clerk.com/docs/reference/backend-api/).
[Relevant discussion thread here](https://clerkinc.slack.com/archives/C05LHV6AK50/p1716914568312259)
> Fixed PaginatedResourceResponse docs

- docs/manifest.json
@royanger [mentioned](https://clerkinc.slack.com/archives/C01QFRQNHSN/p1714601287288829) moving the "Other References" section of the Next.js sdk docs up above App and Pages router. This PR renames the section and moves it up
> Reorganize Nextjs sdk ref section

- docs/references/nextjs/current-user.mdx
- docs/references/nextjs/read-session-data.mdx
We have [a ticket](https://linear.app/clerk/issue/DOCS-6424/currentuser-doc-missing-rate-limit-callout) saying this isn't clear enough in the `current-user` docs page. We do mention the rate limit in a bullet point, but it isn't its own bullet point. I made it into its own bullet point, so hopefully that will improve clarity.
> Make rate limit impact of current-user clearer

- docs/manifest.json
- docs/organizations/inviting-users.mdx
https://clerk.com/docs/pr/1086/organizations/inviting-users
> DOCS-322 (/organizations/inviting-users) update nextjs example and add JS example

- docs/components/control/redirect-to-signin.mdx
- docs/components/control/redirect-to-signup.mdx
Got feedback that this was missing.
> Add app router example to redirect-to-x docs

- docs/manifest.json
- docs/organizations/custom-organization-switcher.mdx
- docs/organizations/inviting-users.mdx
- docs/organizations/manage-membership-requests.mdx
- docs/organizations/viewing-memberships.mdx
Technically, the "Build a custom organization switcher" guide isn't recreating the `<OrganizationSwitcher />`. That component is fully-featured and complex, including handling membership suggestions and requests and organization creation... This guide is simply for building a flow for switching between organizations.
So this PR updates the title of that page to more accurately reflect its content.
This PR also removes all unnecessary h2's from all of the organization custom flow guides.
> update title for org switcher custom flow guide; remove unnecessary h2s from all org custom flows

- docs/references/nextjs/clerk-middleware.mdx
We had the tab named incorrectly
> Change codeblock tab in Clerk Middleware docs

- docs/deployments/clerk-environment-variables.mdx
I found a couple typos on the `/deployments/clerk-environment-variables` page and corrected them.
> fix: Fix typo on clerk-environment-variables page

- docs/integrations/webhooks/inngest.mdx
This pull request fixes the incorrect property name for accessing the user's email address in the Clerk webhook documentation for Inngest integration. The property should be email_address instead of email.
Current code in the documentation:
```
const email = user.email_addresses.find(e =>
e.id === user.primary_email_address_id
).email;
```
Corrected code:
```
const email = user.email_addresses.find(e =>
e.id === user.primary_email_address_id
).email_address;
```
The current documentation uses .email, which does not exist in the email_addresses object structure. The correct property is .email_address, which aligns with the actual data structure returned by the Clerk API.
This fix addresses the issue described in Issue #1122 . By making this change, developers following the documentation …
> Fix incorrect email property name in Clerk webhook documentation

- docs/authentication/social-connections/account-linking.mdx
Sometimes a user may want to link an OAuth account that has a different email address from the one associated with their Clerk account. These instructions teach them how to do so, based on notes from [this linear issue](https://linear.app/clerk/issue/DOCS-246/how-clerk-handles-multiple-oauth-connectionslogin-methods).
> Add instructions for linking OAuth accounts with different emails

- docs/custom-flows/invitations.mdx
- docs/references/backend/invitations/create-invitation.mdx
This PR:
- Addresses updates that the Invitations custom flow guide needed overall.
🔎 Preview: https://clerk.com/docs/pr/1133/custom-flows/invitations
- Addresses the incorrect description of the `redirectUrl` prop for the `createInvitation()` method in the Backend SDK reference docs.
🔎 Preview: https://clerk.com/docs/pr/1133/references/backend/invitations/create-invitation#create-invitation
---
This PR does not address the fact that [Invitations custom flow guide](https://clerk.com/docs/custom-flows/invitations) definitely needs to get separated into two docs:
1. Invitations conceptual doc explaining how to create and revoke invitations
2. Custom flow doc explaining how to handle invitations with a custom flow
These things need to be addressed after the upcoming IA. …
> Update Invitations custom flow guide; update redirectUrl explanation for createInvitation() backend SDK method

- docs/custom-flows/embedded-email-links.mdx
This PR:
- Improves our docs on using sign-in tokens for authentication by adding information [from this comment](https://linear.app/clerk/issue/DOCS-6184/create-a-brief-guide-for-using-sign-in-tokens#comment-cbec9e54) to the embeddable links docs.
- Cleans up some of the language in the embeddable links doc
- Adds an app router code snippet
- Does not add an example of embedding a link. I don't think an example would be particularly useful, as it's just a link with a query param. I assume we're leaning so heavily into the "embeddable" aspect because of SEO, but it does feel odd to describe any link as specifically embeddable, since all links are embeddable, but of course I could be missing something here.
[Preview here](https://clerk.com/docs/pr/1139/custom-flows/embedded-email-links#embe …
> Improve info on using sign-in tokens

- docs/references/nextjs/auth.mdx
> [!IMPORTANT]
> 🔎 [Preview](https://clerk.com/docs/pr/1140/references/nextjs/auth#auth)
A [discussion](https://clerkinc.slack.com/archives/C01QFRQNHSN/p1717099431215419) arose regarding our `auth().protect()` helper where the explanation of `protect()` was not clear.
> update auth() docs to more accurately explain the protect() helper

- docs/organizations/verify-user-permissions.mdx
> [!IMPORTANT]
> 🔎 [Preview](https://clerk.com/docs/pr/1141/organizations/verify-user-permissions#verify-the-active-user-s-permissions-in-an-organization)
While [updating the `auth()` documentation to better explain the `protect()` helper](https://github.com/clerk/clerk-docs/pull/1140), I noticed that this page needed a lot of cleaning up - and we actually had a ticket for it!
This PR:
- cleans up copy that explains the code examples
- adds missing filenames to codeblocks
- updates the props for codeblocks to our new syntax 
- `{{ filename: '' }}`
- updates the names of tabs in code blocks to be consistent throughout the doc 
- `has()` `<Protect>` and `auth().protect()`
> Clean up /verify-user-permissions page

- docs/security/clerk-csp.mdx
Updates the CSP docs to ensure the provided values are formatted correctly. Also uses our `{{fapi_url}}` placeholder to inject the user's instance FAPI host.
> fix(CSP): fix directive syntax, ensure all necessary values are present

- docs/integrations/webhooks/debug-your-webhooks.mdx
- docs/integrations/webhooks/sync-data.mdx
The https://clerk.com/docs/integrations/webhooks/sync-data guide had TS in JS codeblocks. It also had incorrect import for `authMiddleware`.
Fixes https://github.com/clerk/clerk-docs/issues/1143
Fixes https://github.com/clerk/clerk-docs/issues/1144
> fix: Webhook guides typos

- docs/quickstarts/nextjs.mdx
Currently, the closing tag `</ClerkProvider>` the example is not highlighted, despite being part of the change set. This change adds the missing highlight.
> Add highlight also for closing provider tag line in the example

- docs/advanced-usage/satellite-domains.mdx
Based on [this thread](https://clerkinc.slack.com/archives/C01QFRQNHSN/p1717782950372629)
- [Preview](https://clerk.com/docs/pr/1146/advanced-usage/satellite-domains#configure-your-satellite-app)
This PR:
- Adds app router examples
- Specifies which env vars should be associated with primary domains vs satellite domains
- Does the same for which ClerkProvider props should be associated with which domain
- Removes the table of properties on the page. It looked a bit big and intimidating. I turned it into a list instead
- Puts the env vars and properties options into tabs so they can be swapped between and take up less space
> Update satellite domains guide

- docs/elements/examples/shadcn-ui.mdx
This PR introduces several updates to enhance the handling of email input fields and the email verification process within the sign-up and sign-in forms. These changes aim to improve user experience and data validation.
**Modifications**
1. Email Input Type:
- Changed input type to `email` in the sign-up form to ensure proper email validation.
2. Email Verification:
- Updated verification strategy fields to accurately reflect the email verification process.
- Adjusted field names for consistency in email verification steps.
**Benefits**
- Enhanced user experience through more intuitive and accurate email input handling.
- Improved data validation for email fields, reducing errors and ensuring proper email formats.
- Consistency in the email verification process, making it clearer for …
> Update Input Fields for Email Validation and Verification Process in `shadcn-ui` Example Forms

- docs/references/backend/user/update-user-metadata.mdx
[DOCS-8803](https://linear.app/clerk/issue/DOCS-8803/feedback-for-referencesbackenduserupdate-user-metadata) reads:
> User's feedback: Does it override or extend the metadata? It's not clear how this works.
From the [backend API reference docs](https://clerk.com/docs/reference/backend-api/tag/Users#operation/UpdateUserMetadata), it reads:
"Update a user's metadata attributes by merging existing values with the provided parameters."
This PR:
- adds this information to the updateUserMetadata doc
> (/backend/user/update-user-metadata) method merges instead of full replace

- docs/authentication/configuration/sign-up-sign-in-options.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1172/authentication/configuration/sign-up-sign-in-options
[DOCS-6346](https://linear.app/clerk/issue/DOCS-6346/feedback-for-authenticationconfigurationsign-up-sign-in-options) reads:
> User's feedback: It says you can require Multi factor auth, but I can't find where in the Clerk dashboard where I can enforce this for all users in a given app or org
- updates the description for enabling MFA
- adds reference to clerk elements
> (/sign-up-sign-in-options) Clarify enabling MFA does not require it for all users

- docs/guides/image-optimization/imageurl-image-optimization.mdx
We are updating the `width` param to return an image larger than the requested width
Currently, the img.clerk.com is returning the exact width requested. We're updating that API to return a few specific widths, rather than infinitely customizable widths
The current docs claim that `width` is a maximum width. We don't believe that to be a very useful API. Developers generally care about getting the smallest possible image that will look good at a specific width, not the largest possible (but still a bit blurry) image that will be under a specific size.
This won't impact any users of clerk's SDK. Users who are consuming the API directly and have an image width defined will sometimes receive larger-than-requested images, but layout will not break. Usage sampling of our API has revealed only …
> Change "width" param to behave as a min-width

- docs/quickstarts/react.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
The "[Create a header with Clerk components](https://clerk.com/docs/quickstarts/react#create-a-header-with-clerk-components)" section of the React Quickstart docs contains a snippet where certain lines are highlighted to indicate a change. The current highlighted lines are from `7-12`, which does not accurately represent the change in the code.
- Updates it to highlight the correct lines, changing the range to 6-11
- Ensures that the highlighted section are the added components
> Fix highlighted code in React Quickstart

- docs/quickstarts/expo.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
The Sign In flow (for Expo) documentation uses an undeclared variable to check Sign In status. 
- replaces `completeSignIn` with `signInAttempt` in the `Sign-in page` section - [section link](https://clerk.com/docs/quickstarts/expo#sign-in-page)
> Update expo signInAttempt missing variable

- docs/components/customization/user-profile.mdx
- docs/components/protect.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
[User feedback ticket](https://linear.app/clerk/issue/DOCS-8649/deal-with-it-alexis) reads:
> why are you talking about <Header /> with no context as to what that is or why we are putting this into a generic header component. None of these examples work also, you can paste them into a standard Profile or UserProfile and they actually dont do anything
- Fixed the working examples
> Fix working examples for custom User Profile pages

- docs/references/react/use-user.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
[User feedback ticket](https://linear.app/clerk/issue/DOCS-8658/feedback-for-referencesreactuse-user) reads:
> In the section "Reload user data with the useUser() hook", Line 18, it should say:
if(updateMetadata.message !== "success")
- Fixes the conditional statement in the code example
> (/react/use-user) fix conditional statement in code example

- docs/custom-flows/error-handling.mdx
- docs/manifest.json
> [!IMPORTANT]
> 🔎 Previews:
>
> -
[User feedback ticket](https://linear.app/clerk/issue/DOCS-8832/%F0%9F%A4%A9-feedback-for-custom-flowserror-handling) reads:
> This page is helpful, but I would like to see a full list of http errors similar to the JSON seen in the User Locked example.
> If this already exists, I can't find it.  It would be good to have a link to the correct page.
- Adds a callout that references our Clerk-related errors docs, in the custom flow error handling doc.
> add reference to errors doc in the custom flow error handling guide

- docs/advanced-usage/satellite-domains.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
[User feedback ticket](https://linear.app/clerk/issue/DOCS-8822/add-pricing-info-on-satellite-domains-page) reads:
> Include the plan name needed to use this feature as this cannot be achieved on free tier, and i don't think its possible to make it work on multiple domains unless paying for enterprise.
- Adds a WARNING callout about pricing
> Add pricing info on satellite domains page

- docs/references/backend/sessions/verify-session.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1188/references/backend/sessions/verify-session#verify-session-deprecated
[User feedback ticket ](https://linear.app/clerk/issue/DOCS-8818/%F0%9F%98%A2-feedback-for-referencesbackendsessionsverify-session) reads:
> what is it depreciated in favor of?
- adds an alternative to the deprecated method in the callout of the doc
> Offer alternative to the deprecated verifySessions method

- docs/integrations/databases/neon.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
This PR removes the usage of `dotenv` from the neon guide. While a small change, it favors the use of framework-specific utility libraries and reduces unnecessary dependencies, thus simplifying the overall setup.
- Replaced `dotenv` with [`@next/env`](https://www.npmjs.com/package/@next/env) utility for loading environment variables.
- Added a check for `DATABASE_URL` in `drizzle.config.ts`.
> Replace dotenv with @next/env in neon guide

- docs/guides/add-onboarding-flow.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - add-onboarding-flow.mdx
It not easy to notice that developers should call `user.reload()` on the frontend after updating the user's `publicMetadata` on the backend when following the guide ***Add custom onboarding to your authentication flow***. Making that call is a necessary part of the logic and has security implication depending on the use-case. 
Discord issue: https://discord.com/channels/856971667393609759/1253768303483162644
- This PR adds a callout to making a `user.reload()` function call. 
- Also calls it out in the provided code-block incase it's not read earlier on the page.
> (/guides/add-onboarding-flow) Add code comment that explains user.reload()

- docs/authentication/social-connections/oauth.mdx
- docs/guides/add-onboarding-flow.mdx
- docs/guides/basic-rbac.mdx
- docs/references/backend/organization/update-organization-logo.mdx
- docs/references/backend/sessions/authenticate-request.mdx
- docs/references/backend/sessions/get-token.mdx
- docs/references/backend/user/update-user.mdx
- docs/references/nextjs/build-clerk-props.mdx
- docs/references/nextjs/get-auth.mdx
- docs/references/nextjs/read-session-data.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
[clerk/javascript#3617](https://github.com/clerk/javascript/pull/3617) introduced a change where `clerkClient` is now called as a function instead of a singleton for the Clerk Next.js SDK
- Updates all instances of `clerkClient` for `@clerk/nextjs` examples
> call clerkClient as a function instead of singleton for @clerk/nextjs

- docs/manifest.json
- docs/references/backend/sign-in-tokens/create-sign-in-token.mdx
- docs/references/backend/sign-in-tokens/revoke-sign-in-token.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1221/references/backend/sign-in-tokens/create-sign-in-token
> - https://clerk.com/docs/pr/1221/references/backend/sign-in-tokens/revoke-sign-in-token
Missing docs
- Adds doc for the [SignInTokens API](https://github.com/clerk/javascript/blob/main/packages/backend/src/api/endpoints/SignInTokenApi.ts)
> Add SignInTokens API to Backend SDK

- docs/authentication/configuration/email-sms-templates.mdx
- docs/authentication/configuration/sign-up-sign-in-options.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1244/authentication/configuration/email-sms-templates
> - https://clerk.com/docs/pr/1244/authentication/configuration/sign-up-sign-in-options
This includes:
* SMS allowlist
* SMS template enabled status toggle
* SMS template approval flow
This PR:
https://clerk.com/docs/pr/1244/authentication/configuration/email-sms-templates
- Removes unnecessary info, including lists of templates (as these can become outdated and are hard to maintain)
- Reorganizes the email-sms-templates page. Settings that were available to both Email and SMS templates are now only available to Email templates, so these sections were moved under #edit-email-templates and the sections were abstracted into bullet points. Also, missing UI information was added …
> feat: Add sections corresponding to new SMS UI functionality in dashboard

- docs/organizations/verify-user-permissions.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1243/organizations/verify-user-permissions
[Linear ticket](https://linear.app/clerk/issue/DOCS-8824/clarify-callout-about-pbac-rbac-best-practice)
- Updates wording in callout to suggest PBAC over RBAC
- Also updates wording in callout about active orgs; adds a reference link to active orgs section in org overview
> Update wording in callout to suggest PBAC over RBAC

- docs/manifest.json
- docs/references/backend/saml-connections/create-saml-connection.mdx
- docs/references/backend/saml-connections/delete-saml-connection.mdx
- docs/references/backend/saml-connections/get-saml-connection-list.mdx
- docs/references/backend/saml-connections/get-saml-connection.mdx
- docs/references/backend/saml-connections/update-saml-connection.mdx
- docs/references/backend/types/saml-connection.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - [getSamlConnectionList()](https://clerk.com/docs/pr/1223/references/backend/saml-connections/get-saml-connection-list)
> - [getSamlConnection()](https://clerk.com/docs/pr/1223/references/backend/saml-connections/get-saml-connection)
> - [createSamlConnection()](https://clerk.com/docs/pr/1223/references/backend/saml-connections/create-saml-connection)
> - [updateSamlConnection()](https://clerk.com/docs/pr/1223/references/backend/saml-connections/update-saml-connection)
> - [deleteSamlConnection()](https://clerk.com/docs/pr/1223/references/backend/saml-connections/delete-saml-connection)
Missing docs
https://github.com/clerk/javascript/blob/main/packages/backend/src/api/endpoints/SamlConnectionApi.ts
- Adds `samlConnections` api to backend sdk docs
> Add SamlConnection API to Backend SDK

- docs/manifest.json
- docs/references/backend/client/get-client.mdx
- docs/references/backend/client/verify-client.mdx
- docs/references/backend/types/backend-client.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
Part of the work for checking that our /backend/* reference docs were up to date ([due to this linear ticket](https://linear.app/clerk/issue/DOCS-6039/check-that-our-docsreferencesbackend-pages-match-our-backend-api))
I added each pages' corresponding `clerk/javascript` file in a comment on at the top of the page. Adding these links will make it easy to find where these methods exist in the `clerk/javascript` repo when updating their respective pages.
I updated pages accordingly to reflect the BAPI docs.
> Update Client Backend SDK docs to match BAPI docs

- docs/manifest.json
- docs/references/backend/domains/delete-domain.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1214/references/backend/domains/delete-domain
Missing doc
- Adds doc for `deleteDomain` method
> Add deleteDomain method to Backend SDK

- docs/integrations/webhooks/loops.mdx
Makes sure the proper step headings show on the Loops webhooks page (changing `<h2>` to `<h3>`.
> Fix Step headings on Loops page

- docs/manifest.json
- docs/quickstarts/astro.mdx
- docs/references/astro/ui-react.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1255/references/astro/ui-react
-
> Create a guide for Astro and React

- docs/manifest.json
- docs/quickstarts/remix.mdx
- docs/references/remix/custom-signup-signin-pages.mdx
- docs/references/remix/read-session-data.mdx
- docs/references/remix/spa-mode.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1270/quickstarts/remix
> - https://clerk.com/docs/pr/1270/references/remix/spa-mode
> - https://clerk.com/docs/pr/1270/references/remix/custom-signup-signin-pages
> - https://clerk.com/docs/pr/1270/references/remix/read-session-data
Refactoring @anagstef's SPA Mode doc and the existing Remix Quickstart to move info about creating sign-in/up routes and the reading user data to their own guides. This removes duplication of information and lines up with the approach in the Next.js quickstart.
> Moved signin/up routes and user data each to their own pages

- docs/manifest.json
- docs/quickstarts/remix.mdx
- docs/references/remix/custom-signup-signin-pages.mdx
- docs/references/remix/read-session-data.mdx
- docs/references/remix/spa-mode.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1266/references/remix/spa-mode
> - https://clerk.com/docs/pr/1266/quickstarts/remix
The Remix SPA mode docs page was showcasing how to convert an existing Clerk-Remix project into a SPA mode. Probably, this won't be the case for most people.
- Creates a guide similar to the Remix quickstart, that will help devs install Clerk into a Remix that uses the SPA mode.
> Convert the Remix SPA mode page into a guide for apps without Clerk

- docs/components/customization/organization-profile.mdx
- docs/components/customization/user-profile.mdx
- docs/components/organization/organization-profile.mdx
- docs/components/user/user-profile.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1258/components/customization/user-profile#java-script-example
> - https://clerk.com/docs/pr/1258/components/customization/organization-profile#java-script-example
[Linear ticket](https://linear.app/clerk/issue/DOCS-8899/bring-back-the-custom-pages-javascript-guides) reads:
Hello, I think 2 pages have gone missing:
https://github.com/clerk/clerk-docs/pull/404/files#diff-f23176b48e0e8683714aa153471f80873011acb8791a295ede6c9c4d272d7316
https://github.com/clerk/clerk-docs/pull/404/files#diff-857e57c057659631021e10bbf03cd7e34c8edc25306790483838ce149d5f1740
These two pages showcase how to use the Custom Pages if you are using vanilla JS.
I have also seen people in Discord looking for relevant information: …
> Reintroduce JS SDK examples for adding custom pages to components

- docs/manifest.json
- docs/references/astro/auth-store.mdx
- docs/references/astro/clerk-store.mdx
- docs/references/astro/organization-store.mdx
- docs/references/astro/overview.mdx
- docs/references/astro/read-session-data.mdx
- docs/references/astro/session-list-store.mdx
- docs/references/astro/session-store.mdx
- docs/references/astro/sign-in-store.mdx
- docs/references/astro/sign-up-store.mdx
- docs/references/astro/user-store.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1259/references/astro/auth-store
> - https://clerk.com/docs/pr/1259/references/astro/clerk-store
> - https://clerk.com/docs/pr/1259/references/astro/user-store
> - https://clerk.com/docs/pr/1259/references/astro/sign-in-store
> - https://clerk.com/docs/pr/1259/references/astro/sign-up-store
> - https://clerk.com/docs/pr/1259/references/astro/session-store
> - https://clerk.com/docs/pr/1259/references/astro/session-list-store
> - https://clerk.com/docs/pr/1259/references/astro/organization-store
> - https://clerk.com/docs/pr/1259/references/astro/overview
> - https://clerk.com/docs/pr/1259/references/astro/read-session-data
- Adds usage of different stores that acts like the client-side helper hooks of the React SDK
> docs(astro): Add nanostores usage

- docs/integrations/databases/neon.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1234/integrations/databases/neon
The current Neon guide, despite being written for Clerk, doesn't highlight the use of Clerk APIs within the demo app.
- Removed unnecessary drizzle migration step.
- Reordered final steps to improve continuity.
- Highlighted usage of clerk skd in middleware and server actions.
- Edited section titles
- Remove `classNames` for better readability
- Simplify code blocks
> improve Neon guide, highlighting API use in Next.js

- docs/elements/reference/sign-up.mdx
https://linear.app/clerk/issue/SDK-1874/provide-the-options-for-signupstrategys-name-prop-within-the-elements
Update SignUp strategy name property with available options vs marking as `string`
> chore(elements): Use available strategy names vs string in properties

- docs/components/organization/organization-switcher.mdx
- docs/organizations/overview.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1241/organizations/overview#active-organization
[The linear ticket](https://linear.app/clerk/issue/DOCS-8865/clarify-organization-account-wording) reads:
> On [the organizations overview page](https://clerk.com/docs/organizations/overview#active-organization), there are multiple mentions of "personal accounts" and "organization accounts" - while I get what we're after here, we had a prospective customer get confused by this and think that there were different account types - user accounts and org accounts, and both operated independently. This isn't the case, there are only user accounts, and users belong to organizations. I think we could probably clarify the wording here to make it clear how this works.
- Updates the …
> Update explanation of "active organizations"

- docs/authentication/configuration/email-sms-templates.mdx
We are switching over to a new SMS provider (Prelude) very soon, and this makes changes to the SMS message body for verification OTP templates a manual process. In addition, the changes possible are very limited.
As a result, we want to update the docs to call this out and tell customers to contact support if they must change it.
> Update SMS template docs about verification code OTP templates

- docs/elements/reference/sign-in.mdx
Social connections are not supported within SupportedStrategy.
> fix(elements): Remove social connections from `<SupportedStrategy>` name property

- docs/components/overview.mdx
- docs/manifest.json
- docs/quickstarts/astro.mdx
- docs/references/astro/auth-store.mdx
- docs/references/astro/clerk-middleware.mdx
- docs/references/astro/clerk-store.mdx
- docs/references/astro/endpoints.mdx
- docs/references/astro/locals.mdx
- docs/references/astro/migrating-from-astro-community-sdk.mdx
- docs/references/astro/organization-store.mdx
- docs/references/astro/overview.mdx
- docs/references/astro/react.mdx
- docs/references/astro/read-session-data.mdx
- docs/references/astro/session-list-store.mdx
- docs/references/astro/session-store.mdx
- docs/references/astro/sign-in-store.mdx
- docs/references/astro/sign-up-store.mdx
- docs/references/astro/user-store.mdx
Full editorial of Astro docs that were released today.
We're going to use external links for links that take you from the Astro SDK to another SDK (such as our Nextjs SDK). This is a temporary solution until we figure out how to deal with related/duped docs.
> Review/updates for Astro docs

- docs/advanced-usage/satellite-domains.mdx
- docs/guides/add-onboarding-flow.mdx
- docs/guides/custom-redirects.mdx
- docs/guides/force-organizations.mdx
- docs/integrations/databases/neon.mdx
- docs/integrations/webhooks/debug-your-webhooks.mdx
- docs/integrations/webhooks/sync-data.mdx
- docs/quickstarts/nextjs.mdx
- docs/references/nextjs/auth-middleware.mdx
- docs/references/nextjs/clerk-middleware.mdx
- docs/upgrade-guides/core-2/nextjs.mdx
For more context, please refer to https://github.com/clerk/javascript/pull/3741 
- Updates all instances of the old nextjs matcher with the updated one.
> Update the nextjs default middleware matcher

- docs/references/react/add-react-router.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1298/references/react/add-react-router
In order to improve DX within our docs, the lib managers order should be consistent from page to page, to reduce confusion and maintain patterns across the docs.
- Update the add-react-router page codeblock options prop to have an array of `['npm', 'yarn', 'pnpm']` to match the same order as the previous React quick start guide's codeblock order
> Refactor: Update order of lib managers in the CodeBlockTabs on the add-react-router reference page

- docs/advanced-usage/clerk-idp.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1300/advanced-usage/clerk-idp#use-clerk-as-an-o-auth-2-provider
- Added a `warning` callout to the top of the pag.e
- Customers continue to the think the Clerk as OAuth provider features returns a JWT.
> Added warning to top of Clerk as IDP/Oauth Provider that it does not return JWT

- docs/quickstarts/expo.mdx
I checked the quickstart repo, and could not find an example of an import like expo-navigation being used. Both in the quickstart and further up in these docs the expo-router is used for Slot components. This was reported in Support.
> Expo import navigation -> router fix

- docs/backend-requests/versioning/overview.mdx
The third option that supposed to go there isn't released yet so in the meantime it needs to be changed to two 👍
> fix: Typo in backend versioning

- docs/custom-flows/invitations.mdx
- docs/manifest.json
- docs/users/invitations.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1307/custom-flows/invitations
> -  https://clerk.com/docs/pr/1307/users/invitations
Our "invitations" custom flow was out of date.
- Moves general/conceptual information about invitations (such as what they are, how to create, how to revoke) into its own dedicated guide: https://clerk.com/docs/pr/1307/users/invitations
- Updates custom flow guide - adds full working next.js AND javascript examples
> Custom flow for sign-up with application invitations

- docs/elements/reference/sign-in.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1281/elements/reference/sign-in#safe-identifier
>
> 🚫 Waiting For Release:
>
> - https://github.com/clerk/javascript/pull/3749
> - https://github.com/clerk/javascript/pull/3745
Adds docs for the upcoming strategy-aware `SafeIdentifier` component.
- Adds docs for the new strategy-aware `SafeIdentifier`, including the new `transform` prop.
> feat(elements): Add docs for strategy-based SafeIdentifier

- docs/references/nextjs/clerk-middleware.mdx
> [!IMPORTANT]
> 🔎 Previews: 
>
> - https://clerk.com/docs/pr/1318/references/nextjs/clerk-middleware
The first example of the default next.js middleware matcher on this page is now outdated. 
- Updates the first reference to the next.js middleware matcher. Other references were updated in #1275
> fix: update matcher for clerk middleware

- docs/references/astro/clerk-middleware.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1319/references/astro/clerk-middleware#protect-routes-based-on-user-authentication-status
This small PR fixes an incorrect value passed to the route matcher, and some clean ups for consistency.
> docs(astro): Fix incorrect route matcher param

- docs/custom-flows/email-sms-otp.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1286/custom-flows/email-sms-otp
- Adds iOS example code to the Email/SMS OTP custom flow page.
> Add iOS example code to Email / SMS OTP Custom Flow

- docs/testing/cypress.mdx
This PR merely removes a repeated phrase from the doc on Cypress.
It removes the repetition. :)
-
> remove repetition in Cypress doc

- docs/telemetry.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1324/telemetry#framework-specific-instructions
- Adds new tab in frameworks list for disabling telemetry data collection for Astro
> Add option to opt-out of telemetry for Astro

- docs/quickstarts/expo.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
- Removes a stray `\` that was causing a malformed markdown link
> fix: remove errant slash

- docs/manifest.json
Page is coming up as 404 because it was removed, but wasn't removed from sidenav
> Remove /nodejs/token-verification from sidenav

- docs/integrations/webhooks/sync-data.mdx
- docs/references/astro/migrating-from-astro-community-sdk.mdx
- docs/upgrade-guides/core-2/backend.mdx
- docs/upgrade-guides/core-2/chrome-extension.mdx
- docs/upgrade-guides/core-2/expo.mdx
- docs/upgrade-guides/core-2/fastify.mdx
- docs/upgrade-guides/core-2/javascript.mdx
- docs/upgrade-guides/core-2/nextjs.mdx
- docs/upgrade-guides/core-2/node.mdx
- docs/upgrade-guides/core-2/react.mdx
- docs/upgrade-guides/core-2/remix.mdx
- prettier-mdx.mjs
This PR replaces uses of the `diff` code block language with the `del` and `ins` props ([documentation](https://github.com/clerk/clerk-docs/blob/main/CONTRIBUTING.md#highlighting)).
This format allows for code within code blocks to be formatted, and syntax highlighted in code editors.
**Before**
````markdown
```diff
- console.log('hi')
+ console.log('yo')
```
````
**After**
````markdown
```js {{ del: [1], ins: [2] }}
console.log('hi')
console.log('yo')
```
````
> Replace code block `diff` lang with `del`/`ins` props

- docs/authentication/social-connections/microsoft.mdx
- docs/components/customization/overview.mdx
- docs/deployments/migrate-overview.mdx
- docs/integrations/databases/firebase.mdx
- docs/quickstarts/astro.mdx
- docs/quickstarts/expo.mdx
- docs/quickstarts/gatsby.mdx
- docs/quickstarts/javascript.mdx
- docs/quickstarts/nextjs.mdx
- docs/quickstarts/react.mdx
- docs/quickstarts/remix.mdx
- docs/quickstarts/setup-clerk.mdx
- docs/references/astro/react.mdx
- docs/references/expo/web-support/custom-signup-signin-pages.mdx
- docs/references/expo/web-support/overview.mdx
- docs/references/nextjs/custom-signup-signin-pages.mdx
- docs/references/react/add-react-router.mdx
- docs/references/redwood/overview.mdx
- docs/references/remix/custom-signup-signin-pages.mdx
- docs/references/remix/spa-mode.mdx
- docs/users/web3.mdx
This PR updates the usage of the `<Cards>` (and `<FrameworkCards>`) component. The previous usage has been deprecated (and the new usage documented) since #1017.
---
**Before**
```jsx
<div className="container mx-auto my-4">
<div className="grid grid-cols-1 gap-6 md:grid-cols-2">
<Cards
title="SAML SSO with Microsoft Azure AD"
description="Learn how to integrate Microsoft Azure AD with Clerk using SAML SSO."
link="/docs/authentication/saml/azure"
cta="Learn More"
/>
<Cards
title="Account Linking"
description="Learn how Clerk handles account linking and manages unverified email addresses from OAuth providers."
link="/docs/authentication/social-connections/account-linking"
cta="Learn More"
/>
</div>
</div>
```
**After**
```jsx
<Cards>
- [SAML SSO with Microsoft Azure …
```
> Update `<Cards>` usage

- docs/organizations/overview.mdx
- docs/references/javascript/clerk/session-methods.mdx
- docs/references/react/use-organization-list.mdx
- docs/references/react/use-session-list.mdx
- docs/references/react/use-sign-in.mdx
- docs/references/react/use-sign-up.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1328/references/javascript/clerk/session-methods#set-active-params
> - https://clerk.com/docs/pr/1328/references/react/use-sign-in#set-active-params
> - https://clerk.com/docs/pr/1328/references/react/use-sign-up#set-active-params
> - https://clerk.com/docs/pr/1328/references/react/use-session-list#set-active-params
> - https://clerk.com/docs/pr/1328/references/react/use-organization-list#set-active-params
- Updates all occurrences of `setActive` params to state that an organization slug can be used besides the ID.
- https://github.com/clerk/javascript/pull/3825
> Update setActive occurrences to state that org slug is accepted

- docs/references/sdk/terminology.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1346/references/sdk/terminology#cookies
- Adds Clerk cookies in the SDK spec under the Terminology section
> Add cookies section on the SDK spec terminology

- docs/guides/add-onboarding-flow.mdx
- docs/guides/authjs-migration.mdx
- docs/guides/custom-redirects.mdx
- docs/integrations/databases/convex.mdx
- docs/integrations/databases/neon.mdx
- docs/integrations/webhooks/sync-data.mdx
- docs/quickstarts/astro.mdx
- docs/quickstarts/expo.mdx
- docs/quickstarts/gatsby.mdx
- docs/quickstarts/nextjs.mdx
- docs/quickstarts/react.mdx
- docs/quickstarts/remix.mdx
- docs/references/nextjs/custom-signup-signin-pages.mdx
- docs/references/redwood/overview.mdx
- docs/references/remix/custom-signup-signin-pages.mdx
- docs/references/remix/spa-mode.mdx
This PR replaces usage of the `sh` language for environment variable file (`.env`) snippets. The `env` language is an alias for `shell`/`sh` (see https://github.com/clerk/clerk/pull/538), but using `env` where appropriate allows us to differentiate between `.env` snippets and command line snippets.
> Use `env` lang for environment variable code blocks

- prettier-mdx.mjs
The `{{ ins, del }}` syntax for codeblocks is still supported, but we want to support `diff` as a language, as well.
> Allow diff to be used as language for codeblocks

- docs/custom-flows/email-sms-otp.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1374/custom-flows/email-sms-otp
[User feedback ticket ](https://linear.app/clerk/issue/DOCS-8901/remove-seterror-from-custom-flow-guide)reads:
> Small typo in the code snippet, setError doesnt exist
-
> (/email-sms-otp) Remove setError call in code example

- docs/custom-flows/overview.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1373/custom-flows/overview
Ticket reads:
> This page walks through the primitives, where following one of the guides is more or less always what user will want to do. [There's an example here](https://clerkinc.slack.com/archives/C05AVH96DAA/p1719871397075779) of a user who wanted a custom flow but got derailed by the low level instructions on the overview page rather than jumping into the guides in the sidebar.
> I think something like a callout at the top linking to the most common or popular custom flow guides, with a more explicit mention before the "fundamentals" section might be helpful. Or even moving the fundamentals into a separate document that we link to from overview?
- Adds a callout that points users to custom flow …
> (/custom-flows/overview) add callout pointing users to guides

- docs/elements/reference/common.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1330/elements/reference/common#input-type-password-validate-password
>
> 🚫 Waiting For Release:
>
> - https://github.com/clerk/javascript/pull/3812
Add docs for new `config` field for `FieldState`.
-
> docs(elements): Add docs for `FieldState` `config` field

- docs/authentication/social-connections/custom-provider.mdx
- docs/deployments/clerk-cookies.mdx
- docs/references/ios/overview.mdx
Replacing a few instances of `<Callout>` so we can remove support for using the component directly 🔪
> Replace `<Callout>` usage

- docs/manifest.json
- docs/quickstarts/expo.mdx
- docs/references/expo/read-session-user-data.mdx
> [!WARNING]
> Need [clerk/clerk#549](https://github.com/clerk/clerk/pull/549) merged for redirects
Needed to remove an unused import from an expo doc. Also found that the /expo/expo-read-session-user-data doc doesn't /expo twice.
> Rename Expo read-session-user-data doc; remove unused import

- docs/components/organization/create-organization.mdx
- docs/components/organization/organization-list.mdx
- docs/components/organization/organization-switcher.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1386/components/organization/create-organization#properties
> - https://clerk.com/docs/pr/1386/components/organization/organization-list#properties
> - https://clerk.com/docs/pr/1386/components/organization/organization-switcher#organization-switcher-properties
- Adds a new `hideSlug` prop to all organization components
- https://github.com/clerk/javascript/pull/3882
> Add hideSlug prop definition to Organization components

- docs/elements/examples/shadcn-ui.mdx
- docs/elements/examples/sign-up.mdx
- docs/elements/guides/sign-up.mdx
- docs/elements/reference/sign-up.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1398/elements/examples/shadcn-ui#sign-up
> - https://clerk.com/docs/pr/1398/elements/reference/sign-up#usage
- Adding `<SignUp.Captcha />` usage to Elements examples
> chore(elements): Add captcha usage to examples

- docs/references/expo/read-session-user-data.mdx
- docs/references/gatsby/with-server-auth.mdx
- docs/references/go/other-examples.mdx
- docs/references/go/overview.mdx
- docs/references/go/verifying-sessions.mdx
- docs/references/nextjs/auth-middleware.mdx
- docs/references/nextjs/auth-object.mdx
- docs/references/nextjs/auth.mdx
- docs/references/nextjs/build-clerk-props.mdx
- docs/references/nextjs/clerk-middleware.mdx
- docs/references/nextjs/current-user.mdx
- docs/references/nextjs/custom-signup-signin-pages.mdx
- docs/references/nextjs/get-auth.mdx
- docs/references/nextjs/read-session-data.mdx
- docs/references/nextjs/route-handlers.mdx
- docs/references/nextjs/server-actions.mdx
- docs/references/nextjs/trpc.mdx
- docs/references/nextjs/usage-with-older-versions.mdx
- docs/references/nodejs/available-methods.mdx
- docs/references/nodejs/overview.mdx
- docs/references/redwood/overview.mdx
- docs/references/ruby/available-methods.mdx
- docs/references/ruby/overview.mdx
- docs/references/ruby/rack-rails.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1404/references/expo/read-session-user-data
> - https://clerk.com/docs/pr/1404/references/gatsby/with-server-auth
> - https://clerk.com/docs/pr/1404/references/go/other-examples
> - https://clerk.com/docs/pr/1404/references/go/overview
> - https://clerk.com/docs/pr/1404/references/go/verifying-sessions
> - https://clerk.com/docs/pr/1404/references/nextjs/auth-middleware
> - https://clerk.com/docs/pr/1404/references/nextjs/auth-object
> - https://clerk.com/docs/pr/1404/references/nextjs/auth
> - https://clerk.com/docs/pr/1404/references/nextjs/build-clerk-props
> - https://clerk.com/docs/pr/1404/references/nextjs/clerk-middleware
> - https://clerk.com/docs/pr/1404/references/nextjs/current-user
> - …
> Enable Prettier for code blocks: `references/{expo,gatsby,go,nextjs,nodejs,redwood,ruby}`

- docs/advanced-usage/satellite-domains.mdx
- docs/components/control/redirect-to-organizationprofile.mdx
- docs/components/control/redirect-to-signin.mdx
- docs/components/control/redirect-to-signup.mdx
- docs/components/control/redirect-to-userprofile.mdx
- docs/components/organization/organization-list.mdx
- docs/components/user/user-button.mdx
- docs/custom-flows/add-email.mdx
- docs/custom-flows/add-phone.mdx
- docs/custom-flows/email-links.mdx
- docs/custom-flows/email-sms-otp.mdx
- docs/custom-flows/embedded-email-links.mdx
- docs/custom-flows/error-handling.mdx
- docs/custom-flows/invitations.mdx
- docs/custom-flows/manage-sms-based-mfa.mdx
- docs/custom-flows/saml-connections.mdx
- docs/elements/guides/styling.mdx
- docs/elements/reference/common.mdx
- docs/guides/force-organizations.mdx
- docs/integrations/databases/hasura.mdx
- docs/integrations/databases/supabase.mdx
- docs/organizations/creating-organizations.mdx
- docs/organizations/inviting-users.mdx
- docs/organizations/managing-roles.mdx
- docs/organizations/updating-organizations.mdx
- docs/testing/test-emails-and-phones.mdx
- docs/upgrade-guides/core-2/backend.mdx
- docs/users/metadata.mdx
- docs/users/web3.mdx
This PR removes `prettier: false` from some code blocks by first fixing errors, specifically:
- **Incorrect language.** For example some code blocks were set to `js(x)` but contain TS syntax so should be `ts(x)`
- **Syntax errors.** For example missing closing JSX tags
> Enable Prettier for code blocks with incorrect language or syntax errors

- docs/references/sdk/backend-only.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1394/references/sdk/backend-only
This PR will be merged into https://github.com/clerk/clerk-docs/pull/1344 and operates in the same context of "SDK Spec". Companion to https://github.com/clerk/clerk-docs/pull/1368
Fixes ECO-110
Fixes ECO-100
> SDK Spec: Backend-only

- docs/manifest.json
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1420
This PR fixes a minor issue with the manifest structure. The current version groups most items together and does not conform to the schema because a `title` property is missing from the object on line 312.
The side effects of the invalid manifest are subtle but it means that most item are grouped in the markup which is probably not what we want, and it also causes minor spacing issues.
In VS Code (and probably other editors) you should be able to see the error inline and in the "Problems" panel:
I may look into validating the manifest schema as part of the Lint GitHub action.
**Before**
```jsonc
{
"$schema": "./manifest.schema.json",
"navigation": [
[
// first group (with icons)
],
[
{
"items": [
// all other groups except …
```
> Fix manifest structure

- docs/references/nextjs/custom-signup-signin-pages.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1412
`clerkMiddleware()` does not make routes public, so if a customer is making most/all routes private they can mistakenly make the sign in and up routes private. Customers following this guide and then making all/most routes public run into private auth routes.
- Adds step to custom sign up pages and routes about adding routes to be ignored by middleware
> docs: add step to custom sign up pages and routes about adding routes to be ignored by middleware

- docs/customization/layout.mdx
> [!IMPORTANT]
> 🔎 Previews: 
Removes the duplicate `Defaults to true.` text.
> Remove duplicate text

- docs/organizations/overview.mdx
- docs/references/backend/types/backend-user.mdx
- docs/references/backend/user/update-user.mdx
- docs/references/javascript/user/user.mdx
> [!CAUTION]
> ❌ Blocked by:
> https://github.com/clerk/javascript/pull/3823
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1364
> - https://clerk.com/docs/pr/1364/organizations/overview
> - https://clerk.com/docs/pr/1364/references/backend/types/backend-user
> - https://clerk.com/docs/pr/1364/references/backend/user/update-user
> - https://clerk.com/docs/pr/1364/references/javascript/user/user
This PR adds descriptions and indicates the new section of the dashboard to manage create organization limits.
> ORGS-111: Add docs for the new `createOrganizationsLimit` field

- docs/upgrade-guides/core-2/nextjs.mdx
- docs/upgrade-guides/core-2/react.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1432/docs/upgrade-guides/core-2/nextjs
> - https://clerk.com/docs/pr/1432/docs/upgrade-guides/core-2/react
- Fixes syntax errors in higher order component code snippets
```diff
- return {children(session)};
+ return children(session)
```
- Enables Prettier for these snippets now that they are valid and can be formatted
> Fix syntax errors in higher order component code snippets

- docs/components/clerk-provider.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1410/components/clerk-provider
[User feedback ticket](https://linear.app/clerk/issue/DOCS-8960/componentsclerk-provider-add-info-about-dynamic-rendering) reads:
> The docs for this page are extremely lacking and don’t cover how it’s possible to still use ClerkProvider as a client component which doesn’t force dynamic rendering. Needs to be added and explained deeper.
- Updates the information to make usage of the provider clear; adds info on using it in client components
> (/clerk-provider) Update info about dynamic rendering

- docs/customization/organization-profile.mdx
- docs/customization/user-button.mdx
- docs/customization/user-profile.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1430/customization/user-profile
> - https://clerk.com/docs/pr/1430/customization/organization-profile
> - https://clerk.com/docs/pr/1430/customization/user-button
This PR stems from https://github.com/clerk/javascript/issues/3925 where it wasn't clear that one needs to add the 'use client' directive with these components.
> fix: Add callout for 'use client' directive

- .prettierrc
- docs/advanced-usage/using-proxies.mdx
- package-lock.json
- package.json
This PR adds `prettier-plugin-nginx` and `prettier-plugin-svelte` to enable formatting for `nginx` and `svelte` code blocks.
We don't currently have any Svelte code blocks but there [may](https://github.com/clerk/clerk-docs/pull/1434) be [some](https://github.com/clerk/clerk-docs/pull/1435) in the [future](https://github.com/clerk/clerk-docs/pull/1438).
We have one `nginx` block which has been formatted as part of this PR. The only change is that it has aligned the directives, which is a common thing to do in nginx config files. This can be disabled using the `alignDirectives` [configuration](https://github.com/jxddk/prettier-plugin-nginx?tab=readme-ov-file#configuration) if desired.
> Add `prettier-plugin-nginx` and `prettier-plugin-svelte`

- docs/users/metadata.mdx
This PR updates Ruby code snippets to use the correct syntax for single-line comments
> Fix Ruby comment syntax

- docs/deployments/set-up-staging.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1444/deployments/set-up-staging
The link to using subdomains for staging deployments was broken and edited to point to the correct page.
@alexisintech -- I noticed that the `staging-alternatives.mdx` page was not in the sidebar/manifest. I believe this was intentional since this is not a recommended solution but I wanted to mention it in case it should be added.
> fixing link to staging-alternatives in staging doc

- docs/references/astro/auth-store.mdx
- docs/references/astro/clerk-store.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1434/references/astro/auth-store
> - https://clerk.com/docs/pr/1434/references/astro/clerk-store
- As one of Astro's key features is its ability to seamlessly integrate components from various frameworks, this PR demonstrates the use of @clerk/astro's `$authStore` and `$clerkStore` with both Vue and Svelte components.
> docs(astro): Add multi-framework example for $authStore and $clerkStore

- docs/references/astro/session-list-store.mdx
- docs/references/astro/session-store.mdx
This is the last PR for multi-framework examples 🙇🏼 
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1443/references/astro/session-store
> - https://clerk.com/docs/pr/1443/references/astro/session-list-store
- Demonstrates the use of `@clerk/astro`'s `$sessionStore` and `$sessionListStore` stores in both Vue and Svelte components.
> docs(astro): Add multi-framework example for $session and $sessionListStore

- docs/references/astro/user-store.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1441/references/astro/user-store
- Demonstrates the use of `@clerk/astro`'s `$userStore` store in both Vue and Svelte components.
> docs(astro): Add multi-framework example for $userStore 

- docs/references/astro/sign-in-store.mdx
- docs/references/astro/sign-up-store.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1435/references/astro/sign-in-store
> - https://clerk.com/docs/pr/1435/references/astro/sign-up-store
- As one of Astro's key features is its ability to seamlessly integrate components from various frameworks, this PR demonstrates the use of @clerk/astro's `$signInStore` and `$signUpStore` with both Vue and Svelte components.
> docs(astro): Add multi-framework example for $signInStore and $signUpStore

- docs/references/astro/organization-store.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1438/references/astro/organization-store
- As one of Astro's key features is its ability to seamlessly integrate components from various frameworks, this PR demonstrates the use of @clerk/astro's `$organizationStore` with both Vue and Svelte components.
> docs(astro): Add multi-framework example for $organizationStore

- docs/components/authentication/google-one-tap.mdx
- docs/components/authentication/sign-in.mdx
- docs/custom-flows/overview.mdx
- docs/references/backend/types/paginated-resource-response.mdx
- docs/references/javascript/clerk/clerk.mdx
- docs/references/nextjs/get-auth.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1449/components/authentication/google-one-tap
> - https://clerk.com/docs/pr/1449/components/authentication/sign-in
> - https://clerk.com/docs/pr/1449/custom-flows/overview
> - https://clerk.com/docs/pr/1449/references/javascript/clerk/clerk
> - https://clerk.com/docs/pr/1449/references/nextjs/get-auth
> - https://clerk.com/docs/pr/1449/references/backend/types/paginated-resource-response
This PR replaces HTML tables with the `<Properties>` component, where I think it's appropriate. These tables were not caught by the initial codemod (#1341) for various reasons:
- "Description" is spelt incorrectly
- The table doesn't contain a "Type" column
- The table doesn't contain a "Description" column
> Replace tables with `<Properties>`

- docs/manifest.json
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1456
The sub-items don't need to be tagged with "Community" since they are nested under the "Community SDKs" item.
| - | - |
| ![CleanShot 2024-08-15 at 13 43 42@2x](https://github.com/user-attachments/assets/f7c25ee5-9e02-4dfe-97aa-c8cfeb8d8b2a) | ![CleanShot 2024-08-15 at 13 44 18@2x](https://github.com/user-attachments/assets/02d2cdc4-b37a-4e68-8b3c-255ebd47d20d) |
> Remove "Community" tag from nav items under "Community SDKs"

- docs/components/authentication/sign-in.mdx
- docs/references/javascript/clerk/handle-navigation.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1401/components/authentication/sign-in#properties
> - https://clerk.com/docs/pr/1401/references/javascript/clerk/handle-navigation#handle-o-auth-callback-params
Introduce docs for a recently added prop to `<SignIn />`: `transferable`. This was also added as a parameter to `Clerk.handleRedirectCallback()`, and the docs were updated accordingly.
> feat: Adds docs on the new tranferable prop

- docs/components/authentication/google-one-tap.mdx
- docs/components/authentication/sign-in.mdx
- docs/components/authentication/sign-up.mdx
- docs/components/user/user-button.mdx
- docs/components/user/user-profile.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1454/components/user/user-button#usage-with-frameworks
> - https://clerk.com/docs/pr/1454/components/user/user-profile#usage-with-frameworks
> - https://clerk.com/docs/pr/1454/components/authentication/sign-in#usage-with-frameworks
> - https://clerk.com/docs/pr/1454/components/authentication/sign-up#usage-with-frameworks
> - https://clerk.com/docs/pr/1454/components/authentication/google-one-tap#usage-with-frameworks
- Adds Astro authentication and user components examples to UI components section
> docs(astro): Add authentication and user components references

- docs/components/organization/create-organization.mdx
- docs/components/organization/organization-list.mdx
- docs/components/organization/organization-profile.mdx
- docs/components/organization/organization-switcher.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1453/components/organization/create-organization
> - https://clerk.com/docs/pr/1453/components/organization/organization-switcher
> - https://clerk.com/docs/pr/1453/components/organization/organization-profile
> - https://clerk.com/docs/pr/1453/components/organization/organization-list
- Adds Astro organization components examples to UI components section
> docs(astro): Add organization components references

- docs/authentication/social-connections/custom-provider.mdx
Getting ready for GA, this PR removes the warning that prompts users to contact support for access.
> Drop warning for custom OAuth providers

- docs/customization/account-portal/direct-links.mdx
- docs/deployments/clerk-environment-variables.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
Setting fallback redirects in the dashboard is going to be deprecated in a future version of Clerk.
- Updates the instructions for setting fallback redirects (using components or environment variables)
> Update instructions for handling Account Portal fallback redirects

- docs/references/sdk/backend-only.mdx
- docs/references/sdk/fullstack.mdx
- docs/references/sdk/types.mdx
Updates the SDK types table to correctly note handshake support only for fullstack SDKs. Previously it was marked for backend-only and fullstack.
> fix: Update handshake in SDK Development spec

- docs/references/expo/local-credentials.mdx
- docs/references/expo/use-local-credentials.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1446/references/expo/local-credentials
- We are updating the way we export this hook in [this PR](https://github.com/clerk/javascript/pull/3954)
> Update import path for `useLocalCredentials`

- docs/references/expo/use-local-credentials.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1476/references/expo/use-local-credentials
-
> Fix typo in biometricType value for Expo

- docs/references/expo/use-local-credentials.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1478/references/expo/use-local-credentials
I believe that `face-recognition` and `fingerprint` are meant to be string values.
> Fix `biometricType` type typo

- docs/references/react/use-sign-up.mdx
Fixed a typo in the `useSignUp` hook page
> Correct typo in use-sign-up.mdx

- docs/users/metadata.mdx
The function bodies use `await` but the `async` keyword is missing from the functions
> Add missing `async` keyword in user metadata examples

- docs/manifest.json
- docs/references/backend/user/delete-user-profile-image.mdx
- docs/references/javascript/user/user.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1473/references/backend/user/delete-user-profile-image
> - https://clerk.com/docs/pr/1473/references/javascript/user/user#set-profile-image-params
This PR adds `deleteUserProfileImage()` to Backend SDK references added https://github.com/clerk/javascript/pull/3991
-
> Add `deleteUserProfileImage` to Backend SDK reference

- docs/references/sdk/conventions.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1484/references/sdk/conventions#required
- Adds a warning to mention that `CLERK_SECRET_KEY` should not be exposed to the client-side.
> docs(sdk): Add a warning about avoiding exposing secret key to the frontend

- docs/quickstarts/expo.mdx
Slot exists in expo-router, not expo-navigation
> [!IMPORTANT]
> 🔎 Previews:
>
> -
-
> Update expo.mdx to correctly import Slot from expo-router

- docs/integrations/databases/hasura.mdx
Hasura changed their docs around. I believe this new URL is the correct page, but could use a double-check!
> Correct broken link to Hasura docs

- docs/deployments/migrate-from-cognito.mdx
- docs/integrations/databases/fauna.mdx
The rate limit for `createUser` is 20 requests per 10 seconds. The Cognito migration guide had a setTimeout of 200 milliseconds, allowing 50 requests per 10 seconds. I’ve adjusted the setTimeout to align with our rate limit.
> Update cognito migration guide

- docs/references/javascript/session.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1497/references/javascript/session#get-token-options
Adds docs for the new `organizationId` option that `Clerk.session.getToken()` now accepts. This allows session tokens to be created that are associated with a specific organization ID, which can be separate from the session's active organization.
-
> feat: Add new organizationId option to getToken()

- docs/quickstarts/expo.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1502/quickstarts/expo
[User feedback ticket](https://linear.app/clerk/issue/DOCS-9126/user-feedback-about-expo-quickstartcustom-flows) had a user confused about how to implement a passwordless custom flow for their Expo app. Our quickstart didn't mention how Expo native doesn't support UI components - and also doesn't link to our custom flows or really explain why custom flows are needed.
- Adds explanation as to why custom flows are needed for Expo (native doesn't support UI components)
- Adds sentence about seeing the dedicated custom flow guides for other auth methods
> Expo native requires custom flows over UI components

- docs/authentication/saml/azure.mdx
- docs/authentication/saml/okta.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
The ACS URL explanation was being switched with Entity ID, on both Google and Okta guides.
> Fixes ACS URL meaning on Azure and Okta guides

- docs/advanced-usage/using-proxies.mdx
- docs/authentication/configuration/session-options.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1423/advanced-usage/using-proxies#example-configuration
Adds an example of how to configure proxying with a pure nextjs app, using middleware.
> Add nextjs example to proxy config

- docs/advanced-usage/using-proxies.mdx
- docs/customization/localization.mdx
- docs/guides/force-organizations.mdx
- docs/references/astro/migrating-from-astro-community-sdk.mdx
- docs/references/backend/email-addresses/update-email-address.mdx
- docs/references/backend/phone-numbers/update-phone-number.mdx
- docs/references/backend/saml-connections/update-saml-connection.mdx
- docs/references/javascript/clerk/organization-methods.mdx
- docs/references/javascript/types/clerk-api-error.mdx
- docs/references/nextjs/auth-object.mdx
- docs/security/clerk-csp.mdx
- docs/upgrade-guides/core-2/chrome-extension.mdx
- docs/upgrade-guides/core-2/expo.mdx
- docs/upgrade-guides/core-2/javascript.mdx
- docs/upgrade-guides/core-2/nextjs.mdx
- docs/upgrade-guides/core-2/node.mdx
- docs/upgrade-guides/core-2/react.mdx
- docs/upgrade-guides/core-2/remix.mdx
Apply minor formatting fixes:
- Remove `prettier: false` from code blocks that can be formatted
- Update code block language where appropriate
- For code blocks that cannot be formatted, tweak code to match code style, e.g.
- Fix indentation and excess whitespace
- Use single quotes (double quotes for JSX props)
- Add trailing commas
> Minor code block formatting fixes

- docs/custom-flows/saml-connections.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1514
We are mentioning "OAuth" in a couple of places and code snippets from the custom SAML connections docs. I believe it was previously copied from the custom OAuth connections docs.
I've removed those references to use SAML nomenclature.
> Remove OAuth references from custom SAML connection docs

- docs/quickstarts/astro.mdx
- docs/quickstarts/expo.mdx
- docs/quickstarts/javascript.mdx
- docs/quickstarts/nextjs.mdx
- docs/quickstarts/react.mdx
- docs/quickstarts/remix.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
We don't currently explicitly tell users to sign up on their localhost, which creates a gap in metrics between users who run locally, and create their first user (which is what we consider to be an `install` event)
- Adds explicit instructions as the last step of our quickstarts - the goal here is to make it clear that they should sign up to create their first user.
[Companion PR](https://github.com/clerk/dashboard/pull/3571) making the same updates for Dashboard
> add instructions to sign up on localhost

- docs/references/javascript/user/user.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1526
- Fixes spelling from `ap` to `app`
-
> [fix] change spelling from ap to app

- docs/guides/overview.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
-
> Remove typo in guides overview

- docs/customization/variables.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1536
- changes the appearance prop color from red to purple so the code example matches Clerk's colors
> docs-9205:  change appearance prop color from red to purple

- docs/quickstarts/nextjs.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
[User feedback ticket](https://linear.app/clerk/issue/DOCS-9078/mention-use-of-account-portal-in-quickstartsnextjs) reads:
> Wondering about the hosted experiences (sign up, sign in etc?) and how that may be used - or even where to find that info within these docs.
- Adds information about the SignInButton component linking to the Account Portal, and adds a reference link to the AP
- Updates Dashboard navigation instructions
- Updates "Create your first user" instructions to include instructions on running the project
> (/quickstarts/nextjs) Mention use of Account Portal

- docs/deployments/set-up-staging.mdx
- docs/deployments/staging-alternatives.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
Clerk now supports multiple applications being hosted on the same domain. Users no longer need to purchase a separate domain to set up a "staging" application - they can use subdomains.
Relevant ticket: https://linear.app/clerk/issue/DOCS-9206/update-staging-environment-docs
-
> Update Staging guides: support subdomains over buying separate domains

- docs/customization/account-portal/getting-started.mdx
- docs/customization/account-portal/overview.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
[User feedback ticket](https://linear.app/clerk/issue/DOCS-9073/update-intro-paragraph-for-customizationaccount-portalgetting-started) reads:
> It doesn't tell me how to add a custom domain name for the Account Portal pages. Also, how can I integrate Account Portal into my application? I want Clerk to manage sign in, sign up, account management, etc and just give my app the token when user is logs in.
- Adds emphasis on the sentence about integrating the AP into an app (pointing the user to the setup guide)
- Adds further explanation on how to integrate AP
> Clarify how to integrate Account Portal into an app

- docs/quickstarts/nextjs.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1547/quickstarts/nextjs
Following https://github.com/clerk/clerk/pull/674 you can pass the `track` prop to any MDX link to fire a Segment event on click.
This PR adds an event to the "Clerk Dashboard" link in the Next.js Quickstart, to assist with the [upcoming experiment](https://github.com/clerk/clerk-docs/pull/1499)
> Add `track` prop to dashboard link in Next.js Quickstart

- docs/references/nextjs/clerk-middleware.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1508
Resolves DOCS-9092
> User's feedback: I don't understand the dynamic keys section. The changelog post says: "Users building a multi-tenant application might need to provide different Clerk keys depending on the incoming request.".
Adds example on the Next.js dynamic keys section regarding how to make keys conditional per tenant on request time.
> Add example on defining Clerk keys per tenant from `clerkMiddleware`

- docs/users/deleting-users.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1548/users/deleting-users
User feedback ticket reads:
> Your documents show code that your logging says is deprecated.
- The deprecation was "clerkClient singleton was deprecated". This PR updates the Nextjs to call clerkClient as a function
> Update code example for deleting a user

- docs/integrations/databases/neon.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - 
Fixes misspelled user ID from `user.id` to `userId` on step 7, and adds `await` to the messages fetch on step 8
- Fixes the misspelled and missing code to make the guide work out of the box
> fix: Step 7 & 8 of Neon integration guide

- docs/components/clerk-provider.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1553/components/clerk-provider#properties
Fixes ECO-198
> feat: Improve ClerkProvider docs

- docs/organizations/overview.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1550/organizations/overview#create-an-organization
[Linear ticket](https://linear.app/clerk/issue/DOCS-9108/add-a-callout-that-orgs-that-have-no-members-will-be-automatically) reads:
> When assisting a user, I learned that Clerk automatically deletes orgs that have no members in them. This can be alarming to a user who may be creating orgs without members for a certain use-case. To minimize confusion, we would like to add a callout / warning in the docs so users can be aware of this, and also so support has somewhere in the docs to point to if users do write in about this behavior. I'm not entirely sure where this should live so I wanted to make a linear tix for this
In the Slack thread linked in the Linear ticket, Mary …
> Add callout about Clerk auto-deleting empty organizations

- docs/references/backend/user/create-user.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1551/references/backend/user/create-user
>
> 👀 RELATED TO:
> - https://github.com/clerk/clerk_go/pull/7703
[Linear ticket](https://linear.app/clerk/issue/DOCS-9021/move-the-password-hasher-reference-into-a-docs-page) reads:
> https://clerk.com/docs/reference/backend-api/tag/Users#operation/CreateUser - we probably shouldn't have this whole thing in the openapi spec and instead should link to the docs
- Moves the info to Clerk docs, reorganizes the info, removes hashers we no longer support
> Move password hasher info from BAPI docs to Clerk docs

- docs/quickstarts/astro.mdx
- docs/quickstarts/expo.mdx
- docs/quickstarts/javascript.mdx
- docs/quickstarts/react.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
In the last step of many of our quickstarts, we ask users to create their first user locally, but we don't include instructions to run their local dev server.
This adds local dev run instructions (e.g. `npm run dev`) to the final step. 
> ⚠️ I checked docs for these frameworks to ensure it has the right commands, but I'd really appreciate a second check here as I'm not deeply familiar with many of them. 
Companion PR for Dashboard quickstarts is: https://github.com/clerk/dashboard/pull/3656
> add run instructions to quickstarts

- docs/references/javascript/session-with-activities.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1543/references/javascript/session-with-activities
[User feedback ticket](https://linear.app/clerk/issue/DOCS-9161/add-info-about-how-to-get-this-object-referencesjavascriptsession-with) reads:
> I'd love to know how to get that object...
- Adds info about how to access the object
> Add info about how to access SessionWithActivities object

- docs/customization/user-button.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1519/customization/user-button
This PR provides examples of custom menu items for the `<UserButton />` component in Astro and highlights how [slots](https://docs.astro.build/en/basics/astro-components/#slots) are used to render child elements (label icons).
Related PR: https://github.com/clerk/javascript/pull/3969
> docs(astro): Add custom menu items examples for Astro

- docs/components/unstyled/sign-in-button.mdx
- docs/components/unstyled/sign-out-button.mdx
- docs/components/unstyled/sign-up-button.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1556/components/unstyled/sign-in-button#custom-usage
> - https://clerk.com/docs/pr/1556/components/unstyled/sign-up-button#custom-usage
> - https://clerk.com/docs/pr/1556/components/unstyled/sign-out-button#custom-usage
We added support for custom elements/components inside our unstyled components in Astro, similar to the [React counterpart](https://clerk.com/docs/components/unstyled/sign-in-button#custom-usage). Here's the [PR](https://github.com/clerk/javascript/pull/4122) for that change.
> docs(astro): Update unstyled components custom usage

- docs/references/backend/organization/update-organization-logo.mdx
- docs/references/backend/user/update-user-profile-image.mdx
This PR updates the examples for our APIs that deal with file uploads - uploading user profile pictures and organization logos - clarifying which string is placeholder text and must be replaced with actual file contents.
In testing my [recent change to these APIs](https://github.com/clerk/javascript/pull/4236), I tried running the example verbatim, and was surprised to get this error:
```
_ClerkAPIResponseError: Bad Request
at OrganizationAPI.request (/Users/izaak/dev/clerk_docker/javascript/packages/backend/dist/index.js:1543:21)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async /Users/izaak/dev/nodejs-playground/main.js:31:20 {
toString: [Function (anonymous)],
status: 400,
clerkTraceId: 'c49860b6376ec75ad288ba9893540a17',
clerkError: true,
errors: [ …
```
> Clarifying which string is a placeholder in our file upload examples

- docs/references/backend/organization/update-organization-logo.mdx
Companion to https://github.com/clerk/javascript/pull/4236
> Documenting that `uploaderUserId` is optional when uploading organization logo

- docs/testing/playwright.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1529/testing/playwright
- Adds documentation for helper functions in the Playwright integration of the `@clerk/testing` package.
> Add documentation for Playwright helpers

- docs/quickstarts/express.mdx
- docs/references/express/overview.mdx
- docs/upgrade-guides/node-to-express.mdx
Follow up review to https://github.com/clerk/clerk-docs/pull/1201
> Express SDK docs followup review

- docs/references/javascript/sign-in/sign-in.mdx
- docs/references/javascript/sign-up/sign-up.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
[User feedback ticket](https://linear.app/clerk/issue/DOCS-9279/add-example-section-to-referencesjavascriptsign-upsign-up) reads:
> Needs example use cases
- Adds example sections to the appropriate pages
> add example sections to /sign-up/sign-up and /sign-in/sign-in

- docs/manifest.json
- docs/organizations/creator-role.mdx
- docs/organizations/default-role.mdx
- docs/organizations/roles-permissions.mdx
- docs/organizations/verified-domains.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1584/organizations/roles-permissions#the-default-role-for-members
> - https://clerk.com/docs/pr/1584/organizations/verified-domains
> - https://clerk.com/docs/pr/1584/organizations/default-role
We introduced a new "default role for members" setting to the organization settings page.
This PR updates the appropriate docs to do the following:
- introduce the new top-level default role setting
- remove references to the old verified domains specific default role setting
> Add new default role setting docs

- docs/quickstarts/express.mdx
- docs/upgrade-guides/node-to-express.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1595/quickstarts/express#protect-your-routes-using-require-auth
> - https://clerk.com/docs/pr/1595/upgrade-guides/node-to-express
The `getAuth()` helper is basically an unnecessary abstraction, which just calls `req.auth` under the hood and throws an error if the middleware is not installed.
This PR de-emphasizes the use of `getAuth()` and promote direct access to `req.auth` to access authenticate state. We're still keeping it to support the [Backend SDK](https://clerk.com/docs/references/sdk/backend-only#create-a-require-auth-helper) spec.
> docs(express): Start de-emphasizing usage of `getAuth`

- docs/organizations/roles-permissions.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1594
Resolves ORGS-229
System permissions aren't included in the user session claims, therefore cannot be used on the server-side with helpers such as `auth.has`
We should educate others to rely on their custom permissions instead of checking for system ones.
> Clarify usage of system permissions on the server-side

- docs/deployments/overview.mdx
Corrects `dashboard.clerk.dev/*` links to `dashboard.clerk.com/*` on https://clerk.com/docs/deployments/overview
> `.dev` → `.com`

- docs/customization/account-portal/overview.mdx
- docs/customization/localization.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1609
There's no mention on the localisations guide page that the usage guide will only affect components that are used in the application, versus when developers are still using the hosted sign in and sign up pages, etc.
- Adds information about customisation limitations in the Account Portal and Localisation guides
- Fixes [DOCS-9359](https://linear.app/clerk/issue/DOCS-9359/clarify-localization-guide-on-usage-affecting-only-ui-components)
> chore(docs): Add information about customization limitations in Account Portal and Localization guides

- docs/advanced-usage/using-proxies.mdx
- docs/components/authentication/google-one-tap.mdx
- docs/components/authentication/sign-in.mdx
- docs/components/authentication/sign-up.mdx
- docs/components/organization/create-organization.mdx
- docs/components/organization/organization-list.mdx
- docs/components/organization/organization-profile.mdx
- docs/components/organization/organization-switcher.mdx
- docs/components/user/user-button.mdx
- docs/components/user/user-profile.mdx
- docs/custom-flows/email-sms-otp.mdx
- docs/custom-flows/error-handling.mdx
- docs/custom-flows/invitations.mdx
- docs/customization/organization-profile.mdx
- docs/customization/user-profile.mdx
- docs/quickstarts/javascript.mdx
- docs/references/javascript/clerk/organization-methods.mdx
- docs/references/javascript/organization-invitation.mdx
- docs/references/javascript/organization/domains.mdx
- docs/references/javascript/organization/invitations.mdx
- docs/references/javascript/organization/members.mdx
- docs/references/javascript/organization/membership-request.mdx
- docs/references/javascript/organization/organization.mdx
- docs/references/javascript/session.mdx
- docs/references/javascript/user/create-metadata.mdx
- docs/references/javascript/user/password-management.mdx
- docs/references/javascript/user/totp.mdx
- docs/references/javascript/user/user.mdx
- docs/users/metadata.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
Many examples in the JS docs say something like:
```
For the following example, your HTML file should look like this:
<code example>
And your JavaScript file should look like this:
<code example>
```
Instead, we can simply write:
```
Use the following tabs to view the code necessary for each file.
<CodeBlockTabs options={["index.html", "main.js"]}>
```
> chore: combine 'index.html' and 'main.js' using <CodeBlockTabs />

- docs/authentication/social-connections/atlassian.mdx
- docs/authentication/social-connections/bitbucket.mdx
- docs/authentication/social-connections/box.mdx
- docs/authentication/social-connections/coinbase.mdx
- docs/authentication/social-connections/discord.mdx
- docs/authentication/social-connections/dropbox.mdx
- docs/authentication/social-connections/facebook.mdx
- docs/authentication/social-connections/github.mdx
- docs/authentication/social-connections/gitlab.mdx
- docs/authentication/social-connections/google.mdx
- docs/authentication/social-connections/hubspot.mdx
- docs/authentication/social-connections/huggingface.mdx
- docs/authentication/social-connections/line.mdx
- docs/authentication/social-connections/linear.mdx
- docs/authentication/social-connections/linkedin-oidc.mdx
- docs/authentication/social-connections/linkedin.mdx
- docs/authentication/social-connections/microsoft.mdx
- docs/authentication/social-connections/notion.mdx
- docs/authentication/social-connections/slack.mdx
- docs/authentication/social-connections/spotify.mdx
- docs/authentication/social-connections/tiktok.mdx
- docs/authentication/social-connections/twitch.mdx
- docs/authentication/social-connections/twitter.mdx
- docs/authentication/social-connections/x-twitter.mdx
- docs/authentication/social-connections/xero.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1632
- changes terms
- related: https://github.com/clerk/dashboard/pull/3885
> chore: authorized redirect URI > redirect URI

- docs/integrations/webhooks/inngest.mdx
Linking directly to the apex domain for `inngest.com` errors out 🙈  Needs `www.` subdomain to resolve correctly (like the rest of the links in the doc).
> `inngest.com` domain requires `www.`

- docs/advanced-usage/satellite-domains.mdx
- docs/authentication/social-connections/linear.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1643
Users are only made aware of the requirement for sign-in flow to be completed on the primary domain, but not until later on in the implementation step is the sign-up flow requirement mentioned.
- Clarifies that users must complete both the sign-in and sign-up flows on the primary domain using Clerk's <SignIn /> component or useSignIn() hook for sign-in and <SignUp /> component or useSignUp() hook for sign-up. It also explains the redirection process for accessing authentication state from a satellite domain, including sign-in and sign-up flows.
- Fixes [DOCS-9422](https://linear.app/clerk/issue/DOCS-9422/feedback-for-satellite-domains-docs)
> fix(docs): Update satellite domains documentation

- docs/upgrade-guides/nextjs/v6.mdx
> [!IMPORTANT]
> 🔎 Previews:
> * https://clerk.com/docs/upgrade-guides/nextjs/v6
- Fixes a relative url at the bottom of "Upgrade to @clerk/nextjs v6" page
> Remove localhost from a link in v6.mdx

- docs/authentication/configuration/restrictions.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1645
We're changing how the block email subaddress restriction works. 
`nicolas+finance@gmail.com` would be blocked, as the e-mail contains a `+`
🧑‍🦱 A legit user trying to be organized with their mailbox:
- I want to sign up for a new bank that uses Clerk.
- I sign up with an email containing a subaddress: `nicolas+finance@clerk.dev`.
- ✅ Sign-up should be successful.
🎩 An attacker trying to abuse subaddressing:
- They sign up with the first account: `imahacker+1@gmail.com`.
- ✅ Sign-up is successful.
- Now they try to sign up again with `imahacker+2@gmail.com`.
- ❌ The attempt fails because the same canonical identifier already exists.
> (authentication/configuration/restrictions): update block email subaddress behavior

- docs/security/fixation-protection.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1640/security/fixation-protection
The link had the wrong text - it mentioned CSRF protection but this page is about session fixation. This PR fixes the text and updates the copy for this page overall.
> Update Session Fixation doc

- docs/backend-requests/handling/nodejs.mdx
- docs/references/express/overview.mdx
- docs/references/nodejs/available-methods.mdx
- docs/references/nodejs/overview.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1652/references/nodejs/overview
We started the transition period to deprecate `@clerk/clerk-sdk-node`. We need to display some callout when visiting the overview page.
- Adds a callout to Node SDK pages that guides users to the Node-->Express upgrade guide
- Adds a callout to Express SDK overview that mentions the Node-->Express upgrade guide
> Add deprecation notice to Node SDK

- docs/organizations/verify-user-permissions.mdx
- docs/references/nextjs/auth.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1651/references/nextjs/auth
> - https://clerk.com/docs/pr/1651/organizations/verify-user-permissions
Next.js warns users against performing authorization checks in layouts. More info [here](https://nextjs.org/docs/app/building-your-application/authentication#layouts-and-auth-checks).
This PR
- adds a warning callout to examples that perform authz checks in layouts
- updates authz examples to have better explanations and more code comments
- updates broken examples (all examples in both of these docs were tested)
> Update authorization examples

- docs/customization/user-button.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1650/customization/user-button
-
> Add JavaScript example for custom menu items in <UserButton />

- docs/integrations/databases/convex.mdx
> [!IMPORTANT]
> 🔎 Previews:
https://clerk.com/docs/pr/1673/integrations/databases/convex#integrate-convex-with-clerk
>
> -
After speaking with the convex team, they pointed out an error in our docs regarding the callout of OpenId claims. Convex now accepts custom claims. 
I am updating the doc to have this callout mimic what's mentioned in the convex docs.
-
> updating Convex integration docs to mention acceptance of custom claims

- .github/workflows/redeploy.yml
This PR updates the `redeploy` workflow now that the Algolia search index has been updated (see https://github.com/clerk/clerk/pull/662)
- The `Trigger search reindex` step is no longer needed as reindexing is handled by webhooks instead
- The website deploy hook used is now different depending on whether the push was to `main` or `core-1`. This ensures that the correct pages are crawled by Algolia
> [!IMPORTANT]
> - The `WEBSITE_DEPLOY_HOOK_CORE_1` secret must be added in the repository settings before merging this PR
> - The `SEARCH_INDEX_DEPLOY_HOOK` secret can be deleted once this PR has been merged
> Update redeploy workflow

- docs/references/backend/testing-tokens/create-testing-token.mdx
- docs/testing/overview.mdx
Previously, testing tokens were only available for dev instances.
This commit updates the necessary docs to reflect that, testing tokens are available for production instances as well.
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1678/testing/overview#testing-tokens
> - https://clerk.com/docs/pr/1678/references/backend/testing-tokens/create-testing-token#create-testing-token
-
> chore: Testing tokens are now enabled in production instances as well

- docs/components/clerk-provider.mdx
- docs/security/clerk-csp.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1685/security/clerk-csp#implementing-a-strict-dynamic-csp
> - https://clerk.com/docs/pr/1685/components/clerk-provider#properties
With the recent changes to ClerkProvider that cause it to static render by default, in order to pass `nonce` as a prop, which is pulled from headers, it requires server rendering, which means that `dynamic` must also be present. This is now documented in ClerkProvider's props as well as the CSP guide in the strict-dynamic section.
> Add a note that `dynamic` is required for the `nonce` prop

- CONTRIBUTING.md
This PR adds information about the new [`search` frontmatter field](https://github.com/clerk/clerk/pull/729) to the contributing documentation.
---
✨ [Preview →](https://github.com/clerk/clerk-docs/blob/bradlc/search/CONTRIBUTING.md#search)
> Add "Search" section to contributing docs

- docs/components/unstyled/sign-in-button.mdx
- docs/components/unstyled/sign-up-button.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1707/components/unstyled/sign-up-button
> - https://clerk.com/docs/pr/1707/components/unstyled/sign-in-button
Hold until https://github.com/clerk/javascript/pull/4567 is merged
-
> Add `initialValues` property to `<SignUpButton />` and `<SignInButton />`

- docs/authentication/configuration/restrictions.mdx
> Correct auth restrictions link

- docs/upgrade-guides/node-to-express.mdx
Old code using only req.auth would always evaluate to true, rendering the middleware useless, and potentially leading to users having insecure routes.
> [!IMPORTANT]
> 🔎 Previews:
>
> -
- The docs currently have code that may misguide users. req.auth always evaluates to true making the legacyRequireAuth function incorrect.
- Modifies the current legacyRequireAuth function to use req.auth.userId instead of req.auth to check if a user is authenticated.
> docs(express): Fix Express legacyRequireAuth example

- docs/index.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1732#explore-by-frontend-framework
- Our docs currently reference Create React App (CRA), which is no longer the recommended way to start React projects
- We use Vite throughout our documentation for React examples
- Updates the "Create React App" with Vite
> docs(react): Replace CRA with Vite

- docs/components/authentication/sign-up.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1742
- 
- `unsafeMetadata` prop is missing from `<SignUp />` component definition doc
- 
- Adds missing prop `unsafeMetadata` to `<SignUp />` component properties description
> docs: Add unsafeMetadata prop to SignUp component documentation

- docs/references/nextjs/custom-signup-signin-pages.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1739/references/nextjs/custom-signup-signin-pages
Updating the copy to align with the voice of the Docs, and align with the other custom signup/signin guides.
> (/nextjs/custom-signup-signin-pages) Update guide

- docs/components/control/signed-in.mdx
- docs/components/control/signed-out.mdx
- docs/references/react/add-react-router.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
- React Router released a new major version (v7) and things have changes quite a bit!
- So much that we'll release a new SDK for it (WIP PR: https://github.com/clerk/javascript/pull/4621) but in the interim we can update individual snippets and add a notice
> fix: Update React Router mentions

- docs/organizations/organization-workspaces.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1753/organizations/organization-workspaces
- The link on this page was pointing to clerk.com/dashboard instead of dashboard.clerk.com. 
- Rectifies the mistake.
> (/organization-workspace) Fix broken link; update Dashboard navigation instructions

- docs/errors/sign-up.mdx
Captcha is now enabled for all instance types (development and production). The error message has been updated to reflect that.
- Updates the `captcha_not_enabled` error message
> chore: update captcha not enabled error message

- docs/users/metadata.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1775/users/metadata#public-metadata
- The example for setting public metadata for Next was referencing private metadata.
- Updates the parameter to `publicMetdata`
> Fix reference in user metadata page

- docs/backend-requests/resources/session-tokens.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> https://clerk.com/docs/pr/1776/backend-requests/resources/session-tokens#size-limitations
Adding a small acknowledgement of the warning in the Dashboard that will link to this section, with directions on how to clear/fix the warning.
> Adds a reference to the cookie overflow warning in the dashboard

- docs/references/chrome-extension/sync-host.mdx
The docs reference the Secret Key but then use the prefix for publishable key, fixed the prefix to sk
> Quick Typo Fix

- docs/authentication/enterprise-connections/easie/microsoft.mdx
Microsoft's optional `xms_edov` claim should not longer be in preview.
Update Microsoft OAuth docs to remove the updated note, as well as link to documentation about optional claims.
> fix: Remove snipped about xms_edov being in preview

- docs/backend-requests/making/custom-session-token.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1787/backend-requests/making/custom-session-token
Upstream at https://clerk.com/docs/backend-requests/making/custom-session-token, there's a mismatched use of `fullName` and `firstName` in the docs on how to set up custom claims on a session token:
This issue might be confusing to users, and makes it more difficult to confirm that types are working as expected.
This PR resolves the issue by updating text to match existing screenshots, using `fullName` consistently rather than `firstName`.
> fix: typo in custom-session-token docs

- docs/references/astro/overview.mdx
- docs/references/chrome-extension/overview.mdx
- docs/references/expo/overview.mdx
- docs/references/javascript/overview.mdx
- docs/references/nextjs/overview.mdx
- docs/references/redwood/overview.mdx
- docs/references/tanstack-start/overview.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -  https://clerk.com/docs/pr/1789
- 
- 
- Updating copy to align with upcoming React Router reference PR
> chore: update page titles to "Clerk _Name_ SDK" for sdk reference overviews

- docs/components/clerk-provider.mdx
- docs/references/javascript/clerk/clerk.mdx
- docs/references/remix/clerk-app.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1767/components/clerk-provider#properties
> - https://clerk.com/docs/pr/1767/references/javascript/clerk/clerk#load
> - https://clerk.com/docs/pr/1767/references/remix/clerk-app#properties
- Documents a new Clerk option, `allowedRedirectProtocols`, which lets users provide custom protocols to allow in their redirect URLs. Useful for deep linking scenarios where a custom protocol is used.
- https://linear.app/clerk/issue/SDKI-782/introduce-new-allowedredirectprotocols-clerk-option
- 
- Documents the new property!
> feat: Add allowedRedirectProtocols documentation

- docs/backend-requests/making/jwt-templates.mdx
- docs/backend-requests/resources/session-tokens.mdx
The JWTs generated from JWT Templates actually never get stored in a cookie, and are not beholden to the 4kb limit.
> [!IMPORTANT]
> 🔎 Previews:
>
> - Primary Change: https://clerk.com/docs/pr/1790/backend-requests/resources/session-tokens#size-limitations
> - Removing callout: https://clerk.com/docs/pr/1790/backend-requests/making/jwt-templates
The 4kb size limitations only apply to custom Session tokens, as they are stored in cookies.  JWTs that are generated from JWT Templates never are stored in cookies, and are not beholden to the same size limits.  We've updated our Dashboard warnings to reflect this as well.
- Updates the docs about our size limitations to no longer reference JWT Templates
- Removes the callout warning about the size limitations on the JWT Templates page
> Update size limitation docs to reference only session tokens

- docs/authentication/configuration/sign-up-sign-in-options.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1793/authentication/configuration/sign-up-sign-in-options
- The docs currently make it sound like an email address is required at all times, when in reality it's only required if email address is the only enabled identifier.
- Clarifies that users must keep an email address on their account at all times only when email address is the only enabled identifier.
- Removes the verification requirement since that's dependent on instance settings
> fix: clarify email address sign up requirements

- CONTRIBUTING.md
- docs/advanced-usage/satellite-domains.mdx
- docs/guides/architecture-scenarios.mdx
- docs/guides/authjs-migration.mdx
- docs/quickstarts/chrome-extension.mdx
- docs/quickstarts/expo.mdx
- docs/quickstarts/nextjs.mdx
- docs/quickstarts/react.mdx
- docs/quickstarts/tanstack-start.mdx
- docs/telemetry.mdx
- styleguides/STYLEGUIDE.md
Some components, like `<ClerkProvider>` are not self-closing and should not be referenced as such.
> (chore) fix format for component references

- docs/authentication/enterprise-connections/overview.mdx
also fixes DOCS-9596
More context:
> (enterprise-connections/overview) remove info about pricing

- docs/index.mdx
- docs/manifest.json
- docs/quickstarts/overview.mdx
- docs/quickstarts/vue.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1709/quickstarts/vue
> - https://clerk.com/docs/pr/1709/quickstarts/overview#frontend
- We are launching an official Vue SDK for Clerk! 🎉
- This SDK is coming from the community SDK I help maintain - https://www.vue-clerk.com/
- The [Vue SDK PR](https://github.com/clerk/javascript/pull/4461) has been merged, and `0.0.1` version released
- Adds the initial Vue SDK quickstart guide (quickstart repo [here](https://github.com/clerk/clerk-vue-quickstart), 1:1 with the guide)
> feat(vue): Introduce Vue SDK Quickstart

- docs/quickstarts/astro.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1808/quickstarts/astro
- We released [`@clerk/astro` v2](https://github.com/clerk/javascript/pull/4721), which comes with automatic generation of context local types
- Removes the [Add TypeScript declarations](https://clerk.com/docs/quickstarts/astro#add-type-script-declarations) step since our Astro integration now handles this automatically
> docs(astro): Remove typescript declaration step

- docs/references/vue/use-organization.mdx
- docs/references/vue/use-session-list.mdx
- docs/references/vue/use-session.mdx
- docs/references/vue/use-sign-up.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1712/references/vue/use-sign-up
> - https://clerk.com/docs/pr/1712/references/vue/use-session
> - https://clerk.com/docs/pr/1712/references/vue/use-session-list
> - https://clerk.com/docs/pr/1712/references/vue/use-organization
- We are launching an official Vue SDK for Clerk! 🎉
- We need to showcase how to use built-in composables (or what they call hooks in React)
- You will notice that all of the pages mirror the React client-side helpers. I thought of just adding a message somewhere saying that the Vue SDK provides equivalent functionality through composables, but created dedicated Vue pages since not all Vue developers use React.
- Adds client helpers (`useSignUp()`, `useSession()`, `useSessionList()`, `useOrganization()`) …
> feat(vue): Add client helpers (part 2)

- docs/authentication/enterprise-connections/oidc/custom-provider.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1820/authentication/enterprise-connections/oidc/custom-provider#set-up-an-enterprise-connection-in-clerk
Small change to align the docs with the update dashboard label
> fix: Update create enterprise OIDC label

- docs/references/backend/organization/create-organization-invitation.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
This allows the inviterUserId to be nullable on the SDK, since it's nullable on the [BAPI](https://clerk.com/docs/reference/backend-api/tag/Organization-Invitations#operation/CreateOrganizationInvitation)
Update the types allowed
> Organization inviterUserId as nullable

- docs/manifest.json
> [!IMPORTANT]
> 🔎 Previews:
>
> -
- The [Astro community SDK](https://github.com/panteliselef/astro-with-clerk-auth) has graduated into an official SDK and is deprecated.
- Removes the Astro from the Community SDKs list.
> chore: Remove Astro from Community SDKs list

- docs/backend-requests/making/custom-session-token.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1827/backend-requests/making/custom-session-token#use-the-custom-claims-in-your-application
[User feedback reads:](https://linear.app/clerk/issue/DOCS-9693/add-more-examples-for-backend-requestsmakingcustom-session-token)
> WHy does this only apply to next js?
> (custom-session-token) add usage info for non-nextjs frameworks

- docs/references/backend/types/backend-user.mdx
- docs/references/backend/user/create-user.mdx
- docs/references/backend/user/get-user-list.mdx
- docs/references/backend/user/get-user.mdx
- docs/references/backend/user/update-user.mdx
- docs/references/javascript/user/user.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1828/references/backend/user/get-user-list#examples
> - https://clerk.com/docs/pr/1828/references/backend/user/get-user#example
> - https://clerk.com/docs/pr/1828/references/backend/user/create-user#create-user-params
> - https://clerk.com/docs/pr/1828/references/backend/user/update-user#update-user-params
> - https://clerk.com/docs/pr/1828/references/backend/types/backend-user#properties
Updates the user object to include `legalAcceptedAt` and `skipLegalChecks` in the backend sdk to reflect the backend api.
> Add legalAcceptedAt and skipLegalChecks fields to user management methods

- docs/quickstarts/chrome-extension.mdx
- docs/quickstarts/expo.mdx
- docs/quickstarts/ios.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1826/quickstarts/expo
> - https://clerk.com/docs/pr/1826/quickstarts/chrome-extension
> - https://clerk.com/docs/pr/1826/quickstarts/ios
- We've recently changed the product so that Bot Protection is enabled instances by default. Some customers using SDKs like Expo or Chrome Extension are running into issues with captcha/bot protection related issues.
> Add disable bot protection step to native sdk quickstarts

- docs/how-clerk-works/overview.mdx
Minor fix. "An" is generally used before words that start with vowel sounds.
> fix: phonetic article agreement "an much" => "a much"

- .github/CODEOWNERS
The intention behind setting the Growth team as codeowners on `/quickstarts/*` was to try to ensure we keep the Dashboard quickstart content in sync with the docs quickstarts, but this approach is just causing a lot of approval noise and delaying shipping in some cases, so this PR removes `@clerk/growth` as a codeowner.
> [codeowners] remove Growth team from quickstarts

- docs/quickstarts/react-router.mdx
- docs/references/react-router/overview.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1866/quickstarts/react-router
> - https://clerk.com/docs/pr/1866/references/react-router/overview
- Adding node version requirement warning to React Router docs due to current upstream issue. See https://github.com/clerk/javascript/issues/4826#issuecomment-2573054703
- Adds warning callout to React Router quickstart and overview pages informing users to use Node.js 22.11 or lower
> Add React Router 7 compatilibty issue callout

- docs/manifest.json
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1856
- We now have an official Vue SDK!
- Removes Vue from community SDKs list
> Remove Vue from community SDKs list

- docs/index.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1868
The "SDKs" card was in the wrong place.
Current:
Fixed:
-
> fix: Move "SDKs" card on index page to correct place

- docs/how-clerk-works/overview.mdx
- docs/how-clerk-works/tokens-signatures.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1811/how-clerk-works/overview
- Fixes explanation for comprehension check "Why doesn't Clerk set a **session token** using the `Set-Cookie` header when its setting the **client token**?"
> Update How Clerk works

- docs/quickstarts/react-router.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1874/quickstarts/react-router
I don't know if we accidentally removed it or never added it in the first place, but compared to all other quickstarts the React Router one is missing the "Next steps" heading to link to the reference docs.
Since we have a callout for inside the library guide about the framework guide, I'm adding that backlink also to the quickstart so it's easier to discover.
> fix: Add "Next steps" to React Router quickstart

- docs/references/react/use-auth.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1882/references/react/use-auth
- Fix formatting of `useAuth()` options
- 
Before: 
After:
> fix(useAuth): Fix options formatting

- docs/authentication/social-connections/atlassian.mdx
- docs/authentication/social-connections/coinbase.mdx
- docs/authentication/social-connections/github.mdx
- docs/authentication/social-connections/notion.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
- 
-
> fix: sso guides

- docs/quickstarts/expo.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1884/quickstarts/expo
This PR updates the Expo quickstart so that the repo link uses the GitHub icon instead of the Clerk icon, for consistency with other quickstarts.
| - | - |
| ![CleanShot 2025-01-13 at 12 38 45@2x](https://github.com/user-attachments/assets/275d55fd-d0cd-403f-a8b8-6887046d547d) | ![CleanShot 2025-01-13 at 12 38 40@2x](https://github.com/user-attachments/assets/70cfb107-b71c-4030-88e0-4e0051040fcb) |
> Update repo icon in Expo quickstart

- docs/deployments/clerk-environment-variables.mdx
- docs/references/react-router/custom-signup-signin-pages.mdx
- docs/references/remix/custom-signup-signin-pages.mdx
- docs/upgrade-guides/core-2/javascript.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1888/deployments/clerk-environment-variables
> - https://clerk.com/docs/pr/1888/references/react-router/custom-signup-signin-pages
> - https://clerk.com/docs/pr/1888/references/remix/custom-signup-signin-pages
> - https://clerk.com/docs/pr/1888/upgrade-guides/core-2/javascript
- Update references of `CLERK_SIGN_IN_FALLBACK_URL` to `CLERK_SIGN_IN_FALLBACK_REDIRECT_URL`
-
> fix: CLERK_SIGN_IN_FALLBACK_URL usage

- docs/components/control/redirect-to-createorganization.mdx
- docs/components/control/redirect-to-organizationprofile.mdx
- docs/components/control/redirect-to-userprofile.mdx
Page titles are parsed as MDX so `<RedirectToCreateOrganization />` needs to be escaped or wrapped in `` ` ``
https://clerk.com/docs/pr/1891/components/control/redirect-to-createorganization
> Fix page title

- docs/authentication/social-connections/hubspot.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1896/authentication/social-connections/hubspot
Trying to use HubSpot as an OAuth provider was giving this error:
We never had a step in the docs where the user is supposed to add a required `crm.objects.owners.read` scope. This PR adds this crucial step.
> (social-connections/hubspot) add missing scope

- docs/troubleshooting/create-a-minimal-reproduction.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1898/troubleshooting/create-a-minimal-reproduction
- The Chrome Extension link for the minimal reproduction page pointed to a now non-public repo. Some of the other links were to `github.com/clerkinc` which is no longer valid.
- Updated links.
> fix: Fixed Extension link, and changed clerkinc to clerk for other links

- docs/quickstarts/vue.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1901/quickstarts/vue#create-a-header-with-clerk-components
- Missing `setup` directive in the script tag which is important to make the quickstart work
- Adds the `setup` directive and also `lang` for consistency
> docs(vue): Add missing `setup` directive

- docs/quickstarts/express.mdx
- docs/references/express/overview.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1899/quickstarts/express
https://clerk.com/docs/pr/1899/references/express/overview
Aligning the Express docs with [its dedicated repo.](https://github.com/clerk/clerk-express-quickstart)
Fixes DOCS-9807
> (express) update quickstart and overview

- docs/users/invitations.mdx
Fixes a typo `redirecrs` => `redirect`
should be redirect 
fixes the typo
- [ x] I have clicked on "Files changed" and performed a thorough self-review
> Fix typo in invitation redirect documentation

- docs/references/javascript/external-account.mdx
- docs/references/javascript/sign-in/sign-in.mdx
- docs/references/javascript/sign-up/sign-up.mdx
- docs/references/javascript/sign-up/verification.mdx
- docs/references/javascript/user/create-metadata.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1885/references/javascript/external-account
> - https://clerk.com/docs/pr/1885/references/javascript/sign-in/sign-in
> - https://clerk.com/docs/pr/1885/references/javascript/sign-up/sign-up
> - https://clerk.com/docs/pr/1885/references/javascript/sign-up/verification
> - https://clerk.com/docs/pr/1885/references/javascript/user/create-metadata
This PR adds `oidcPrompt` & `oidcLoginHint` to the following types  for Clerk JS:
- `ReauthorizeExternalAccountParams`
- `SignInCreateParams`
- `PrepareVerificationParams`
- `SignUpCreateParams`
- `CreateExternalAccountParams`
more information about what `oidcPrompt` and `oidcLoginHint` mean: https://clerkinc.slack.com/archives/C01QFRQNHSN/p1736980805072979
> feat: Add `oidcPrompt` & `oidcLoginHint`

- docs/_partials/custom-flows/phone-number.mdx
- docs/custom-flows/add-phone.mdx
- docs/custom-flows/email-sms-otp.mdx
- docs/custom-flows/manage-sms-based-mfa.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1913/custom-flows/manage-sms-based-mfa
> - https://clerk.com/docs/pr/1913/custom-flows/add-phone
> - https://clerk.com/docs/pr/1913/custom-flows/email-sms-otp
- Custom flow docs for phone/sms do not mention the format. 
- Added callout with link to Wikipedia indicating that they must be in E.164 format.
> refactor: Added callout that phone number must be in E.164 format

- docs/references/expo/overview.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1923/references/expo/overview
https://clerkinc.slack.com/archives/C05GH6N5LLS/p1737133942872259
Updates the `id` for a couple headings on the Expo overview page because "Clerk components" gets an auto-generated `id` of `clerk-components` and this is interacting with Clerk in some way causing the heading to disappear. I also updated the "Clerk hooks" `id` just for consistency on this page.
> Fix "Clerk components" heading disappearing

- docs/components/clerk-provider.mdx
- docs/components/control/clerk-loaded.mdx
- docs/components/control/clerk-loading.mdx
- docs/components/control/signed-in.mdx
- docs/components/control/signed-out.mdx
- docs/components/protect.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
https://linear.app/clerk/issue/DOCS-9771/update-component-references-to-include-all-sdks
Adds examples for the Clerk components in the @clerk/clerk-expo module
> Document available expo clerk components

- docs/organizations/overview.mdx
Currently, the docs reference an outdated flow for creating organizations, wherein you need to select an organization owner.
Currently, we don't ask for the organization owner at all. After creating an org, the dashboard user can invite application users with the admin role if they so choose.
This removes that instruction.
We still display an "Owner" field on the organization inspect view, which is always empty if the org was created via the dashboard. See the linear ticket for next steps - the current intention is to change that field to "created by" (as it actually is in the API layer), and set it to something like "An Admin" if it's empty.
https://clerk.com/docs/pr/1924/organizations/overview
> bug(orgs): remove outdated instruction to set an organization owner

- docs/_partials/authentication/microsoft/create-app.mdx
- docs/_partials/authentication/microsoft/enable-openid.mdx
- docs/_partials/authentication/microsoft/get-client-id-secret.mdx
- docs/_partials/authentication/microsoft/noauth.mdx
- docs/authentication/enterprise-connections/easie/microsoft.mdx
- docs/authentication/social-connections/microsoft.mdx
- **preview**: https://clerk.com/docs/pr/1929/authentication/social-connections/microsoft
- **ticket**: https://linear.app/clerk/issue/DOCS-9776/add-a-note-about-client-credentials-expiring-to-msft-sso-docs
- **note**: added warnings to two different places, one under production instances and one right next to the step where the client sets up the secret
> (sso microsoft): add warning about client credentials expiring; align oauth and easie guides

- docs/_partials/authentication/passkeys-restriction.mdx
- docs/authentication/configuration/sign-up-sign-in-options.mdx
- docs/custom-flows/passkeys.mdx
**previews**
- https://clerk.com/docs/pr/1931/custom-flows/passkeys
- https://clerk.com/docs/pr/1931/authentication/configuration/sign-up-sign-in-options
**tickets**
- https://linear.app/clerk/issue/DOCS-9767/add-passkey-information-about-localhost
- https://linear.app/clerk/issue/DOCS-9623/passkeys-dev-instance-account-portal
> add info about passkey behavior in dev

- docs/authentication/social-connections/google.mdx
- docs/components/authentication/google-one-tap.mdx
- docs/custom-flows/google-one-tap.mdx
**preview**
- docs/components/authentication/google-one-tap
- docs/authentication/social-connections/google
**ticket**: https://linear.app/clerk/issue/DOCS-9766/add-note-to-google-one-tap-about-allowed-js-origins
> add info on adding domains to allowed js origins for google one tap

- docs/advanced-usage/using-proxies.mdx
- https://clerk.com/docs/pr/1945/advanced-usage/using-proxies
- (nextjs tab)
The current proxy example for NextJS matches `__clerk` anywhere in the URL which will match search params like `__clerk_ticket` or `__clerk_status` and proxy those requests. 
Developers who use the example scheme we have of `/__clerk` may run into issues. 
Updated the example to use `nextUrl.pathname` as this will exclude search params.
> Updated NextJS proxy example to use nextUrl.pathname

- package.json
- scripts/check-quickstarts.mjs
If there are changes to a `/quickstarts/**.mdx` file, we need the linter to check and warn the Docs Team that they need to reflect those changes in the corresponding quickstart in the Dashboard
> Add script that warns about changes in quickstarts

- .github/workflows/lint.yml
- scripts/check-quickstarts.mjs
Related to https://github.com/clerk/clerk-docs/pull/1952
We have a script that warns us in development if changes have been made to a quickstart.
This PR updates the script to also check for those changes in the GH PR, not just in local dev.
This PR also updates our lint GH action to post a comment if changes have been made to a quickstart, to remind contributors to also update the Dashboard for the corresponding quickstarts.
> Create GH action for warning about quickstart changes

- docs/components/control/authenticate-with-callback.mdx
- docs/references/react/use-auth.mdx
- docs/references/react/use-organization-list.mdx
- docs/references/react/use-organization.mdx
- docs/references/react/use-session-list.mdx
- docs/references/react/use-session.mdx
- docs/references/react/use-sign-in.mdx
- docs/references/react/use-sign-up.mdx
- docs/references/react/use-user.mdx
- docs/references/vue/use-user.mdx
- https://clerk.com/docs/pr/1958/references/react/use-auth
I noticed on https://clerk.com/docs/references/react/use-auth that the description for `isLoaded` was missing. I figured the wrong indentation caused that.
Update (Alexis): found a few more in other tables.
-
> fix incorrect indentations in tables

- docs/security/clerk-csp.mdx
-
Put in a change that will thread through the nonce to clerk-injected styles with strict dynamic CSPs a few months ago but forgot to update the docs with it, shame on me.
> Remove unsafe-inline from style-src for strict dynamic

- docs/components/authentication/google-one-tap.mdx
- docs/components/authentication/sign-in.mdx
- docs/components/authentication/sign-up.mdx
- docs/components/waitlist.mdx
- https://clerk.com/docs/pr/1950/components/authentication/google-one-tap#usage-with-frameworks
- The `<GoogleOneTap />` component examples are placed incorrectly. The `<GoogleOneTap />` renders a `<div>` element and it can't be a direct child of `<html>`
- Moved component placements inside `<body>`
> Fix `<GoogleOneTap />` examples

- docs/manifest.json
- https://clerk.com/docs/pr/1961
- The C# icon in the nav is outdated
- Use the `c-sharp` icon which is up to date, instead of the `csharp` icon which is outdated
✨ Please see clerk/clerk#969 for the preview
> Update C# icon in nav

- docs/custom-flows/enterprise-connections.mdx
- https://clerk.com/docs/pr/1960/custom-flows/enterprise-connections
- Tried to create a custom enterprise sso flow today with the example and the redirect back to /sso-callback resulted in a 404 because the walkthrough has the sso callback page at /sign-up/sso-callback.
- I updated the redirectUrl to be /sign-up/sso-callback which is consistent with our custom OAuth flow doc.
> Correct the redirectUrl for the Enterprise SSO custom flow.

- docs/_partials/clerk-provider/properties.mdx
- Broken link in `docs/_partials/clerk-provider/properties.mdx`
```diff
- /last-activepath=api-keys
+ /last-active?path=api-keys
```
> Fix dashboard link in ClerkProvider partial

- docs/quickstarts/nextjs.mdx
In #1699 we had the quickstart hidden from search and crawlers.
> [fix] Make nextjs quickstart search visible

- docs/manifest.json
- The "Keyless Mode" link in the navigation links to a page that doesn't exist
- Removed the "Keyless Mode" link from the navigation (`manifest.json`)
> Remove broken link from navigation/manifest

- docs/references/ios/overview.mdx
-
- We changed the name of the swift package, so the existing link to its docs broke
- The link to the swift docs is now correct
> fix link to swift reference docs

- docs/references/javascript/overview.mdx
- Broken link at `/docs/references/javascript/overview`
```diff
- docs/references/javascript/types/session-with-activities
+ /docs/references/javascript/types/session-with-activities
```
> Fix link in JavaScript reference overview

- docs/quickstarts/ios.mdx
- https://clerk.com/docs/pr/1983/quickstarts/ios
- Updates the iOS quick start to reflect recent changes.
> update ios quickstart

- docs/references/ios/sign-in-with-apple.mdx
- https://clerk.com/docs/pr/1984/references/ios/sign-in-with-apple
- Updates the iOS Sign in with Apple guide to account for recent changes to the sdk.
> update ios sign in with apple guide

- docs/webhooks/overview.mdx
- https://clerk.com/docs/pr/1985
Adds information about the instance_id key in the webhooks payload.
Added explanation of what the `instance_id` field is and updated the example payload.
> feat: Webhook instance ID

- docs/quickstarts/expo.mdx
-
- Make docs more user-friendly and prevent issues caused by incorrect memoization when copying and pasting code.
- add missing dependencies for useCallback on expo quick-start
- we can remove the useCallback() altogether!
> fix: remove useCallback from Expo quickstart

- docs/quickstarts/astro.mdx
- docs/quickstarts/expo.mdx
- docs/quickstarts/express.mdx
- docs/quickstarts/fastify.mdx
- docs/quickstarts/ios.mdx
- docs/quickstarts/javascript.mdx
- docs/quickstarts/nextjs-pages-router.mdx
- docs/quickstarts/nuxt.mdx
- docs/quickstarts/react-router.mdx
- docs/quickstarts/react.mdx
- docs/quickstarts/remix.mdx
- docs/quickstarts/ruby.mdx
- docs/quickstarts/tanstack-start.mdx
- docs/quickstarts/vue.mdx
- docs/references/nextjs/authjs-migration.mdx
- docs/references/react-router/library-mode.mdx
- docs/references/remix/spa-mode.mdx
-
Before, we needed to tell the <TutorialHero /> component whether the framework was Nextjs or not. If it was Nextjs, the component would supply the App Router and Pages Router repos to the exampleRepo prop
Now, Nextjs has separate App Router vs Pages Router quickstarts, so we no longer need to support nextjs specificity in the <TutorialHero />
- Removes the `framework` prop from the `<TutorialHero />` component
- Explicitly passes the example repository to the Nextjs Pages Router `<TutorialHero />` component (as its not automatically supplied based on the `framework` prop anymore)
https://github.com/clerk/clerk/pull/997
> remove the framework prop from tutorialhero

- docs/quickstarts/ios.mdx
- docs/references/ios/overview.mdx
- docs/references/ios/sign-in-with-apple.mdx
- https://clerk.com/docs/pr/1997/quickstarts/ios
- https://clerk.com/docs/pr/1997/references/ios/overview
- https://clerk.com/docs/pr/1997/references/ios/sign-in-with-apple
- While the iOS SDK is still technically in beta (though not for long 😏), it is considered stable.
> remove ios beta warnings

- docs/customization/user-profile.mdx
https://clerk.com/docs/pr/1994
We've had a handful of folks attempting to utilize the JavaScript example on this page and reporting that the feature is broken or bugged. This will solve the broken behavior experienced from our users.
After testing and reproducing the behavior we found the current example in the docs doesn't work. The former example reflects using the openUserProfile() method which opens this component as a modal. Custom pages cannot be mounted this way. Adjusted example to utilize the mountUserProfile() instead which works as intended.
- Change `clerk.openUserProfile()` -> `clerk.mountUserProfile()`
This change reflects the correct method to use in the example code we provide.
> (/customization/user-profile) fix broken javascript example

- docs/components/user/user-button.mdx
-
- The `afterMultiSessionSingleSignOutUrl` prop description said to move `afterSignOutUrl`. It was referencing the wrong prop.
> (/components/user/user-button) fix incorrect prop description

- docs/references/expo/local-credentials.mdx
-
The guide was outdated. I've updated the copy to follow the Clerk Docs voice and semantics. 
There were imports and other things missing from the code examples. I've updated those as well.
> (/references/expo/local-credentials): update guide

- docs/customization/user-button.mdx
- https://clerk.com/docs/pr/1999/customization/user-button
- Since the implementation uses Vue [slots](https://vuejs.org/guide/components/slots) (rather than props like in React) to pass in custom components, it's important to document this approach.
- Adds Vue examples to each section of the custom menu items docs
- Shows proper usage of template slots for custom components
> (/customization/user-button) Add Vue examples; update copy

- docs/references/javascript/organization/organization.mdx
-
- Wrong description of properties.
- Fixed some small typos in the `organization.mdx` where it was `role` instead of `permission`.
> docs(javascript): fix wrong type name

- docs/references/sdk/types.mdx
This PR corrects a link to `clerk-sdk-go` in `docs/references/sdk/types.mdx`
> Fix `clerk-sdk-go` link

- docs/quickstarts/express.mdx
Directly using getAuth, as mentioned in the docs creates a reference error with the message: `ReferenceError: getAuth is not defined`. However, importing and destructuring it alongside clerkMiddleware and requireAuth as `import { clerkMiddleware, requireAuth, getAuth } from "@clerk/express";` resolves the issue
- [Clerk Express Quickstart - Protect Your Routes Using requireAuth](https://clerk.com/docs/quickstarts/express#protect-your-routes-using-require-auth)
- Directly using `getAuth` as documented results in a `ReferenceError: getAuth is not defined`.  
- This occurs because `getAuth` is not automatically available in the scope unless explicitly imported.  
- By importing `getAuth` alongside `clerkMiddleware` and `requireAuth` as:  
```js
import { clerkMiddleware, requireAuth, getAuth …
```
> (quickstarts/express) Add missing `getAuth` import

- docs/advanced-usage/clerk-idp.mdx
- docs/manifest.json
- https://clerk.com/docs/pr/1968
- Now you can use your Clerk instance, not only as an OAuth 2.0 provider, but also as an OpenID Connect (OIDC) provider
- We enhance the existing docs page, with the necessary data for the OpenID Connect flows
> feat: Clerk as an OpenID Connect provider

- docs/references/javascript/organization/invitations.mdx
Links were to /types/organization-domain and should be to /types/organization-invitation
> (/references/javascript/organization/invitations) fix incorrect links

- docs/references/react/use-organization.mdx
Adds correct types with appropriate reference links for the return properties.
> (/react/use-organization) add correct types for the returns

- docs/references/astro/auth-store.mdx
Audited headings that include "returns" in it to ensure they are absolutely necessary.
> fix headings that include "returns" in the text

- docs/backend-requests/resources/session-tokens.mdx
- The `fva` claim was missing from our session token default claims
- Adds missing `fva` claims to default claims
- Updates lists to be markdown tables instead for better visual clarity
> add fva claim; restructure to use tables

- docs/custom-flows/user-impersonation.mdx
User feedback tickets reads:
> Please call out that both (impersonation and custom roles) features shown in this example are add-on's. You'll want to also talk about how to create the custom role that you've shown, otherwise I don't think it will work as shown?
- Adds copy to indicate to the user that for the guide, they must create the custom permission.
> (custom-flows/user-impersonation) mention needing to create the custom perm

- docs/customization/localization.mdx
This PR adds `bun` as an option in the localization setup guide for installing `@clerk/localizations`.
**Changes:**
- Added `bun add @clerk/localizations` to installation commands.
> I believe `bun` should be added across all documentation.
> Add `bun` Support to Localization Doc

- docs/guides/custom-types.mdx
- docs/references/backend/types/auth-object.mdx
- docs/references/javascript/organization/members.mdx
- docs/references/javascript/types/organization-custom-permission-key.mdx
- docs/references/javascript/types/organization-custom-role-key.mdx
- docs/references/javascript/types/organization-invitation.mdx
- docs/references/javascript/types/user-organization-invitation.mdx
- docs/references/react/use-organization.mdx
- https://clerk.com/docs/pr/2038/references/react/use-organization
- The `useOrganization()` table wasn't rendering properly
- Fixes the table
- Reorganizes the table to be more visually palatable (using lists in the property descriptions)
- Created type references for `OrganizationCustomRoleKey` and `OrganizationCustomPermissionKey`
- Removes sections like "OrganizationCustomRoleKey" and "OrganizationCustomPermissionKey"
- Updates tables across docs to link to these references
- Adds a section to our "Custom types" guide to demonstrate how to define custom types for roles and permissions (as related to `OrganizationCustomRoleKey` and `OrganizationCustomPermissionKey`)
> fix useOrganization() table

- docs/upgrade-guides/node-to-express.mdx
- https://clerk.com/docs/pr/2052/upgrade-guides/node-to-express
- I am validating that all docs have a title, this guide is failing due to the title not being in the frontmatter
- Moved the title up in to the frontmatter
> Move the "Node to Express Migration" docs title up in to the markdown frontmatter

- docs/_partials/clerk-middleware-options.mdx
- docs/_partials/clerk-options.mdx
- docs/_partials/root-auth-loader.mdx
- docs/backend-requests/manual-jwt.mdx
- docs/integrations/databases/fauna.mdx
- docs/integrations/databases/hasura.mdx
- docs/integrations/databases/nhost.mdx
- docs/organizations/invitations.mdx
- docs/references/backend/authenticate-request.mdx
- docs/references/backend/verify-token.mdx
- docs/users/invitations.mdx
- Changes to the Clerk Dashboard's API keys page was made. The sidebar is now on the right, and there is no longer a "Show JWT public key" option anymore.
> Align with dashboard updates to API keys page

- docs/manifest.json
- https://clerk.com/docs/pr/2042/deployments/clerk-environment-variables
The link `/docs/upgrade-guides/api-keys` gets redirected to `/docs/deployments/clerk-environment-variables` so faster to just have it link directly. It's possible instead we just want to remove this item? instead of having it duplicated as "Clerk environment variables" also links to `/docs/deployments/clerk-environment-variables`.
- Updated link in manifest
> Update "API Key Changes" in manifest to redirected href

- docs/custom-flows/forgot-password.mdx
- docs/references/javascript/sign-in.mdx
- https://linear.app/clerk/issue/DOCS-9993/confusing-resetpassword-documentation-and-behavior
- User feedback reported confusing documentation surrounding `resetPassword()`
- Adds a recommendation to use our forgot password custom flow instead.
- Updates the forgot password custom flow guide.
- Tests email code, adds updates like wrapping the `router.push` in a useEffect()
- Adds section for phone code.
- Updates the copy to explain what the reset password flow looks like
> update forgot password flow

- .github/workflows/lint.yml
- docs/components/authentication/sign-in.mdx
- package.json
- scripts/check-frontmatter.mjs
Titles that start or end with a backtick (or both) must be wrapped in quotations.
Creates a script that checks the formatting of the title of a page. Updates the GH action to run the lint step for PRs. 
⚠️  There's currently an incorrect title as an example of how the lint checker fails.
Examples:
❌ title: `auth()`
✅  title: '`auth()`'
❌  title: `<SignIn />` component
✅  title: '`<SignIn />` component'
> Create script to check formatting of titles

- docs/manifest.json
-
- The urls for the elements guides have changed, but where not updated in the manifest.json, this causes slower loading times as requests have to go through the redirect catcher.
- Updated Hrefs
> Update the Elements hrefs in manifest.json

- docs/components/waitlist.mdx
- https://clerk.com/docs/pr/2071/components/waitlist#usage-with-frameworks
- We're missing a `<Waitlist />` example for our Astro an Vue SDK
- Adds a new tab with example for Astro and Vue 👍🏼
> docs: Add `<Waitlist />` Astro and Vue example

- docs/references/chrome-extension/overview.mdx
> Clarify why Chrome Extensions dont allow OAuth/SAML

- docs/quickstarts/nextjs.mdx
- https://clerk.com/docs/pr/2076/quickstarts/nextjs
- Currently we only give a command for creating the nextjs app with npx, this doesn't align with the rest of the guide that has examples for the four major package managers
- Based on the react quickstart which has all four package managers, I used the `create` command that each package manager exposes.
> Add package manager tabs to Next.js quickstart

- docs/advanced-usage/using-proxies.mdx
-
The current Clerk docs do not specify a port for the Next.js proxy. As the url is taken from the request url, any port that the user is accessing the server from (or more likely, the port that a reverse proxy listens to) gets used on the clerk request. So you end up with frontend-api.clerk.dev:8080 being fetched.
I have added a specification of the correct SSL port.
> Include port on Next.js proxy example

- docs/_partials/environment-variables.mdx
- docs/components/authentication/sign-in.mdx
- docs/components/authentication/sign-up.mdx
- docs/components/waitlist.mdx
- docs/deployments/clerk-environment-variables.mdx
- docs/guides/custom-redirects.mdx
- docs/references/expo/web-support/custom-sign-in-or-up-page.mdx
- docs/references/expo/web-support/custom-sign-up-page.mdx
- docs/references/nextjs/custom-sign-in-or-up-page.mdx
- docs/references/nextjs/custom-sign-up-page.mdx
- docs/references/react-router/custom-sign-in-or-up-page.mdx
- docs/references/react-router/custom-sign-up-page.mdx
- docs/references/remix/custom-sign-in-or-up-page.mdx
- docs/references/remix/custom-sign-up-page.mdx
- docs/references/tanstack-start/custom-sign-in-or-up-page.mdx
- docs/references/tanstack-start/custom-sign-up-page.mdx
A [user's feedback ticket](https://linear.app/clerk/issue/DOCS-10002/feedback-for-upgrade-guidescore-2nextjs) inspired me to investigate how we explain our custom redirect URLs (using env vars).
- Clarified what these env vars are used for
- E.g. "Used for the 'Sign In' link" --> "Used for the 'Already have an account? Sign in' link"
- Fixed `CLERK_SIGN_UP_FALLBACK_URL` to `CLERK_SIGN_UP_FALLBACK_REDIRECT_URL`
In the `<SignIn/>` and `<SignUp/>` component references:
- Put prop tables in alphabetical order
- Updated prop descriptions
- Added links to the redirect URL guide where the examples are for each SDK, so that users can find these guides more easily.
- Updated `withSignUp` prop description
- Added `<If sdk="javascript">` to the JavaScript sections of the component references
In the …
> Clarify custom redirect URLs (env var usage)

- docs/components/authentication/sign-in.mdx
- docs/components/authentication/sign-up.mdx
I saw builds fail because of incorrect prop:
```
items passed to <If /> "javascript" are not a valid SDK. Valid SDKs are "nextjs", "react", "javascript-frontend", "astro", "csharp", "chrome-extension", "expo", "expressjs", "fastify", "go", "ios", "javascript-backend", "nuxt", "python", "react-router", "remix", "ruby", "tanstack-start", "vue", "sdk-development", "community-sdk"
```
> fix: `<If>` usage for `javascript`

- docs/advanced-usage/clerk-idp.mdx
- docs/drizzle.mdx
- https://clerk.com/docs/pr/2082/advanced-usage/clerk-idp
We have had many users come across the "Clerk as an OAuth2/OIDC IDP" feature and reasonably assume that this meant that Clerk will run a full OAuth2 server for your app which handles not only initial authentication, but also handles subsequent request authorization to API endpoints within your application.
At the moment, this feature only handles initial authentication, and that was not clear in the docs, so I added a section to clarify this.
> Add clarification to clerk as IDP docs page

- docs/hooks/use-auth.mdx
- docs/hooks/use-clerk.mdx
- docs/hooks/use-organization-list.mdx
- docs/hooks/use-organization.mdx
- docs/hooks/use-reverification.mdx
- docs/hooks/use-session-list.mdx
- docs/hooks/use-session.mdx
- docs/hooks/use-sign-in.mdx
- docs/hooks/use-sign-up.mdx
- docs/hooks/use-user.mdx
- https://clerk.com/docs/pr/2092/hooks/use-user
- https://clerk.com/docs/pr/2092/hooks/use-clerk
- https://clerk.com/docs/pr/2092/hooks/use-auth
- https://clerk.com/docs/pr/2092/hooks/use-sign-in
- https://clerk.com/docs/pr/2092/hooks/use-sign-up
- https://clerk.com/docs/pr/2092/hooks/use-session
- https://clerk.com/docs/pr/2092/hooks/use-session-list
- https://clerk.com/docs/pr/2092/hooks/use-organization
- https://clerk.com/docs/pr/2092/hooks/use-organization-list
- https://clerk.com/docs/pr/2092/hooks/use-reverification
- For the nextjs examples in the docs we don't use the `src` folder
- updates the paths
> Switch nextjs file paths to not use src folder

- docs/deployments/overview.mdx
https://linear.app/clerk/issue/DOCS-9978/add-csp-to-deployment-docs
https://linear.app/clerk/issue/DOCS-9977/make-sure-to-mention-to-re-deploy-after-changing-keys
- Links users to CSP guide in our Deployment guide, so that they don't forget to update their CSP headers
- In Deployment guide, reminds users to redeploy after changing keys
FIXES DOCS-9978, DOCS-9977
> add csp step to deployment guide

- docs/references/ios/overview.mdx
- iOS does not support hooks. It also doesn't support components yet. The copy was a bad copy and paste when updating all SDK overviews
- updates the copy to be accurate to what the iOS SDK offers
> (ios) remove mention of components from overview

- docs/quickstarts/expo.mdx
- https://clerk.com/docs/pr/2103/quickstarts/expo
- Simplifies the Expo quickstart a bit
- Removed installation of `@clerk/types` step. Installing `@clerk/clerk-expo` includes `@clerk/types` by default, so they can just import if needed. Also, it raises the question on why do we have the step here but not in other SDKs.
- `<ClerkLoaded>` wrapping root layout means the entire app won't render until Clerk is loaded, which sounds like an anti-pattern. I tried our quickstart and removed this, everything is still expected to work 👍🏼 🫡
> docs: Simplify Expo quickstart

- docs/_partials/expo/sign-out-custom-flow.mdx
- docs/custom-flows/sign-out.mdx
- docs/quickstarts/expo.mdx
- docs/references/expo/overview.mdx
- We've had user complaints about not having sign out functionality, and its fair feedback.
- Adds a step to the quickstart for adding a sign out button
- Updated https://github.com/clerk/clerk-expo-quickstart to match these changes
> (expo) include sign out functionality in quickstart

- docs/manifest.json
- docs/references/expo/access-clerk-outside-components.mdx
- docs/references/expo/accessing-clerk-outside-components.mdx
- https://clerk.com/docs/pr/2102/references/expo/accessing-clerk-outside-components
https://github.com/user-attachments/assets/40d92a80-ccda-477a-b95e-427e5da97e40
Demo repo: https://github.com/wobsoriano/clerk-docs-2102
- We have a [massive discussion](https://github.com/orgs/clerk/discussions/1751#discussioncomment-10162453) on how to access the Clerk instance outside of React components in Expo applications. We have the `getClerkInstance()` available [since last year](https://github.com/clerk/javascript/pull/3420), but it's not documented and is hard for customers to find.
- This PR adds a dedicated Expo guide with some practical examples on how to access Clerk instance outside of components.
> docs(expo): Add guide for accessing Clerk outside components in Expo

- docs/authentication/social-connections/overview.mdx
- docs/references/backend/user/get-user-oauth-access-token.mdx
Reflects changes made in https://github.com/clerk/javascript/pull/5097
> remove usage of the oauth prefix in getUserOauthAccessToken

- docs/quickstarts/chrome-extension.mdx
- docs/quickstarts/expo.mdx
- docs/quickstarts/ios.mdx
- Previously customers had to enable the native API before they could integrate with their native application. This is no longer necessary as it is enabled by default for development instances.
- Remove the step in favor of a callout to enable the Native API
> chore: remove requirement to enable native API during development

- docs/quickstarts/ios.mdx
- https://clerk.com/docs/pr/2115/quickstarts/ios
- Adding `@State` annotation to the clerk reference in the quick start for clarity.
> iOS: add state annotation to quick start clerk reference

- docs/users/metadata.mdx
I believe the intention here was to use `role` as an example of public metadata, and that using the `stripeId` was a copy/paste mistake from the private metadata example.
> fix: use `role` in public metadata example (to be consistent)

- docs/custom-flows/email-sms-otp.mdx
- https://clerk.com/docs/pr/2126/custom-flows/email-sms-otp#sign-in-flow
- If a user has more than one phone number, the docs would have just grabbed the first one. This makes sure it grabs the phone number used to initiate the sign in flow.
- Adds additional filter when pulling the phone code factor.
> update ios email sms otp example code

- docs/custom-flows/enterprise-connections.mdx
- docs/custom-flows/oauth-connections.mdx
- https://clerk.com/docs/pr/2098/custom-flows/enterprise-connections
- https://clerk.com/docs/pr/2098/custom-flows/oauth-connections
- We were receiving user feedback with confusion on how to use the makeRedirectUri() method
- Adds a link to the Expo docs so users can see how to use the makeRedirectUri() method
> (expo) clarify usage of makeRedirectUri()

- .github/pull_request_template.md
- .github/workflows/preview.yml
- .github/workflows/revalidate.yml
This PR updates the preview workflows to account for https://github.com/clerk/clerk/pull/1087 – please check out that PR for more info
- Share the preview URL when a first-party PR is _opened_ (replaces "_(un)labeled_")
- Revalidate the preview when a first-party PR is updated (via `synchronize` event)
- Remove `deploy-preview` label reference in pull request template
> [!IMPORTANT]
> ~We should merge https://github.com/clerk/clerk/pull/1087 first~ ✅
> Update workflows to remove `deploy-preview` label

- docs/components/clerk-provider.mdx
- docs/quickstarts/expo.mdx
- docs/references/expo/offline-support.mdx
- docs/references/expo/passkeys.mdx
- https://clerk.com/docs/pr/2127/quickstarts/expo#add-clerk-provider-to-your-root-layout
- https://clerk.com/docs/pr/2127/quickstarts/expo#configure-the-token-cache
- https://clerk.com/docs/pr/2127/references/expo/passkeys#update-your-clerk-provider
- https://clerk.com/docs/pr/2127/references/expo/offline-support#use-the-experimental-resource-cache-property-on-clerk-provider
- https://clerk.com/docs/pr/2127/components/clerk-provider
- We already handle the `EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY` environment variable check at runtime. See https://github.com/clerk/javascript/pull/5399.
- Removes the steps where we check for `EXPO_PUBLIC_CLERK_PUBLISHABLE_KEY` and pass it to the `<ClerkProvider>`. We do this at runtime already 👍🏼
> docs(expo): Remove publishable key checks

- docs/hooks/use-clerk.mdx
-
- The warning was probably copy pasted, but wasn't updated to reflect this hook is used in a react environment instead of vue
- changed `composable` to `hook`
> Update`useClerk()` warning message

- .github/workflows/revalidate.yml
Fixes the branch owner check in `.github/workflows/revalidate.yml` to ensure the preview revalidation runs on PR synchronise.
> Fix preview revalidation workflow condition

- docs/quickstarts/react.mdx
Fix some grammar
Change the code highlighter
-
- 
-
> (react quickstart) small copy updates; fix code highlight

- docs/authentication/enterprise-connections/saml/azure.mdx
Preview: https://clerk.com/docs/pr/2112
Here's how configuring SAML usually works:
1. An App Owner begins to onboard a new enterprise, and is put in touch with the enterprise's IT Admin
2. The App Owner creates the saml connection, and shares the Entity ID and Reply URL with the IT Admin via an email, along with more instructions
3. The IT admin follows those instructions, and responds via email with a metadata url
4. The App owner adds the metadata URL, and then coordinates on a time with the IT admin to enable and test the connection
Our docs today don't reflect that reality. They presume the the reader has simultaneous access to Clerk and the Microsoft IDP. As such, an application owner reading our docs needs to understand them deeply enough to re-write them into an email suitable for …
> Rewrite Azure SAML docs for application owners

- docs/deployments/changing-domains.mdx
A user is confused on why they can't see the "Danger" tab in the Domains section of the Dash.
It's because they're trying to change their Clerk provisioned domain (dev instance), which is not allowed.
> (changing-domains) change callout from note to warning

- docs/references/backend/types/auth-object.mdx
None yet.
We were seeing rate limiting issues while performing `getToken({ template: 'my-template' })`. This behavior was unclear from the documentation, especially since tokens are typically retrieved directly from request cookies without making an API request.
After cloning the Clerk codebase, we found the following:
```
export function signedInAuthObject(...): SignedInAuthObject {
...
const apiClient = createBackendApiClient(authenticateContext);
const getToken = createGetToken({
sessionId,
sessionToken,
fetcher: async (...args) => (await apiClient.sessions.getToken(...args)).jwt,
});
}
const createGetToken: CreateGetToken = params => {
const { fetcher, sessionToken, sessionId } = params || {};
return async (options: ServerGetTokenOptions = {}) => {
if (!sessionId) {
return null;
}
if …
```
> docs: Add Rate Limiting Information For `getToken` With Template

- docs/components/control/clerk-loaded.mdx
- docs/components/control/clerk-loading.mdx
- https://clerk.com/docs/pr/2156/components/control/clerk-loaded
- https://clerk.com/docs/pr/2156/components/control/clerk-loading
- Wrapping your app in either of these components can lead to your entire app not rendering if Clerk is down
- Only wrap Clerk-related components with these components
> (clerkloaded, clerkloading) do not wrap app

- docs/references/nextjs/clerk-middleware.mdx
-
- Removes an unused and non-existent import (redirectToSignIn), reducing confusion, from the "Combine Middleware" example for Next.js.
> docs(nextjs): removed unused/non-existing imported function

- docs/authentication/enterprise-connections/saml/azure.mdx
fix typo -- `First name` is written twice, including for the claim surname.
Could also consider renaming attribute fields to Given Name / Surname.
- TBD
- Fixes typo with Azure SAML mislabeled claim.
- Fixes typo with Azure SAML mislabeled claim.
> [typo] Update Azure SAML mislabeled claim

- package-lock.json
- package.json
- scripts/build-docs.test.ts
- scripts/build-docs.ts
- Currently the script will fail if a heading is in a partial embedded in to a page, and another page attempts to link to that heading in the partial
- This change temporarily embeds the partials in to the page before extracting the headings to be accurate
> Validate links to headings inside of partials

- docs/references/javascript/types/external-account.mdx
- https://clerk.com/docs/pr/2168
- We make sure to keep our docs types up to date with our actual FE types
- We introduced a new property 'phoneNumber' as part of the external account type and response
> Add 'external_account.phoneNumber' property on type references

- docs/account-portal/disable-account-portal.mdx
- docs/authentication/social-connections/linkedin-oidc.mdx
- docs/backend-requests/resources/session-tokens.mdx
- docs/components/authentication/sign-up.mdx
- docs/custom-flows/email-links.mdx
- docs/deployments/changing-domains.mdx
- docs/references/backend/types/auth-object.mdx
- docs/references/chrome-extension/configure-consistent-crx-id.mdx
- docs/references/javascript/sign-up.mdx
- docs/references/javascript/types/role.mdx
- docs/references/nextjs/basic-rbac.mdx
- docs/references/nextjs/waitlist.mdx
- docs/testing/playwright/test-authenticated-flows.mdx
- docs/testing/playwright/test-helpers.mdx
- docs/users/user-impersonation.mdx
- scripts/build-docs.test.ts
- scripts/build-docs.ts
The validation script expects all the links to be both a path, then possibly a hash (eg `/docs/quickstart#login`) but sometimes a link only has a hash (eg `#login`) pointing to another point on the page, so we need to validate those links. Currently the script just skips over those links
Added tests with links that only use a hash, then fixed the script, to pull in its own doc to validate against.
> Validate a hash is legit when it links to its own page

- docs/authentication/configuration/force-mfa.mdx
- docs/references/nuxt/clerk-middleware.mdx
- docs/references/nuxt/overview.mdx
- docs/references/nuxt/read-session-data.mdx
- https://clerk.com/docs/pr/2182/references/nuxt/overview#auth-object
- https://clerk.com/docs/pr/2182/references/nuxt/clerk-middleware#authentication-based-protection
- https://clerk.com/docs/pr/2182/references/nuxt/clerk-middleware#protecting-routes-using-custom-permissions
- https://clerk.com/docs/pr/2182/references/nuxt/clerk-middleware#protecting-routes-using-custom-permissions
- https://clerk.com/docs/pr/2182/references/nuxt/read-session-data#server-side
We deprecated `event.context.auth` in favor of `event.context.auth()` as a function [here](https://github.com/clerk/javascript/pull/5513). 
This PR updates all occurrences to use `event.context.auth()` as a function and not the deprecated one.
> docs(nuxt): Use `event.context.auth` as a function

- docs/advanced-usage/using-proxies.mdx
-
-  it doesn't work when i set proxyUrl on .load: e.q. clerk.load({proxyUrl})
-  it works when i set proxyUrl on constructor: e.q. new Clerk(..., {proxyUrl})
> Move proxyUrl parameter to the correct place

- docs/_partials/has-warning.mdx
- docs/references/backend/types/auth-object.mdx
- Clerk released v2 of session tokens, which means the structure of the jwt has changed.
Updates all the examples with session tokens to include tabs for version 2 vs version 1:
> v2 session token followup: update session token examples

- scripts/build-docs.test.ts
- scripts/build-docs.ts
- When updating the validation script to validate typedoc files, I added to the script to pull out the headings / hashes, but failed to add validation to check the links inside the typedoc files.
- Added validation to ensure the links and hashes inside the typedoc markdown point to valid urls and headings
> Add validation for links inside typedoc files

- docs/hooks/use-auth.mdx
- We now return sessionClaims from useAuth(). The engineering PR is [here](https://github.com/clerk/javascript/pull/5565).
- Updates the reference doc's returns table
> useAuth() now returns sessionClaims

- docs/upgrade-guides/long-term-support.mdx
- https://clerk.com/docs/pr/2190/upgrade-guides/long-term-support
Core 1 is now unsupported, so we want to call that out in our docs. Also, we want to clarify the actual supported browsers for Core 2, which targets "last 2 years". Finally, we want to specifically note that Core 1's browser support is frozen at the versions released for the final Core 1 release.
- This PR marks `Core 1` as unsupported on our Long Term Support page.
- Additionally, it clarifies the browser support for Core 1 and Core 2
> Mark Core 1 as unsupported, clarify browser support

- .github/dependabot.yml
- .gitmodules
- package.json
- Currently we download the typedoc generated repo in to this repo when we need it, cloning inside of this repo, git treats this as a implicit submodule, but vscode doesn't fully know how to handle this, and we don't get the full control over it.
- Setup clerk-typedoc ([typedoc-generated](https://github.com/clerk/generated-typedoc)) as an official git submodule, update the package.json scripts, and setup dependabot to check daily for changes to the typedoc repo.
- This is a more manual approach, but that does also give us more control, and a pr preview when changes have been pushed to the typedoc repo before we update to it.
> Treat typedoc repo as a full git submodule

- docs/components/control/signed-in.mdx
- docs/components/protect.mdx
- https://clerk.com/docs/pr/2196/components/protect#usage
- https://clerk.com/docs/pr/2196/components/control/signed-in
These two components return their children via source code due to the way that React hydration works. This change adds a note to the docs to clarify that if there is sensitive information that should be entirely inaccessible to the current user, these components are not enough to secure it.
> Add security warning for Protect and SignedIn components

- .github/dependabot.yml
- .gitignore
- .gitmodules
- package.json
Continuation of https://github.com/clerk/clerk-docs/pull/2194
- We didn't like the author experience of using submodule, files showing up in search and the dual repo in vscode confusion
- Instead of using submodule (either implied or explicit) we will just clone in the latest files, then remove the .git folder to make it a standard dumb folder
- authors will need to remember to run `npm run typedoc:update` to pull in the latest version of the typedoc generated files if they need them
> Remove typedoc submodule, replace with just fetching the typedoc repo contents

- redirects/static/docs.json
-
- Currently `/docs/references/nextjs/overview` redirects to itself which crashes the page
- removed redirect
> Remove infinite redirect

- .github/workflows/redeploy.yml
-
- Currently the redeploy github action only runs on changes to the `/docs/**` folder of this repo, but with the redirects getting moved over to this repo, this means changes to the redirects doesn't make clerk.com redeploy like it did before.
- Add the `redirects/**` folder to the paths config that the github action matches on
> Redeploy on redirects changes

- docs/backend-requests/custom-session-token.mdx
https://linear.app/clerk/issue/DOCS-9981/feedback-for-backend-requestsmakingcustom-session-token
Adds examples for all supported frameworks.
> (custom session tokens) add examples for all supported frameworks

- docs/index.mdx
- docs/quickstarts/overview.mdx
- docs/references/overview.mdx
- https://clerk.com/docs/pr/2214
- https://clerk.com/docs/pr/2214/quickstarts/overview
- https://clerk.com/docs/pr/2214/references/overview
- The build script I'm working on (https://github.com/clerk/clerk-docs/pull/2041) had issues parsing the `<Include />` component when inside the curly braces, easiest fix was to just take them out of the the brackets.
- Updated from `{<Include src="_partials/icons/nextjs" />}` to `<Include src="_partials/icons/nextjs" />`
> Remove curly brackets around includes for icons

- docs/components/pricing-table.mdx
- https://clerk.com/docs/pr/2222/components/pricing-table#usage-with-java-script
- [A user](https://x.com/volkandkaya/status/1919977618578755995) is looking to use the new billing component without React
- Added a "Usage with JavaScript" section for `<PricingTable />`, similar to other components
> docs: Add `<PricingTable />` JavaScript usage

- docs/components/pricing-table.mdx
- https://clerk.com/docs/pr/2225/components/pricing-table#properties
- Renaming `popup` to `drawer`
-
> fix: rename checkout popup to checkout drawer

- docs/custom-flows/oauth-connections.mdx
Updated the redirectUrl param for the Next.js authenticateWithRedirect example to match the SSO callback page example.
Current State:
- This change improves clarity for developers integrating SSO in Next.js when referencing this example.
- Updated the redirectUrl from /sign-up/sso-callback to /sign-in/sso-callback.
> Update oauth-connections.mdx for Next.js setup

- docs/customization/themes.mdx
https://linear.app/clerk/issue/DOCS-10320/fix-documentation-error-in-clerk-themes-section
> (themes) fix order of code example tabs

- docs/organizations/create-orgs-for-users.mdx
- docs/organizations/create-roles-permissions.mdx
- docs/organizations/creator-role.mdx
- docs/organizations/default-role.mdx
- docs/organizations/force-organizations.mdx
- docs/organizations/invitations.mdx
- docs/organizations/manage-sso.mdx
- docs/organizations/metadata.mdx
- docs/organizations/org-slugs-in-urls.mdx
- docs/organizations/organization-workspaces.mdx
- docs/organizations/overview.mdx
- docs/organizations/roles-permissions.mdx
- docs/organizations/verified-domains.mdx
- docs/organizations/verify-user-permissions.mdx
https://clerk.com/docs/pr/2230
- We on the Growth Marketing front have been exploring ways to grow our LLM and Search Engine traffic, starting with Organizations as our guinea pig.  To be more specific, we noticed some opportunities to improve the seo`title` and `description` frontmatter across the `/docs/organizations/` section.
- CONTEXT: Our current docs pages for Organizations have limited visibility in search results. They don’t rank well for popular SEO terms that developers or decision-makers might use when looking for a B2B Organizations product (e.g., “multi-tenant auth,” “teams in SaaS apps,” “organization-level access control,” etc.). You can read the [experiment doc on Notion](https://www.notion.so/clerkdev/Content-Experiment-Orgs-1e02b9ab44fe809fb90dc460a284fa24?pvs=4).
- …
> Update SEO title and meta description for all 14 docs pages related to Orgs

- package-lock.json
- package.json
- scripts/build-docs.test.ts
- scripts/build-docs.ts
- scripts/lib/config.ts
- scripts/lib/redirects.ts
- We need the redirects data to properly redirect requests
- This parses in the files (checking they are valid json / jsonc)
- It optimizes the static redirects so users aren't making multiple hops
- It writes out the redirects in to the dist folder
> Include docs redirects in the generated docs artifact

- scripts/build-docs.test.ts
- scripts/build-docs.ts
- scripts/lib/config.ts
- scripts/lib/io.ts
- scripts/lib/redirects.ts
Building on top of https://github.com/clerk/clerk-docs/pull/2242 cuz that pr changes how the generated output artifact is managed
- We need a way to access the public images / assets that are stored in the clerk-docs repo from clerk.com
- copies the public folder in to dist/_public
> Copy over the public folder (images) in to the generated out build artifact

- package-lock.json
- package.json
- scripts/build-docs.test.ts
- scripts/build-docs.ts
- scripts/lib/getLastCommitDate.ts
- https://clerk-docs-git-nick-record-file-last-updated-date.clerkstage.dev/
- We need a way to get when a file was last updated, luckily this information is managed already for us fairly accurately by git
- Used a module called 'simple-git' to grab the datetime out and embed it in to the frontmatter in ISO format
> Include the last updated date from git in the generated out markdown frontmatter

- docs/manifest.json
- docs/references/backend/organization/create-organization-invitation-bulk.mdx
- https://clerk.com/docs/pr/2241
Introduces reference for `createOrganizationInvitationBulk` method, introduced on https://github.com/clerk/javascript/pull/5962
> chore(backend): Introduce reference for `createOrganizationInvitationBulk`

- docs/custom-flows/application-invitations.mdx
- Adjusting the sign up flow template to include the CAPTCHA div, to save one other error a user may run into as part of trying to utilize the template
- When attempting to copy/paste the example code, users may run into an issue with getting it to work. First, if the first name and last name are not enabled, it will error. Second, if a CAPTCHA is not included (in the cases where it is enabled for the sign up flow, which I believe it is by default), it will error. 
- The template has been modified to include the minor fix for CAPTCHA users.
> Adjust the SignUp flow template to include CAPTCHA div

- docs/customization/elements/examples/shadcn-ui.mdx
- docs/customization/elements/examples/sign-in.mdx
Using the example code from the docs produces a password input with text directions for email. This happens inside `<SignIn.Strategy name="password" ...`
- Updates the `CardTitle` to "Enter your password" and removes `CardDescription` as there isn't much more to say
- Removes extra space in tailwind class
> docs: extra space in tailwind class, SignIn elements with Shadcnui example password/email_code CardTitle mismatch

- docs/references/backend/organization/create-organization.mdx
- docs/references/backend/types/backend-organization.mdx
- docs/references/javascript/organization.mdx
- https://clerk.com/docs/pr/2277/references/backend/organization/create-organization.mdx
- https://clerk.com/docs/pr/2277/references/backend/types/backend-organization.mdx
- https://clerk.com/docs/pr/2277/references/javascript/organization.mdx
This clarifies that setting `max_allowed_memberships=0` means there is no limit on the number of memberships an organization can have. This prevents confusion when customers see the value 0 in the system after enabling unlimited membership.
Linear: https://linear.app/clerk/issue/DOCS-10419/document-that-max-allowed-memberships=0-means-unlimited-membership
Added documentation explaining that `max_allowed_memberships=0` indicates unlimited memberships for an organization. This helps users understand that 0 removes the membership limit rather than …
> Clarify that max_allowed_memberships=0 means unlimited membership

- docs/references/react-router/root-auth-loader.mdx
- https://clerk.com/docs/pr/2264/references/react-router/root-auth-loader
Context: https://github.com/clerk/javascript/issues/6012
Change `req` to `request` as that's what React Router uses.
> fix(react-router): Correct callback params

- docs/references/backend/organization/get-organization-membership-list.mdx
- package.json
- https://clerk.com/docs/pr/2272/references/backend/organization/get-organization-membership-list
Outdated `client.organization.getOrganizationMembershipList` params.
Updates the existing `client.organization.getOrganizationMembershipList` params to reflect the latest options.
> chore: Update getOrganizationMembershipList params

- scripts/build-docs.test.ts
- scripts/build-docs.ts
- scripts/lib/config.ts
- scripts/lib/getLastCommitDate.ts
- scripts/lib/plugins/insertFrontmatter.ts
- Since adding the getting the latest commit date on a file in the build script, the testing has gotten a lot slower as it initializes the tests each time, this results in the tests taking 30+ seconds to run which isn't great for local development
- I've made the git repo init optional so it only runs on one test, making it slow but the whole tests script back to around 2 seconds to run
> Drastically speed up build script tests

- docs/authentication/social-connections/x-twitter.mdx
- https://clerk.com/docs/pr/2281/authentication/social-connections/x-twitter
This PR adds a direct link to the official X/Twitter OAuth 2.0 Scopes documentation in the X/Twitter social connection guide. This update responds to a user request to make it easier for developers to review the available scopes when setting up their social connection.
Linear: https://linear.app/clerk/issue/DOCS-10412/feedback-for-authenticationsocial-connectionsx-twitter
- Added a new section about X/Twitter OAuth scopes (Step 4 in the guide) to provide more details and clarity
- Added a link to the [X/Twitter OAuth 2.0 Scopes documentation](https://docs.x.com/resources/fundamentals/authentication/oauth-2-0/authorization-code#scopes) within the configuration instructions.
- **Unrelated to this specific issue**: …
> Add more context and information around configuring scopes in Twitter social connection

- docs/webhooks/sync-data.mdx
- https://clerk.com/docs/pr/2287/webhooks/sync-data
- Removed `svix` installation instructions for `verifyWebhook()`
- https://github.com/clerk/javascript/pull/6059 refactors `verifyWebhook()` to manually verify the Clerk webhook and removes the need to install `svix`. Once that change is live customers no longer need to install `svix`
> chore: Remove svix installation instructions

- docs/organizations/roles-permissions.mdx
- https://clerk.com/docs/pr/2289/organizations/roles-permissions
This PR addresses feedback from a user regarding having to update the permissions in roles / permissions for admins to manage / read billing. There isn't much context to the ticket, [but here it is](https://app.plain.com/workspace/w_01GT53BQWV3DFW6ECTWZNQ1E9K/thread/th_01JV9M1KZCFWB4V4E3VE4CJ678/). So, had to dive a bit deeper into this one, and found that system permissions do include **Read billing** and **Manage billing**, as seen on the image below:
However, those aren't listed on the docs:
I figured that was where the misunderstanding came from the user. But, not 100% sure why they say they had to update the permission for those if they're already included in the system permissions. I may be missing something here, so …
> Added the billing system permissions for clarification

- docs/advanced-usage/using-proxies.mdx
- https://clerk.com/docs/pr/2248/advanced-usage/using-proxies
- 
- The proxy middleware example does not work properly as the proxy logic is not executed until `clerkMiddleware()` authenticates the request. This is unnecessary and causes issues in the handshake flow.
- 
The implementation has been improved to guarantee that proxy routes are always checked and handled before the Clerk middleware executes. This execution order is critical because it ensures that requests to the proxy path (__clerk) are correctly intercepted and routed to Clerk's Frontend API before any authentication middleware runs, preventing potential conflicts in request handling.
> fix: Frontend API proxy example for Next.js

- scripts/build-docs.test.ts
- scripts/build-docs.ts
- scripts/lib/config.ts
- scripts/lib/plugins/validateAndEmbedLinks.ts
- linking to `/docs/quickstart` will fail the validation in the build script as thats a special link not tied to a markdown file
- Added the link to the ignoredLinks in the build config so it doesn't fail on `docs/quickstart.mdx` not existing
> Add /docs/quickstart as ignored link

- docs/custom-flows/manage-sso-connections.mdx
- https://clerk.com/docs/pr/ss-docs-10519/custom-flows/manage-sso-connections
This PR clarifies the existence of a `normalizeProvider` function, used to remove the `oauth` prefix of each strategy to match with the provider field in the user's existing external accounts. There was nothing to fix in the code itself, as it was correct, but user may have missed the presence and importance of the `normalizeProvider` function. 
- Slack thread for context: https://clerkinc.slack.com/archives/C01QFRQNHSN/p1749618595504739
- Linear ticket: https://linear.app/clerk/issue/DOCS-10519/clarify-the-normalizeprovider-function-to-reverify-sso-connection-in
- Twitter user comment: https://x.com/divandcode/status/1932534112365260915
- Added extra explanation around the `normalizeProvider` function to …
> Clarify normalizeProvider function to reverify SSO connection in custom flow

- docs/authentication/configuration/email-sms-templates.mdx
- OTP SMS templates cannot be modified. To eliminate confusion for users, this should be noted in the docs.
- [DOCS-10391](https://linear.app/clerk/issue/DOCS-10391/add-call-out-in-docs-for-sms-template-customisation-otp-templates)
- Added a note to the SMS Template section under "Email & SMS Templates" page to inform users that these templates cannot be modified
> Added note about OTP SMS templates being non-customizable

- docs/customization/overview.mdx
- https://clerk.com/docs/pr/alexcarpenter-appearance-css-layer-name/customization/overview
- To support Tailwind CSS v4 usage, we've introduced a new property within the top level appearance prop to enable rendering clerk styles within a native CSS layer.
- SDK PR: https://github.com/clerk/javascript/pull/5552
-
> add `cssLayerName` property to `appearance` prop

- package.json
- scripts/build-docs.test.ts
- scripts/build-docs.ts
- scripts/lib/error-messages.ts
- scripts/lib/manifest.ts
- scripts/lib/plugins/validateAndEmbedLinks.ts
This changes how two warnings / errors are reported from the build script.
- When a page links to another page, and that page doesn't exist
Updated to match the warning message from the check-links.mjs script
- When a page is in the manifest.json but doesn't exist 
Updated so it doesn't close out after hitting the first broken link in the manifest
> validation / build script - clean up warnings reporting

- docs/quickstarts/nextjs.mdx
- https://clerk-docs-git-heat-grow-608-change-nextjs-quickstart-la-1fb1bc.clerkstage.dev/
- Matching dashboard PR: https://github.com/clerk/dashboard/pull/5876
- Draws attention to `<SignUpButton />` by using the Clerk brand color purple 
- Ensures Tailwind CSS is installed with Next.js app creation by adding `--yes` flag, which is required for styling changes to `<SignUpButton />` to be apparent. Tailwind CSS is not installed by default (see screenshot below)
- Updates to Next.js app router quickstart guide:
- Update app creation instructions to include `--yes` flag to install Tailwind CSS
- All app creation commands were tested and worked as expected
- Update `<SignUpButton/>` styling in layout.tsx code example to use Clerk brand purple
> Updates to Next.js app router quickstart guide

- docs/_partials/nextjs/update-globals-css.mdx
- docs/quickstarts/nextjs-pages-router.mdx
- docs/quickstarts/nextjs.mdx
https://linear.app/clerk/issue/DOCS-10539/update-quickstart-doc-to-include-csslayername-for-tailwind-4
To support Tailwind v4, users need to set `cssLayerName` in their ClerkProvider and then set that layer in their `globals.css` file.
⚠️  Related Dashboard PR: https://github.com/clerk/dashboard/pull/5919
> update nextjs quickstarts to support tailwind v4

- docs/authentication/enterprise-connections/overview.mdx
- docs/authentication/social-connections/overview.mdx
- docs/deployments/deploy-expo.mdx
This pr updates the `Allowlist for mobile SSO redirect` path as we moved them from `sso-connections` page to `native applications`
-
- 
-
> chore: Update Allowlist for mobile OAuth redirect url

- package-lock.json
- package.json
- scripts/link-typedoc.mjs
- When working on the typedoc generated content, need to link the output in to clerk-docs repo to test out the generated markdown
- Added a `typedoc:link` script the package.json making it easy to setup
> Add script to link typedoc generated markdown folder to clerk-docs

- docs/references/nextjs/connect-mcp-client.mdx
- https://clerk.com/docs/pr/ss-docs-10566/references/nextjs/connect-mcp-client
This small PR fixes a typo in the newly created MCP guide. 
Fixed typo!
> Fix typo in important callout MCP guide 

- docs/organizations/create-roles-permissions.mdx
- docs/organizations/roles-permissions.mdx
- https://clerk.com/docs/pr/ss-docs-10558/organizations/create-roles-permissions
- https://clerk.com/docs/pr/ss-docs-10558/organizations/roles-permissions#roles-and-permissions
This PR clarifies that custom roles and permissions are a paid add-on following user feedback and confusion. 
- Added a paid callout on the roles permissions page under Custom roles and Custom permissions
- Added a paid callout on the create custom roles and permissions page
> Add paid add-on callout for custom roles and permissions

- docs/quickstarts/nextjs.mdx
-
These tailwind v4 instructions regarding `cssLayerName` are only if the user is customizing their app using the `appearance` prop, which isn't necessary in the quickstart. Therefore, those instructions can be left in the appearance/customization docs, and left out of the quickstart.
⚠️  Related Dash PR: https://github.com/clerk/dashboard/pull/6003
> (nextjs) remove tailwind v4 instructions from quickstart

- docs/_partials/native-api-callout.mdx
- docs/deployments/deploy-chrome-extension.mdx
- docs/quickstarts/chrome-extension.mdx
- docs/quickstarts/expo.mdx
- docs/quickstarts/ios.mdx
- https://clerk.com/docs/pr/ss-docs-10550/deployments/deploy-chrome-extension
This PR adds a callout for Native API in the Chrome Extension SDK deployment docs, similar to what we have on the Quickstart page. 
- Added note callout for Native API in deployment docs for Chrome Extension SDK
> Add callout for Native API in Chrome Extension SDK docs

- docs/references/javascript/session.mdx
-  https://clerk.com/docs/pr/ss-docs-10556/references/javascript/session#session-verify-create-params
Linear: https://linear.app/clerk/issue/DOCS-10556/sessionverifycreateparams-are-incorrect
This PR fixes the incorrect types set for sessionVerifyCreateParams based on changes here: https://github.com/clerk/javascript/blob/d898eb71ca5ce76b213daa6448c3b989044f8e7f/packages/types/src/session.ts#L344. 
Replaced `status` type to `level` to align with the new type: `level: SessionVerificationLevel`.
> Fix incorrect types for sessionVerifyCreateParams from status to level

- docs/customization/variables.mdx
- scripts/build-docs.test.ts
- scripts/build-docs.ts
- scripts/lib/markdown.ts
- scripts/lib/plugins/validateUniqueHeadings.ts
- In this pr https://github.com/clerk/clerk-docs/pull/2347 a feature of markdown callouts, using custom ids to link to them is being used for the first time, the validation side of the docs script didn't extract that to validate against
- Added a traversal of the markdown to extract out any callout custom ids
> Support custom ids in callouts - validation script

- docs/quickstarts/react-router.mdx
we don't want to encourage passing the fallbackRedirectUrl props as users should use env vars instead.
also, its not necessary to pass these, as there isn't a case where a redirect url wouldn't be in the path because there is no `/sign-in` or `/sign-up` routes set up that could be directly visited.
> Update react router quickstart

- docs/_partials/authentication/microsoft/noauth.mdx
- https://clerk.com/docs/pr/ss-docs-10323/authentication/social-connections/microsoft#secure-your-app-against-the-n-o-auth-vulnerability
- https://clerk.com/docs/pr/ss-docs-10323/authentication/enterprise-connections/easie/microsoft
Linear ticket: https://linear.app/clerk/issue/DOCS-10323/xms-edov-call-out-regarding-portal
We occasionally get support tickets from developers confused by the warning message in the Azure portal regarding the `xms_edov` optional claim, thinking they misconfigured their Entra ID app. This PR clarifies that the warning is expected and safe to ignore, which should reduce unnecessary support tickets and confusion. 
Added a short note callout to the relevant section of the nOAuth setup guide, explaining that the warning is safe to ignore and the reasons behind the …
> Add callout about xms_edov Azure portal warning

- scripts/build-docs.ts
- scripts/lib/config.ts
- scripts/lib/error-messages.ts
- scripts/lib/io.ts
- scripts/lib/store.ts
- scripts/lib/tooltips.ts
-
- New `_tooltip` folder getting added
- Includes the new tooltips in the dist to be put up on the vercel cdn
- Validates that the tooltips are valid markdown and embed the `SDKLink` if need be
> Validate and copy over tooltips to dist

- docs/references/nextjs/clerk-middleware.mdx
- https://clerk.com/docs/pr/ss-docs-10591/references/nextjs/clerk-middleware
Linear: https://linear.app/clerk/issue/DOCS-10591/broken-link-in-documentation
A user spotted a broken link within the [Clerk Middleware page](https://clerk.com/docs/references/nextjs/clerk-middleware) in one of the callouts. Clicking on the link leads to a 404. After investigating, I noticed it was due to Next.js moving things around in their own docs, so I looked for the new place mentioning Next.js middleware. 
- Replaced the broken link with the new correct link within the Next.js docs. Worth noting that the old link was leading to the Pages router docs, so replaced it with the App router docs.
> Fix broken link in Clerk middleware docs

- docs/integrations/vercel-marketplace.mdx
-
-  Fixes the Vercel deploy link to not include our team slug
-
> chore: fix vercel deploy link

- docs/references/express/overview.mdx
- https://clerk.com/docs/pr/ss-docs-10460/references/express/overview#require-auth
Slack thread: https://clerkinc.slack.com/archives/C05GH6N5LLS/p1749057529795019?thread_ts=1749056599.729809&cid=C05GH6N5LLS
Linear: https://linear.app/clerk/issue/DOCS-10460/update-requireauth-helper-docs
This clarifies when and how the `requireAuth()` helper should be used in Express apps. We’ve seen user confusion ([Slack thread](https://clerkinc.slack.com/archives/C05GH6N5LLS/p1749057529795019?thread_ts=1749056599.729809&cid=C05GH6N5LLS)) about using `requireAuth()` for backend API routes - which it isn’t intended for since it redirects unauthenticated users to a sign-in page. This PR adds an explicit warning and clearer wording, and points users to the [cross-origin …
> Update requireAuth() helper docs

- .github/workflows/typedoc.yml
- Typedoc ci failing due to `clerk/javascript` repo pnpm version getting bumped to 10
- Upgraded version 10 to match
> Up the pnpm version for clerk/javascript to 10

- .github/workflows/typedoc.yml
-
- Fix the directory the ci, copies the typedocs to `./clerk-docs/clerk-typedocs/*` instead of `./clerk-docs/clerk-typedocs/docs/*`
- Uses the `clerk/javascript` short sha to make the branch in this pr, instead of the current date
- Doesn't attempt to create a new pr for that branch, if a pr for that branch already exists
> Typedoc ci improvements

- .github/workflows/migration.yml
- .gitignore
- flags.json
- package-lock.json
- package.json
- proposal-mapping.json
- proposal.md
- scripts/build-docs.test.ts
- scripts/build-docs.ts
- scripts/lib/config.ts
- scripts/lib/siteFlags.ts
- scripts/migration-assistant/README.md
- scripts/migration-assistant/generate-manifest.ts
- scripts/migration-assistant/map-content.ts
- vercel.json
sibling pr / blocked by: https://github.com/clerk/clerk/pull/1396
- https://clerk-git-nick-docs-migration.clerkstage.dev/docs/pr/nick-example-preview-proposal - built off the `nick/example-preview-proposal` which branches off this pr but enables the feature flags
- We need a robust solution for migrating the docs towards a content goal post
- A new `proposal.md` file, using markdown edit this file to reach for the sidebar that is desired
- A new `proposal-mapping.json` file, Take the generated `public/manifest.proposal.json` file and by hand generate this file that defines the migration expectations to get from the current docs to the new docs
- Added three new package.json scripts:
- `migration:generate-manifest` - Takes the `proposal.md` file and generates a Manifest proposal
- …
> Migration Assistant

- docs/custom-flows/email-password.mdx
-
This pull request updates the documentation for custom email/password flows to include Android-specific examples and Kotlin code snippets for both sign-up and sign-in processes. It enhances the guide by providing detailed implementations for Android developers using Jetpack Compose and ViewModel architecture.
* **Added Android as a tab option**: Updated the `<Tabs>` component to include "Android" alongside existing options like "Next.js" and "JavaScript" for both the sign-up and sign-in sections. [[1]](diffhunk://#diff-522941a131d76e7833ff1208d1e9483399972430714aa3e07df39916f12cb2eaL31-R31) [[2]](diffhunk://#diff-522941a131d76e7833ff1208d1e9483399972430714aa3e07df39916f12cb2eaL475-R570)
* **Added Kotlin example for sign-up flow**: Introduced a comprehensive Kotlin code snippet …
> [DO NOT MERGE] Add Android content to `email-password.mdx`

- docs/custom-flows/email-sms-otp.mdx
-
This pull request introduces several updates to improve developer experience and documentation for SMS OTP flows. The changes include enabling auto-formatting in the VS Code settings, expanding documentation for Android, and adding Kotlin examples for SMS OTP sign-up and sign-in flows.
* [`docs/custom-flows/email-sms-otp.mdx`](diffhunk://#diff-54dddc16ad9f565a0a496167e3484dc6ddef144497f6575ecb65af48704596cbL32-R32): Added Android as a supported platform in the `<Tabs>` component for both SMS OTP sign-up and sign-in guides. [[1]](diffhunk://#diff-54dddc16ad9f565a0a496167e3484dc6ddef144497f6575ecb65af48704596cbL32-R32) [[2]](diffhunk://#diff-54dddc16ad9f565a0a496167e3484dc6ddef144497f6575ecb65af48704596cbL318-R428)
* [`docs/custom-flows/email-sms-otp.mdx`](diffhunk://#diff-54dddc16ad9f565a …
> [ DO NOT MERGE ] Add Android content to `email-sms-otp.mdx`

- docs/custom-flows/forgot-password.mdx
This pull request introduces improvements to the development environment and expands the documentation for custom password reset flows. The most notable changes include enabling auto-formatting in VS Code settings and adding Kotlin examples for Android in the "Forgot Password" documentation.
* [`docs/custom-flows/forgot-password.mdx`](diffhunk://#diff-5896155cc3aa50dedacadfa6a76b72ddea8daecd3e96a6a34ea7fdafc808e245R189-R315): Added Kotlin examples for Android password reset flows, including composable UI components (`ForgotPasswordView` and `InputContent`) and a `ForgotPasswordViewModel` to handle state and API interactions. [[1]](diffhunk://#diff-5896155cc3aa50dedacadfa6a76b72ddea8daecd3e96a6a34ea7fdafc808e245R189-R315) [[2]](diffhunk://#diff-5896155cc3aa50dedacadfa6a76b72ddea8daecd3e96a6 …
> [DO NOT MERGE] Add Android samples to password reset flow

- docs/custom-flows/sign-out.mdx
This pull request updates the documentation for the `signOut()` function to include support for Android in the multi-session sign-out flow. It adds a new tab with Kotlin code examples for implementing the `signOut()` functionality on Android, alongside existing examples for other platforms.
* [`docs/custom-flows/sign-out.mdx`](diffhunk://#diff-0044d1373ef4af998d22e5fb4237b35e82ffb2e929e7715c7ac35f070821dd44L15-R15): Added "Android" to the list of tabs in the `signOut()` documentation, expanding platform coverage.
* [`docs/custom-flows/sign-out.mdx`](diffhunk://#diff-0044d1373ef4af998d22e5fb4237b35e82ffb2e929e7715c7ac35f070821dd44R118-R169): Included Kotlin code examples (`SignOutView.kt` and `SignOutViewModel.kt`) to demonstrate the implementation of the `signOut()` function on Android, …
> [DO NOT MERGE] Add android samples to `sign-out.mdx`

- scripts/build-docs.test.ts
- scripts/build-docs.ts
- scripts/lib/plugins/validateAndEmbedLinks.ts
- scripts/lib/utils/scopeHrefToSDK.ts
With https://github.com/clerk/clerk/pull/1377 merged no need to generate `~` instant redirect pages.
> Remove '~' dedicated instant redirect page

- scripts/migration-assistant/generate-manifest.ts
Fixes the href generation to include all levels of sidebar headings in the generated href.
> Docs Proposal manifest generation - fix href generation

- scripts/build-docs.test.ts
- scripts/build-docs.ts
- scripts/lib/plugins/insertFrontmatter.ts
Added `redirectpage`, `availableSdks` and `notAvailableSdks` to frontmatter for sdk scoped base redirect pages.
Added `sdkScoped`, `availableSdks`, `notAvailableSdks` and `activeSdk` to frontmatter for sdk scoped pages.
- Need additional information in the frontmatter for us to put in the page metadata for algolia to use (https://github.com/clerk/clerk/compare/main...algolia-crawler)
- Added additional context
> Add additional context to the frontmatter for the sdk scoped pages

- docs/components/checkout-button.mdx
- docs/components/plan-details-button.mdx
- docs/components/subscription-details-button.mdx
- https://clerk.com/docs/pr/nick-sdk-scope-beta-billing-components/nextjs/components/checkout-button
- https://clerk.com/docs/pr/nick-sdk-scope-beta-billing-components/nextjs/components/plan-details-button
- https://clerk.com/docs/pr/nick-sdk-scope-beta-billing-components/nextjs/components/subscription-details-button
- With https://github.com/clerk/clerk-docs/pull/2086 merged, all the components and hooks are now sdk scoped, but these new components aren't part of the pr
- SDK scoped these new beta components to react and nextjs as that is all they are supported in right now
> Sdk scope new beta billing components

- docs/references/ios/sign-in-with-apple.mdx
- https://clerk.com/docs/pr/mike-ios-components-sign-in-with-apple/references/ios/sign-in-with-apple
- Lets users know that they can stop at a certain point in the SignInWithApple guide if they are using prebuilt components.
- I'm labeling this as blocked since it **should not be merged** yet but can be reviewed.
> SignInWithApple updates for iOS components

- docs/manifest.json
- Moves the iOS Components within the iOS Guides in the manifest.
- Visually this shouldn't change anything, but it makes the location of this drop down consistent with others in the manifest/sidebar.
> put ios components dropdown within guides

- docs/customization/themes.mdx
- https://clerk.com/docs/pr/alexcarpenter-shadcn-theme-note/customization/themes#shadcn-theme
- Adds note to shadcn theme usage about importing the CSS file to resolve Tailwind picking up the classes used within the theme.
-
> [do not merge] Add shadcn theme note about css import

- docs/users/creating-users.mdx
- docs/users/deleting-users.mdx
- https://clerk.com/docs/pr/ss-docs-10671/users/deleting-users
- https://clerk.com/docs/pr/ss-docs-10671/users/creating-users
This fixes a misleading label in the **Using the Backend API** section of the [Deleting Users](https://clerk.com/docs/users/deleting-users) page. The tab group was incorrectly titled "Frontend SDKs," which didn't align with the tab of the code example. Noticed this was an issue for the [Creating Users](https://clerk.com/docs/users/creating-users) page too. 
The change was prompted by user feedback who spotted the issue.
- Updated the bullet point to say "Backend SDK" rather than "Frontend SDKs.." in the Deleting Users and Creating Users pages
> Fix incorrect tab label from "Frontend SDKs" to "Backend SDK" 

- docs/machine-auth/m2m-tokens.mdx
- https://clerk.com/docs/pr/rob-fix-m2m-docs/machine-auth/m2m-tokens#creating-m2-m-tokens
- Fixes incorrect method when creating m2m tokens
- Replaced `m2m.create()` with `m2m.createToken()`
> Fix incorrect m2m create method

- docs/components/authentication/task-choose-organization.mdx
- https://clerk.com/docs/pr/nick-add-sdk-scoping-for-choose-organization/nextjs/components/authentication/task-choose-organization
- The new `<TaskChooseOrganization />` component is showing up as available in all sdks
- Checked with all our javascript based sdks on the latest sdk version and added sdks that the component is importable in
> Add sdk scoping for `<TaskChooseOrganization />`

- docs/billing/events-webhooks.mdx
-
Fixes typo for subscription item past due webhook name
Updated webhook name from `subscriptionItem.past_due` to `subscriptionItem.pastDue`
> fix: subscriptionItem.pastDue name update

- docs/quickstarts/javascript.mdx
`Clerk` needs to be uppercase for <script> loaded library
The code as currently presented doesn't work
Fixes the typo for the variable name
> Fix typo in javascript.mdx

- docs/custom-flows/overview.mdx
- https://clerk.com/docs/pr/laura-patch-custom-flow-task-instructions/custom-flows/overview
Update custom flows mentions that after sign-in or sign-up, `setActive({ navigate })` should be used to check against pending session tasks.
> chore(tasks): Refer to `setActive({ navigate })` for checking pending tasks on custom flows

- docs/guides/force-token-refresh.mdx
-
A user reported that skipCache true is not available server-side but our docs say allude to that being true
https://x.com/strehldev/status/1963607291816542654
Updates the docs appropriately
> skipCache true not available server-side

- scripts/build-docs.test.ts
- The tests to list the output files and ensure they are what we expect can be flaky, as the glob() function doesn't always return the array in the same order
- sorts the glob array output before returning it
> build script tests - Sort the files we list to ensure consistent array

- docs/machine-auth/m2m-tokens.mdx
🔍 [Preview linking to section](https://clerk.com/docs/pr/clarify-machine-scopes/machine-auth/m2m-tokens#creating-machines)
There's an important distinction on how machine scopes are applied to m2m tokens.  Notably, they are not applied to m2m tokens which have already been created, but only new tokens.
Adds an Important callout in the section where we describe the process for creating a machine (and adding its scopes).
> Clarify how Machine scope changes are applied to tokens.

- scripts/build-docs.test.ts
- scripts/build-docs.ts
Need to make changes to the frontmatter so the site can include information in the meta tags for Algolia to pick up, so we can improve our in-site search.
- Adds `sdkScoped: "false"` to non sdk scoped pages
- Adds `canonical: ...` to non sdk scoped pages to be consistent with sdk scoped pages
- Adds `search: exclude: true` for redirect pages to stop them being indexed
> Always embed the canonical link in the frontmatter, disable search for the redirect pages

- docs/manifest.json
- https://clerk.com/docs/pr/ss-docs-10978/reference/nextjs/overview
Linear: https://linear.app/clerk/issue/DOCS-10978/missing-beta-tags-on-billing-hooks
The billing hooks that are in beta don't have beta tags next to them. This PR adds them. 
- Adds beta tags to billing hooks
Before:
After:
> Add beta tags to billing hooks

- docs/guides/development/webhooks/inngest.mdx
-
With the new restructure, the Inngest guide isn't on the sidebar, as there are plans to revamp/ restructure it. However, while working on other things, I noticed some links were broken in the guide, and we probably want those fixed for any users stumbling upon the guide. 
Fixed the links leading to 404.
> Fix 404 links on Inngest guide

- docs/reference/components/overview.mdx
-
This [PR](https://github.com/clerk/clerk-docs/pull/2633) made a change to the Secured by Clerk section of the iOS components overview. But that section also exists in the Components overview page. This PR is to make the same changes to the section. 
Copy / pasted the section.
> Bring consistency to Secured by Clerk branding message

- docs/manifest.json
- docs/reference/backend/invitations/create-invitation-bulk.mdx
- docs/reference/backend/invitations/create-invitation.mdx
- https://clerk.com/docs/pr/ss-docs-10973/reference/backend/invitations/create-invitation-bulk
In the Clerk Backend API Reference, there is a route to create multiple invitations in bulk, and the wrapper method (`createInvitationBulk`) for that route is also being documented in the `javascript` repo [here](https://github.com/clerk/javascript/blob/main/packages/backend/src/api/endpoints/InvitationApi.ts). However, we do not have it in our docs - this PR documents the missing method within our JS Backend SDK. 
- Adds the `createInvitationBulk` method in JS Backend SDK. 
**Note:** While doing this work, @manovotny and I noticed the `templateSlug` and `expiresInDays` properties were missing from the `createInvitation` method while being documents in both the `javascript` repo and the Backend …
> Document missing createInvitationBulk method on JS Backend SDK 
