- src/pages/quickstarts/_meta.json
- src/pages/quickstarts/expo.mdx
This adds Expo quickstart to show basic examples of:
- Using the app
- Adding a custom sign in flow with email & passwords and verification codes.
- OAuth flows with transfers.
> Adds Expo Quickstart

- src/components/Cards.tsx
- src/components/Images.tsx
- src/pages/index.mdx
- src/pages/quickstarts.mdx
- src/pages/quickstarts/expo.mdx
- src/pages/quickstarts/nextjs/app-router.mdx
- src/pages/quickstarts/nextjs/stable.mdx
- src/pages/quickstarts/react.mdx
- src/pages/sdk.mdx
Added a Card that can be used anywhere for CTAs
Added the cards to all places where we are using CTAs
> Add Cards for CTAs

- src/pages/index.mdx
- src/pages/quickstarts.mdx
- src/pages/quickstarts/_meta.json
- src/pages/quickstarts/redwood.mdx
Add Redwood quickstart and cards to the quickstart.
> Add Redwood quickstart

- src/pages/components/authentication/sign-up.mdx
Instead of SigIn prefix SignUp could be better
> fix: solve typo on SignUp component

- src/pages/components/authentication/user-button.mdx
- src/pages/components/authentication/user-profile.mdx
- src/pages/components/organization-management/create-organization.mdx
- src/pages/components/organization-management/organization-profile.mdx
- src/pages/components/organization-management/organization-switcher.mdx
- src/pages/components/user-management/clerk-loaded.mdx
- src/pages/components/user-management/clerk-loading.mdx
- src/pages/components/user-management/multi-session.mdx
- src/pages/components/user-management/redirect-to-signin.mdx
- src/pages/components/user-management/redirect-to-signup.mdx
- src/pages/components/user-management/redirect-to-userprofile.mdx
- src/pages/components/user-management/signed-in.mdx
- src/pages/components/user-management/signed-out.mdx
- src/pages/quickstarts/_meta.json
- src/pages/quickstarts/remix.mdx
> Remix Guide

- src/pages/hooks/authentication/use-sign-up.mdx
- missing setActive in signup.tsx code
- heading typo
> Fix useSignUp typo

- src/pages/quickstarts/nextjs/app-router.mdx
> Fix typo in next app-router page

- README.md
A minor grammatical and punctuation fix. 🙏
> fix: README wording

- src/pages/security/_meta.json
- src/pages/security/csrf-protection.mdx
- src/pages/security/fixation-protection.mdx
- src/pages/security/password-protection-and-rules.mdx
- src/pages/security/security-overview.mdx
- src/pages/security/vulnerability-disclosure-policy.mdx
- src/pages/security/xss-leak-protection.mdx
Adds
- Security Overview
- Vulnerability disclosure policy
- XSS leak protection
- CSRF protection
- Fixation protection
- Password protection and rules
> Add Security Pages

- src/pages/quickstarts/backend/_meta.json
- src/pages/quickstarts/backend/fastify.mdx
- src/pages/quickstarts/clerk-idp.mdx
- src/pages/quickstarts/frontend/react.mdx
- src/pages/quickstarts/full-stack/gatsby.mdx
- src/pages/quickstarts/full-stack/redwood.mdx
- src/pages/quickstarts/full-stack/remix.mdx
- src/pages/quickstarts/native/expo.mdx
- Adds Fastify
- Fix quickstarts to use steps.
> Add Fastify / Fix quickstarts

- src/pages/migrations-deployments/migrate-from/_meta.json
- src/pages/migrations-deployments/migrate-from/firebase.mdx
> Firebase migration

- src/pages/reference-react/customization/localization.mdx
> feat(localization): add jaJP

- src/pages/migrations-deployments/deployment-guides/vercel.mdx
- src/pages/users/authentication-providers/apple.mdx
- src/pages/users/authentication-providers/atlassian.mdx
- src/pages/users/authentication-providers/bitbucket.mdx
- src/pages/users/authentication-providers/box.mdx
- src/pages/users/authentication-providers/coinbase.mdx
- src/pages/users/authentication-providers/discord.mdx
- src/pages/users/authentication-providers/dropbox.mdx
- src/pages/users/authentication-providers/facebook.mdx
- src/pages/users/authentication-providers/github.mdx
- src/pages/users/authentication-providers/gitlab.mdx
- src/pages/users/authentication-providers/google.mdx
- src/pages/users/authentication-providers/hubspot.mdx
- src/pages/users/authentication-providers/line.mdx
- src/pages/users/authentication-providers/linear.mdx
- src/pages/users/authentication-providers/linkedin.mdx
- src/pages/users/authentication-providers/microsoft.mdx
- src/pages/users/authentication-providers/notion.mdx
- src/pages/users/authentication-providers/slack.mdx
- src/pages/users/authentication-providers/spotify.mdx
- src/pages/users/authentication-providers/tiktok.mdx
- src/pages/users/authentication-providers/twitch.mdx
- src/pages/users/authentication-providers/twitter.mdx
- src/pages/users/authentication-providers/xero.mdx
This PR replaces various links to the production site to the relative links for the beta site
> chore: replace production links with beta links

- src/pages/reference-js/_meta.json
- src/pages/reference-js/authentication/sign-in.mdx
This PR is the initial idea for setting up a SignIn component docs page for ClerkJS' JavaScript package.
Preview: https://clerk-docs-git-clerk-js-quickstart.clerkpreview.com/reference-js/authentication/sign-in
> ClerkJS JavaScript SignIn Component Docs

- src/pages/reference-js/authentication/_meta.json
- src/pages/reference-js/authentication/user-profile.mdx
- src/pages/reference-react/authentication/user-profile.mdx
This PR adds the ClerkJS UserProfile component reference docs, based off the SignUp docs
> docs: add user profile ClerkJS reference page

- src/pages/reference-js/authentication/_meta.json
- src/pages/reference-js/authentication/sign-in.mdx
- src/pages/reference-js/authentication/sign-up.mdx
- src/pages/reference-js/authentication/user-profile.mdx
- src/pages/reference-react/authentication/sign-up.mdx
- src/pages/reference-react/authentication/user-profile.mdx
This PR adds the ClerkJS SignUp component reference docs, based off the SignIn docs
> docs: add clerk-js signup component reference docs

- src/pages/reference-js/authentication/sign-in.mdx
- src/pages/reference-js/authentication/sign-up.mdx
- src/pages/reference-js/authentication/user-profile.mdx
- src/pages/reference-js/organization-management/_meta.json
- src/pages/reference-js/organization-management/create-organization.mdx
- src/pages/reference-js/organization-management/organization-profile.mdx
- src/pages/reference-react/organization-management/create-organization.mdx
> Create Organization Reference Docs

- src/pages/reference-js/authentication/_meta.json
- src/pages/reference-js/authentication/user-button.mdx
- src/pages/reference-react/authentication/user-button.mdx
This PR documents the ClerkJS UserButton docs
> docs: add ClerkJS UserButton docs

- src/pages/reference-js/authentication/_meta.json
- src/pages/reference-js/authentication/user-button.mdx
- src/pages/reference-js/organization-management/organization-switcher.mdx
- src/pages/reference-react/authentication/user-button.mdx
- src/pages/reference-react/organization-management/organization-switcher.mdx
This PR:
- Updates the React OrganizationSwitcher docs to add missing props and remove incorrect properties
- Adds ClerkJS OrganizationSwitcher docs
>  docs: add ClerkJS OrganizationSwitcher docs

- src/pages/reference-js/_meta.json
- src/pages/reference-js/organization-invitation.mdx
- src/pages/reference-js/organization-membership.mdx
- src/pages/reference-js/organization/invitations.mdx
- src/pages/reference-js/organization/members.mdx
- src/pages/reference-js/types/_meta.json
- src/pages/reference-js/types/public-user-data.mdx
This PR adds:
- OrganizationMembership
- PublicUserData
Docs
> ClerkJS Add Organization Membership Doc

- src/pages/reference-js/clerk/_meta.json
- src/pages/reference-js/clerk/build-urls.mdx
This PR adds the build URL methods from the ClerkJS class
> Add ClerkJS build URL methods

- src/pages/reference-js/clerk/_meta.json
- src/pages/reference-js/clerk/handle-navigation.mdx
- src/pages/reference-js/types/_meta.json
- src/pages/reference-js/types/magic-link-error.mdx
This PR documents the `handle` prefixed methods for the ClerkJS class
> ClerkJS Handle Navigation Docs

- src/pages/reference-js/clerk/_meta.json
- src/pages/reference-js/clerk/session-methods.mdx
This PR documents the `setSession` and `setActive` methods
> ClerkJS Session Management

- src/pages/reference-js/_meta.json
- src/pages/reference-js/email-address/_meta.json
- src/pages/reference-js/email-address/email-address.mdx
- src/pages/reference-js/email-address/verification.mdx
- src/pages/reference-js/sign-in/first-factor.mdx
This PR documents the `EmailAddress` class via reference docs
> EmailAddress Class Docs

- src/pages/reference-js/_meta.json
- src/pages/reference-js/phone-number/_meta.json
- src/pages/reference-js/phone-number/phone-number.mdx
- src/pages/reference-js/phone-number/second-factor.mdx
- src/pages/reference-js/phone-number/verification.mdx
This PR introduces the first docs for the `PhoneNumber` class reference pages
> PhoneNumber Reference Docs

- src/pages/reference-js/_meta.json
- src/pages/reference-js/session-with-activities.mdx
This PR adds reference docs for the SessionActivites class
> Add reference docs for SessionActivities

- src/pages/reference-js/_meta.json
- src/pages/reference-js/web3-wallet/_meta.json
- src/pages/reference-js/web3-wallet/verification.mdx
- src/pages/reference-js/web3-wallet/web3-wallet.mdx
This PR writes the initial reference docs for the Web3Wallet class
> Document the Web3Wallet class

- src/pages/reference-js/_meta.json
- src/pages/reference-js/types/_meta.json
- src/pages/reference-js/types/deleted-object.mdx
- src/pages/reference-js/user/_meta.json
- src/pages/reference-js/user/create-metadata.mdx
- src/pages/reference-js/user/password-management.mdx
- src/pages/reference-js/user/totp.mdx
- src/pages/reference-js/user/user.mdx
This PR introduces reference documentation for the User Class
> Document User Class Reference

- src/pages/reference-js/overview.mdx
This PR introduces an updated ClerkJS overview doc
> docs: improve the ClerkJS overview doc

- src/pages/quickstarts/frontend/_meta.json
- src/pages/quickstarts/frontend/javascript.mdx
This PR adds an initial Clerk JavaScript Quickstart guide
> docs: initial Clerk JavaScript quickstart guide

- docs/manifest.json
Updates the "frontend API" and "backend API" links to their respective external links.
> docs: update "frontend API" and "backend API" links

- docs/components/overview.mdx
- docs/index.mdx
- docs/integrations/overview.mdx
- docs/quickstarts/overview.mdx
- docs/references/overview.mdx
- docs/references/react/overview.mdx
- scripts/check-links.mjs
- Update metadata for a number of the overview pages
- Improve output of the broken link checker
> feat: add overview pages and tweak content

- docs/authentication/social-connections/oauth.mdx
- docs/components/control/authenticate-with-callback.mdx
- docs/components/control/clerk-loaded.mdx
- docs/components/control/multi-session.mdx
- docs/components/unstyled/sign-out-button.mdx
- docs/integrations/analytics/google-analytics.mdx
- docs/manifest.json
- docs/reference-platform/rate-limits.mdx
- docs/references/react/use-organization-list.mdx
- docs/references/react/use-organization.mdx
- docs/references/react/use-organizations.mdx
- Adds some missing pages
- Remove unnecessary horizontal rules
- Add page for `<SignOutButton />`
- Tweak navigation data
> feat(mdx): more docs updates

- docs/account-portal/overview.mdx
- docs/authentication/public-user-data.mdx
- docs/authentication/saml-at-clerk.mdx
- docs/authentication/set-up-your-application.mdx
- docs/authentication/using-clerk-hosted-pages.mdx
- docs/build-frontend-first/elevating-permissions.mdx
- docs/build-frontend-first/handling-errors.mdx
- docs/build-frontend-first/session-authentication.mdx
- docs/build-frontend-first/what-is-a-frontend-api.mdx
- docs/components/authentication/sign-in.mdx
- docs/manifest.json
- docs/references/javascript/clerk/clerk.mdx
- docs/references/javascript/organization/organization.mdx
- docs/references/javascript/sign-up/sign-up.mdx
- docs/references/javascript/sign-up/verification.mdx
- docs/references/react-native/overview.mdx
- docs/references/remix/overview.mdx
- docs/users/build-your-own-ui.mdx
- docs/users/web3-wallets.mdx
Maps remaining pages from our old system, and removes a number of empty pages. Some of these pages will likely end up being removed in the near future, but for now we'll continue serving the content until we have suitable replacements.
> docs: map remaining pages, remove some empty pages

- docs/references/javascript/clerk/build-urls.mdx
Small fix for spacing around a link.
> Fix spacing around link

- docs/manifest.json
Found two pages that 404 because the files no longer exist, but they were existent in the nav. Removed these pages from the nav.
> remove nonexistent pages from nav

- docs/manifest.json
- docs/quickstarts/nextjs.mdx
This isn't technically launched yet, so changing the wording until it is.
> chore: remove AP references

- .github/workflows/preview.yml
Hopefully this is the last time. Point back at production for previews.
> Revert "fix: point previews at assembly branch for now (#198)"

- docs/quickstarts/nextjs.mdx
Fixes optional catch all route for sign in
> Fix the optional catch all route

- docs/authentication/configuration/session-options.mdx
- docs/authentication/configuration/sign-in-options.mdx
- docs/authentication/configuration/sign-up-options.mdx
when using squoosh to optimize images, they were changed from png's to jpg's... and we missed that.
> update image paths

- docs/authentication/configuration/sign-in-options.mdx
- docs/authentication/configuration/sign-up-options.mdx
This PR
- updates an image path for /sign-in-options 
- adds direct links to dashboard references
> update sign up options

- docs/quickstarts/expo.mdx
- Fixed a typo in the hooks filepath
- Fixed a minor typo
> Fixed minor typos in docs

- docs/authentication/social-connections/slack.mdx
- docs/components/clerk-provider.mdx
- docs/quickstarts/nextjs.mdx
- docs/references/react/use-clerk.mdx
This resolves
DOCS-306 DOCS-307 DOCS-308 DOCS-309
> Resolves a few minor issues with docs

- docs/users/sync-data.mdx
- Clarified api/ for Page Router and app/ for App Router
- Updated App Router example to remove unused imports, improve flow
> Updated information and code for App Router

- docs/references/react/use-organization-list.mdx
This PR:
- replaces the content from sanity
- Add new examples that use the new API of useOrganizationList
- Adds `Parameters` and `Returns` section that explain in detail what each property does
> update: Include docs for the new API of useOrganizationList

- docs/users/metadata.mdx
This PR
- removes unnecessary imports
- fixes grammar and typos and other copy-related things
> Clean up tech debt and copy, and add links to 'Metadata' page

- README.md
Fixed spelling mistake on the README, changing repostiroy to correct spelling
> Fix spelling mistake on README.md

- docs/authentication/configuration/email-options.mdx
let's try this one more time :D
> fix broken link raised by our broken link checker

- docs/custom-flows/use-sign-up.mdx
/docs/custom-flows/use-sign-up
This PR
https://github.com/clerkinc/clerk-docs/assets/98043211/d3fce135-02e1-4d84-ac95-f10249c31dbb
> Migrate use-sign-up from Sanity to MDX

- docs/custom-flows/mfa.mdx
/docs/custom-flows/multifactor
This PR
https://github.com/clerkinc/clerk-docs/assets/98043211/de69ca6a-e7ed-4c0d-ab23-27660fec6fe8
> Migrate 'Multifactor' from Sanity to MDX

- docs/references/nextjs/route-handlers.mdx
Simple edit -- added callout to Route Handlers with link.
> Updated Route Handlers with callout and link to clerkClient docs.

- docs/references/nextjs/auth.mdx
API route handlers in nextjs for app router are in `route` files 
Thanks in advance for taking a look (:
> Align with nextJS api route handler docs

- docs/references/nextjs/auth-middleware.mdx
> Fix a small typo

- docs/references/nextjs/authentication-object.mdx
This PR
- adds the missing description to frontmatter
- migrates table from component to MDX
- fixes broken codeblock by assigning a language
> fix broken codeblock; migrate table from component to mdx

- docs/custom-flows/saml-connections.mdx
/docs/custom-flows/saml-connections
This PR
https://github.com/clerkinc/clerk-docs/assets/98043211/447f6af9-ac51-4133-a773-1df6d1d7090c
> Migrate saml-connections from Sanity to MDX

- docs/authentication/configuration/restrictions.mdx
> Update restrictions with email subaddress blocking

- docs/references/nodejs/troubleshooting.mdx
This PR migrates this page from Sanity to MDX
🔎 [Old page](https://clerk.com/troubleshooting/overview)
> Migrate troubleshooting from Sanity to MDX

- docs/quickstarts/fastify.mdx
- docs/references/javascript/clerk/clerk.mdx
- docs/references/javascript/clerk/handle-navigation.mdx
- docs/references/javascript/clerk/organization-methods.mdx
- docs/references/javascript/clerk/redirect-methods.mdx
- docs/references/javascript/clerk/session-methods.mdx
- docs/references/javascript/organization-invitation.mdx
- docs/references/javascript/organization-membership.mdx
- docs/references/javascript/organization/invitations.mdx
- docs/references/javascript/organization/members.mdx
- docs/references/javascript/organization/organization.mdx
- docs/references/javascript/overview.mdx
- docs/references/javascript/user/create-metadata.mdx
- docs/references/javascript/user/password-management.mdx
- docs/references/javascript/user/totp.mdx
- docs/references/javascript/user/user.mdx
This PR
- migrates components to markdown tables
- updates deprecated types
- updates parameters to show as optional or required
- adds links to references where necessary
- typical clean up / consistency thingssss
> clean up /javascript/organization pages

- docs/references/javascript/session-with-activities.mdx
- docs/references/javascript/session.mdx
This PR
- migrates components to markdown tables
- updates parameters to show as optional or required
- adds links to references where necessary
- typical clean up / consistency thingssss
> clean up /javascript session pages

- docs/components/unstyled/sign-in-button.mdx
- docs/components/unstyled/sign-up-button.mdx
Added info on using the components as modals.
> Added 'mode' prop to SignInButton and SignUpButton component docs

- docs/references/javascript/client.mdx
- docs/references/javascript/external-account.mdx
- docs/references/javascript/verification.mdx
Cleaning up the JavaScript reference docs.
This PR
- migrates components to markdown tables
- adds links to references where necessary
- typical clean up / consistency thingssss
> clean up client, external account, verification

- docs/references/javascript/sign-up/authenticate-with.mdx
- docs/references/javascript/sign-up/email-verification.mdx
- docs/references/javascript/sign-up/phone-verification.mdx
- docs/references/javascript/sign-up/sign-up.mdx
- docs/references/javascript/sign-up/verification.mdx
- docs/references/javascript/sign-up/web3-verification.mdx
- docs/references/javascript/verification.mdx
Cleaning up the JavaScript reference docs.
This PR
migrates components to markdown tables
adds links to references where necessary
typical clean up / consistency thingssss
> clean up /signup pages for javascript reference docs

- docs/components/user/user-button.mdx
This example had the exact same code as the Pages Router example. This PR fixes the App Router code example.
> DOCS-389 solved code duplication: App Router vs. Pages Router example

- docs/custom-flows/sign-out.mdx
Added a link to the signOut() function and updated the example to be typical of usage.
> Update Custom Flow Sign Out doc

- docs/backend-requests/making/jwt-templates.mdx
The following patch documents the newly-added capability of the JWT Template language: conditional expressions using the `||` operator.
> feat: JWT Template conditional expressions

- docs/references/nextjs/route-handlers.mdx
Updating the file syntax to match NextJS's [file convention](https://nextjs.org/docs/app/building-your-application/routing/route-handlers)
> docs: updating route handler file convention

- CONTRIBUTING.md
Adds a note to guide internal folks on how to preview changes locally.
> chore: Add note about local preview to the contributing guide

- README.md
- docs/manifest.json
- docs/troubleshooting/overview.mdx
- docs/troubleshooting/script-loading.mdx
This is a PR in response to https://github.com/clerkinc/javascript/issues/1643 - I'm open to feedback to further improve the doc or clarify things. This is probably the bare minimum version of that doc.
> feat: Add 'Script loading' troubleshooting doc

- docs/components/customization/localization.mdx
Update information and example for Localizations
> Improve Localization docs, add info on contributing

- docs/manifest.json
- docs/references/backend/overview.mdx
- docs/references/backend/sessions/authenticate-request.mdx
Added doc page, added to overview page and added to doc manifest to document authenticateRequest()
> Added doc page for authenicateRequest()

- .github/workflows/preview.yml
- CONTRIBUTING.md
- README.md
- docs/advanced-usage/satellite-domains.mdx
- docs/backend-requests/handling/go.mdx
- docs/components/customization/localization.mdx
- docs/integrations/databases/supabase.mdx
- docs/manifest.json
- docs/organizations/overview.mdx
- docs/quickstarts/fastify.mdx
- docs/quickstarts/nextjs.mdx
- docs/references/backend/overview.mdx
- docs/references/go/overview.mdx
- docs/references/go/verifying-sessions.mdx
- docs/references/react/use-organization.mdx
- docs/testing/cypress.mdx
- docs/users/overview.mdx
Recently, we updated our Clerk GitHub slug from 'clerkinc' to 'clerk'
This PR updates all instances of 'clerkinc' to 'clerk'.
> Update 'clerkinc' references to 'clerk'

- docs/custom-flows/email-password.mdx
Changed pages:
https://docs-preview-452.clerkpreview.com/docs/custom-flows/email-password
> Updated Signin and Signup examples, moved App Router first

- STYLEGUIDE.md
> update state styles in STYLEGUIDE.md

- docs/references/nextjs/custom-signup-signin-pages.mdx
Fix copy to reflect correct component that is referenced (SignIn instead of SignUp)
> DOCS-583 Fix incorrect component reference

- docs/components/customization/localization.mdx
> DOCS-550 add callout about localization being experimental

- docs/quickstarts/expo.mdx
The current expo example for sign up doesn't include the first and last name which  makes the sign up process not work, so i added them.
> Fix Expo SIgn Up Example

- docs/references/backend/user/update-user.mdx
Corrected a word that could potentially confuse a reader.
> Changed the word "replays" to "replace"

- docs/references/nextjs/custom-signup-signin-pages.mdx
There was a typo in the Custom SignUp/SignIn docs
> Typo in docs fixed.

- docs/references/react/use-user.mdx
[DOCS-624](https://linear.app/clerk/issue/DOCS-624/%F0%9F%98%A2-feedback-for-referencesreactuse-user) is a user feedback ticket that states "what is the shape of user? More type hints please."
This PR adds references to the `User` object.
And thank you to Ali for leaving the feedback that incited these changes 💙
> DOCS-624 clarify on the shape of user data (add reference to the User object)

- docs/manifest.json
- docs/quickstarts/nextjs.mdx
* Add deployment step to Next.js Quickstart
* And swaps 'deployment & migrations' in navigation to reflect ordering of content in that section
**Now**
**Before**
> Add deployment step to Next.js Quickstart

- docs/manifest.json
- docs/references/javascript/organization-membership-request.mdx
- docs/references/javascript/organization/membership-request.mdx
https://docs-preview-516.clerkpreview.com/docs/references/javascript/organization-membership-request
https://docs-preview-516.clerkpreview.com/docs/references/javascript/organization/membership-request
> feat: Introduce Organization Membership Requests

- docs/deployments/migrate-overview.mdx
Some minor editorial changes to the migration docs.
> chore: Edits to the updated migration docs

- docs/security/programmatically-lock-user-accounts.mdx
- docs/security/unlock-user-accounts.mdx
This looks like it was a little typo, fixing it on up!
> chore: Typo fixes

- docs/quickstarts/nextjs.mdx
Align Next.js quickstart to account for two commits that were pushed to the app router starter:
- https://github.com/clerk/clerk-nextjs-app-quickstart/commit/f0145454a815d889cff886a153afd09abe971405
- https://github.com/clerk/clerk-nextjs-app-quickstart/commit/dcf2c03d01988ba0f593c177a8680e8a771eaaf0
> chore: Update Next.js quickstart to align with App router starter

- docs/organizations/creating-organizations.mdx
- docs/organizations/inviting-users.mdx
- docs/organizations/managing-roles.mdx
- docs/organizations/permissions-show-hide-content.mdx
- docs/references/backend/organization/create-organization-invitation.mdx
- docs/references/backend/organization/create-organization-membership.mdx
- docs/references/backend/organization/update-organization-membership.mdx
- docs/references/javascript/organization-invitation.mdx
- docs/references/javascript/organization-membership.mdx
- docs/references/javascript/organization/invitations.mdx
- docs/references/javascript/organization/members.mdx
- docs/references/react/use-organization.mdx
- docs/references/react/use-organizations.mdx
What do y'all think? Need to update more than just this wording.
> Update all the references to `basic_members`, `guest_members` and `admin`/Administrators to be in line with Roles

- docs/users/web3.mdx
added information for adding metamask extension for web3 login flow
> added info that user should download meta mask

- docs/guides/basic-rbac.mdx
This pull request addresses the spelling errors found in the `Implement basic Role Based Access Control (RBAC) with metadata` section of the Clerk documentation.
fixes: #586
> Fixed Spelling Mistake in Clerk Docs - RBAC Section

- docs/integrations/webhooks.mdx
> fix typo "Orgnaization"

- docs/manifest.json
- docs/upgrade-guides/long-term-support.mdx
I don't think we need a description here, it is what it is!
> Add long term support policy

- docs/references/nextjs/auth-middleware.mdx
`apiRoutes` and `publicRoutes` both had incorrect formatting on text that should be code snippets
> fix code snippet

- docs/references/react/use-clerk.mdx
[DOCS-5160](https://linear.app/clerk/issue/DOCS-5160/feedback-for-referencesreactuse-clerk) is a user feedback ticket that expressed that the callout is unclear: "Could you maybe expand a little bit on that and in the best case show an example?"
@jescalan and I decided that this text is more clear.
> DOCS-5160 update callout to be more clear

- docs/guides/force-organizations.mdx
> feat: Add usage example of SyncActiveOrganization and minor fixes in snippets

- docs/organizations/creator-role.mdx
https://discord.com/channels/856971667393609759/858011152133783584/1194440265142911148
> Typo fixed found by Discord member

- docs/custom-flows/email-sms-otp.mdx
Tab instances on this page weren't syncing. They needed the `type` prop.
> sync tab instances for this page

- docs/components/user/user-button.mdx
added closing tag to the **SignInButton** JSX component.
> fix: add closing tag to SignInButton JSX component in snippet.

- docs/components/customization/organization-profile.mdx
- docs/components/customization/variables.mdx
- Replace "settings" with "general" in OrganizationProfile custom pages reordering items
- Update the default variables of the appearance prop
> Retheme updates

- docs/components/authentication/sign-in.mdx
- docs/components/authentication/sign-up.mdx
- docs/custom-flows/oauth-connections.mdx
- docs/custom-flows/saml-connections.mdx
- docs/organizations/creating-organizations.mdx
- docs/organizations/inviting-users.mdx
- docs/organizations/managing-roles.mdx
- docs/references/backend/overview.mdx
- docs/references/javascript/clerk/clerk.mdx
- docs/references/javascript/clerk/create-organization.mdx
- docs/references/javascript/clerk/organization-methods.mdx
- docs/references/javascript/clerk/redirect-methods.mdx
- docs/references/javascript/clerk/session-methods.mdx
- docs/references/javascript/clerk/sign-in.mdx
- docs/references/javascript/clerk/sign-up.mdx
- docs/references/javascript/external-account.mdx
- docs/references/javascript/organization/invitations.mdx
- docs/references/javascript/organization/members.mdx
- docs/references/javascript/organization/organization.mdx
- docs/references/javascript/sign-up/web3-verification.mdx
- docs/references/javascript/user/user.mdx
- docs/references/nextjs/server-actions.mdx
- docs/references/react/use-organization-list.mdx
- docs/testing/cypress.mdx
> v5 javascript updates

- docs/references/backend/sessions/authenticate-request.mdx
- docs/upgrade-guides/upgrading-from-v4-to-v5.mdx
**Review the changes per commit**
TODO: add a description
> feat(v5-upgrade-guide): Update upgrade guide based for ClerkJS SDKs @v5

- docs/references/javascript/organization/domains.mdx
- docs/references/javascript/organization/invitations.mdx
- docs/references/javascript/organization/members.mdx
- docs/references/javascript/organization/membership-request.mdx
- docs/references/javascript/types/clerk-paginated-response.mdx
- docs/references/javascript/user/user.mdx
- docs/upgrade-guides/upgrading-from-v4-to-v5.mdx
> fix: Update v4 -> v5 migration guide

- docs/references/go/overview.mdx
> fix go import path

- docs/upgrade-guides/upgrading-from-v4-to-v5.mdx
Add some localization values changes from UserProfile
> Add more @clerk/localizations value changes on the upgrade guide

- docs/upgrade-guides/upgrading-from-v4-to-v5.mdx
Added values that changed on the `<CreateOrganization/>` component.
Removed values no longer used on the avatar file drop area.
> Update localization changes

- docs/quickstarts/expo.mdx
Mention `expo-updates` / OTA updates in Expo docs
> docs(expo): add OTA consideration

- docs/references/nextjs/read-session-data.mdx
`userId` has been checked by the above `if` statement
> Remove unnecessary check from read-session-data doc

- docs/integrations/databases/convex.mdx
- docs/quickstarts/react.mdx
https://docs-preview-667.clerkpreview.com/docs/integrations/databases/convex
> DOCS-136 update convex guide

- docs/upgrade-guides/upgrading-nextjs-from-v4-to-v5.mdx
Final coat of polish on v5 migration guides ✨ 
Depends on https://github.com/clerk/clerk-marketing/pull/885
> v5 Migration Guide Adjustments

- docs/references/javascript/overview.mdx
> Fix invalid syntax in clerk-js example

- docs/references/javascript/clerk/sign-in.mdx
- docs/references/javascript/clerk/sign-up.mdx
- docs/references/javascript/user/user.mdx
[DOCS-5152](https://linear.app/clerk/issue/DOCS-5152/update-user-docs-with-an-accurate-list-of-user-methods) reads:
The [docs for the User class](https://clerk.com/docs/references/javascript/user/user#user) are dramatically out of date with reality and only contain a very small subset of the available methods. - you can see a list of the actual methods on the class [in the sidebar here](https://github.com/clerk/javascript/blob/main/packages/clerk-js/src/core/resources/User.ts).
It may be worth converting this into a list of subtasks, and certain people can be tapped for help in explaining the purpose of each method if necessary.
---
This PR
- adds missing methods to the User page
- adds examples for appropriate methods
🔎 [JS User …
> DOCS-5152 Update User docs with an accurate list of user methods

- docs/quickstarts/nextjs.mdx
Our Next.js quickstart needs to be updated for usability and discoverability. This PR includes changes to:
- The title of the quickstart
- The structure of the content
- Some of the comments in the code snippets
[Preview here](https://docs-preview-703.clerkpreview.com/docs/quickstarts/nextjs)
> DOCS-5376 Update Nextjs Quickstart

- docs/references/javascript/clerk/sign-in.mdx
- docs/references/javascript/clerk/sign-up.mdx
- `openSignUp` should be `mountSignUp`
- remove use of themes
> (core1) remove theme usage; fix mountSignUp

- docs/references/react/use-user.mdx
Made it a strictly equals, which is a JS/TS best practice. I couldn't find any other loosely equals in the docs.
> Code Example Fix

- docs/quickstarts/nextjs.mdx
- docs/quickstarts/react.mdx
- docs/upgrade-guides/core-2/nextjs.mdx
- updates react quickstart to follow suit of nextjs quickstart
- also found some things that needed to be updated in the nextjs quickstart
🔎 [React quickstart]
> DOCS-5441 (core2) update react quickstart

- docs/backend-requests/making/custom-session-token.mdx
- docs/components/authentication/sign-up.mdx
- docs/components/organization/create-organization.mdx
- docs/components/organization/organization-list.mdx
- docs/components/organization/organization-profile.mdx
- docs/components/organization/organization-switcher.mdx
- docs/components/user/user-button.mdx
- docs/references/backend/user/update-user.mdx
- docs/references/nextjs/current-user.mdx
- docs/references/nextjs/server-actions.mdx
[DOCS-5254](https://linear.app/clerk/issue/DOCS-5354/lose-the-[jsxtsx]-file-extension)
> DOCS-5254 remove jsx/tsx from file extensions

- docs/users/metadata.mdx
[DOCS-5336](https://linear.app/clerk/issue/DOCS-5336/fix-order-of-tabs-for-code-example-httpsclerkcomdocsusersmetadata)
> DOCS-5336 fix order of tabs in code example

- docs/quickstarts/expo.mdx
- docs/quickstarts/fastify.mdx
- docs/quickstarts/javascript.mdx
- docs/quickstarts/nextjs.mdx
- docs/quickstarts/react.mdx
- docs/quickstarts/remix.mdx
Want to make extra sure that if someone lands on this page, they know they are reading a beta guide, and where to find other upgrade info.
> add a note about the beta and linking to upgrade guide to quickstarts

- docs/references/react/use-organization-list.mdx
- docs/references/react/use-organization.mdx
🔎 [useOrganization](https://docs-preview-747.clerkpreview.com/docs/references/react/use-organization)
🔎 [useOrganizationList](https://docs-preview-747.clerkpreview.com/docs/references/react/use-organization-list)
> Add callout to React hooks about opting in to resources

- docs/manifest.json
- docs/references/backend/types/paginated-resource-response.mdx
- docs/references/backend/user/get-user-oauth-access-token.mdx
adds missing operation to backend sdk
> add getUserOAuthAccessToken to backend sdk

- CONTRIBUTING.md
- docs/references/go/other-examples.mdx
- docs/references/go/overview.mdx
- docs/references/go/verifying-sessions.mdx
_Do not merge but please do review_ :smile: 
Replaced the existing docs with content for the v2 version of the SDK.
> Updated the documentation for Go SDK

- docs/quickstarts/javascript.mdx
- docs/references/javascript/overview.mdx
🔎 [Preview JS Quickstart](https://docs-preview-740.clerkpreview.com/docs/quickstarts/javascript)
Merge when JS quickstart repos are updated.
> Update JavaScript Quickstart

- docs/components/control/redirect-to-createorganization.mdx
[DOCS-5295](https://linear.app/clerk/issue/DOCS-5295/feedback-for-componentscontrolredirect-to-createorganization)
> DOCS-5295 fix incorrect closing element

- docs/references/nextjs/trpc.mdx
Take over of this PR from an external contributor: https://github.com/clerk/clerk-docs/pull/612
> update trpc pages router guide

- docs/quickstarts/expo.mdx
- docs/references/javascript/organization/domains.mdx
- docs/references/javascript/organization/invitations.mdx
- docs/references/javascript/organization/members.mdx
- docs/references/javascript/organization/membership-request.mdx
found here: https://clerkinc.slack.com/archives/C03PHCND9JP/p1709747939411639
> fix links found by broken link checker

- docs/manifest.json
- docs/references/backend/overview.mdx
- docs/references/backend/types/backend-user.mdx
- docs/references/backend/user/update-user-metadata.mdx
While searching through the docs, I noticed that the documentation for this function is missing. I am unsure whether it is missing because we should simply use `user.update` or if there is something else to consider. However, I currently use this function in my project, and it seems to work as expected. I hope this helps, Clerk! Thanks!
> Add updateUserMetadata() to backend references

- docs/references/backend/user/update-user.mdx
[DOCS-5502](https://linear.app/clerk/issue/DOCS-5502/feedback-for-referencesbackenduserupdate-user) is a user feedback ticket that reported:
> In your app router example the file name is incorrect. Route handlers must follow the /api/folder/route.js/ts pattern
> DOCS-5502 update filename for route handler code example

- docs/references/react/use-user.mdx
[DOCS-5452](https://linear.app/clerk/issue/DOCS-5452/%F0%9F%98%A2-feedback-for-referencesreactuse-user) is a user feedback ticket that says:
> no informaton on what arguments can be passed to user.update
This PR adds clear reference links in each section on this page.
> DOCS-5452 adds links to reference documentation on /react/use-user page

- docs/upgrade-guides/long-term-support.mdx
This adds a level of detail that mirrors the beta docs
> Update LTS Page

- docs/components/customization/user-profile.mdx
Related to code review suggestions in https://github.com/clerk/clerk-docs/pull/768
> Shorten titles for /customization/user-profile

- docs/components/customization/overview.mdx
> small fix for a broken anchor link

- docs/manifest.json
- docs/quickstarts/nextjs.mdx
- docs/references/nextjs/overview.mdx
This PR:
- Replaces **More Resources** heading with **Next steps**
- Combines steps 4.2 and 4.3
- Removes step 5.4
- Removes step 7
- Moves authMiddleware docs link higher in the code snippet
- Removes language about "protecting" all routes, as this is inaccurate
- Shortens the environment variable section
Based on slack feedback:
- https://clerkinc.slack.com/archives/C01QFRQNHSN/p1710219197063989
> Update Nextjs quickstart

- docs/references/javascript/user/user.mdx
- switches the conditional logic in code examples from `!clerk.user` --> `clerk.user` in order to be consistent with other code examples in the docs
- adds the initialization script tag for script examples
- fixes syntax highlighting for the code examples
> switch conditional logic in code examples from !clerk.user --> clerk.user

- docs/references/javascript/organization-invitation.mdx
https://docs-preview-827.clerkpreview.com/docs/references/javascript/organization-invitation
> DOCS-5942 add example for revoke method

- docs/authentication/saml/overview.mdx
Introduce two new sections on the SAML overview page regarding the below options
- Sync user attributes during Sign in
- Allow subdomains
> Introduce SAML sections for 'Sync user attributes during Sign in' & 'Allow subdomains options'

- docs/references/backend/invitations/get-invitation-list.mdx
> Fix escaping in `get-invitation-list.mdx`

- docs/references/javascript/sign-up/authenticate-with.mdx
> Fix table in `authenticate-with.mdx`

- docs/references/react/use-user.mdx
Applying https://github.com/clerk/clerk-docs/pull/841 in beta docs
> fix: Add await to user.reload() snippet to indicate it is async

- docs/manifest.json
[Relevant PR for astro icon](https://github.com/clerk/clerk-marketing/pull/914)
> feat: Add Astro sdk reference

- docs/authentication/configuration/restrictions.mdx
🔎 https://docs-preview-836.clerkpreview.com/docs/authentication/configuration/restrictions#restrictions
TODO:
> DOCS-5962 update restrictions doc to better explain the restrictions features

- docs/authentication/configuration/restrictions.mdx
woops, missed this before merge
> Add bold to a reference to a Clerk Dashboard feature in the Restrictions doc

- docs/references/nextjs/custom-signup-signin-pages.mdx
[User feedback ticket](https://linear.app/clerk/issue/DOCS-5896/%F0%9F%98%A2-feedback-for-referencesnextjscustom-signup-signin-pages) needed to find our custom flow doc from the /custom-signup-signin-pages doc.
> add link to custom flows in the nextjs custom pages guide

- docs/authentication/saml/overview.mdx
Requirements were moved to each tutorial's "Before you start" section. This PR removes the section from the overview.
This PR also adds more information about the available guides and IdP's for SAML SSO with Clerk.
> Update saml overview

- docs/authentication/saml/authentication-flows.mdx
Suggestions for https://github.com/clerk/clerk-docs/pull/855
> Updates to new /saml/authentication-flow doc

- docs/references/backend/user/update-user.mdx
🔎 https://docs-preview-864.clerkpreview.com/docs/references/backend/user/update-user
> DOCS-5992 update UpdateUserParams for backend updateUser() method

- docs/authentication/saml/authentication-flows.mdx
- docs/authentication/saml/overview.mdx
Update the SAML FAQ section along with the new released features and also remove any references to the Beta period
**We should merge and deploy this on Monday**
> Update SAML FAQ section

- docs/authentication/saml/azure.mdx
- docs/authentication/saml/custom-provider.mdx
- docs/authentication/saml/google.mdx
- docs/authentication/saml/okta.mdx
- docs/authentication/saml/overview.mdx
- docs/manifest.json
Updated overview to mention the three IdPs we currently directly support integrations for, and to mention the guide for configuring a custom IdP (convo for this change lives [here](https://clerkinc.slack.com/archives/CHZ1FBBEG/p1711964994313999?thread_ts=1711662244.196599&cid=CHZ1FBBEG)):
🔎 https://docs-preview-868.clerkpreview.com/docs/authentication/saml/overview
Added guide for configuring SAML SSO with a custom IdP in Clerk:
🔎 https://docs-preview-868.clerkpreview.com/docs/authentication/saml/custom-provider
> (guide): add custom provider as option for saml sso

- docs/backend-requests/overview.mdx
- docs/references/nextjs/overview.mdx
This PR adds:
- [A list of required headers for authentication](https://docs-preview-875.clerkpreview.com/docs/backend-requests/overview#required-headers)
> Add info on required headers

- docs/components/organization/create-organization.mdx
Based on [this info](https://github.com/clerk/javascript/pull/1501/files#diff-7fe408fe0aa07864e0cb473677db03dee709c0c571cbfc856088e13b0d610d25R670).
> Add `skipInvitationScreen` to `CreateOrganization`

- docs/references/go/verifying-sessions.mdx
Made some adjustments to the code snippets and fixed a compilation error.
> fix: Go SDK manual token verification fixes

- docs/backend-requests/handling/nodejs.mdx
related ticket: https://linear.app/clerk/issue/DOCS-6014/add-missing-options-sdk-node-middleware
🔎 [Nodejs middleware options](https://docs-preview-896.clerkpreview.com/docs/backend-requests/handling/nodejs#middleware-options)
> DOCS-6014 update options for nodejs middleware

- docs/organizations/creator-role.mdx
🔎  https://docs-preview-904.clerkpreview.com/docs/organizations/creator-role
> remove screenshots from and clean up creator role guide

- docs/guides/basic-rbac.mdx
Corrected typographical errors and grammatical structure.
> Update basic-rbac.mdx, Correcting typos and grammar.

- docs/custom-flows/bot-sign-up-protection.mdx
- docs/custom-flows/use-sign-up.mdx
- docs/manifest.json
- docs/security/bot-protection.mdx
- Adds the "Bot sign-up protection on a custom flow" page
- Adds a top-level docs page about bot protection
> Add bot protection docs

- docs/references/backend/types/backend-user.mdx
https://github.com/clerk/clerk-docs/issues/911
> Resolves Issue 911: Update types for Backend User object

- docs/manifest.json
This position in the nav was requested by @jescalan [here](https://clerkinc.slack.com/archives/C06CA0JUZ8D/p1714489487109499?thread_ts=1714460040.892419&cid=C06CA0JUZ8D)
> Add core 1 docs to the sidebar nav

- docs/elements/examples/sign-in.mdx
- docs/elements/examples/sign-up.mdx
- Add `priority` prop to demos "above the fold" (https://github.com/clerk/clerk/pull/370)
- Use `rem` units for `height` styles
- Set background colours (https://github.com/clerk/clerk/pull/369)
> Elements: Update code block demo props

- docs/troubleshooting/create-a-minimal-reproduction.mdx
The link was to the older 2yr old started the Remix v2 is 4 months old using newer Remix + Clerk patterns
> Update Remix link to Newest Remix repo

- docs/authentication/social-connections/microsoft.mdx
https://linear.app/clerk/issue/DOCS-5891/add-info-that-saml-supports-tenants-to-ms-social-provider-doc
> DOCS-5891 Different tenant types *are* supported for SAML with Microsoft

- docs/elements/reference/sign-up.mdx
Reverts clerk/clerk-docs#988 per request on slack
> Revert "add more detail to <captcha> element docs"

- docs/components/control/authenticate-with-callback.mdx
- docs/components/control/multi-session.mdx
- docs/components/control/redirect-to-organizationprofile.mdx
- docs/components/customization/user-profile.mdx
- docs/components/organization/create-organization.mdx
- docs/components/organization/organization-profile.mdx
- docs/components/organization/organization-switcher.mdx
- docs/errors/actor-tokens.mdx
- docs/errors/application.mdx
- docs/errors/authentication.mdx
- docs/errors/billing-accounts.mdx
- docs/errors/billing.mdx
- docs/errors/domains.mdx
- docs/errors/entitlements.mdx
- docs/errors/identifications.mdx
- docs/errors/sign-in-tokens.mdx
- docs/errors/sign-in.mdx
This PR makes use of the [Line Break Opportunity element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/wbr) (`<wbr>`) to improve text wrapping in headings, particularly those containing inline code
The issues generally fall into two categories:
- `<h1>` is overflowing on small viewports
- Headings are overflowing and causing scroll in the table of contents
Below are a couple examples of the issues that this PR solves:
<table>
<tbody>
<tr>
<td colspan=2>
`docs/components/control/authenticate-with-callback.mdx`
```diff
- # `<AuthenticateWithRedirectCallback />`
+ # <code>\<AuthenticateWith<wbr/>RedirectCallback&nbsp;/></code>
```
</td>
</tr>
<tr>
<td>
Before
</td>
<td>
After
</td>
</tr>
<tr>
<td colspan=2>
`docs/errors/actor-tokens.mdx`
```diff
- ## …
```
> Improve text wrapping in headings

- docs/integrations/webhooks/overview.mdx
fix typo in webhooks overview page
> fix typo in webhooks overview page

- docs/custom-flows/email-sms-otp.mdx
> (/custom-flows/email-sms-otp) remove error handling from code examples

- docs/integrations/webhooks/debug-your-webhooks.mdx
- docs/integrations/webhooks/sync-data.mdx
- added info about type exports
- moved 'type' header up a level so it is easier to find for customers
- added info about returning success codes
- added info on installing ngrok
> Added some info based on feedback from customer

- docs/manifest.json
- docs/references/backend/organization/update-organization-logo.mdx
https://clerk.com/docs/pr/1035/references/backend/organization/update-organization-logo
> DOCS-6342 add updateOrganizationLogo to Backend SDK

- docs/custom-flows/saml-connections.mdx
https://clerk.com/docs/pr/1046/custom-flows/saml-connections
> DOCS-5905 Update SAML custom flow guide

- docs/custom-flows/oauth-connections.mdx
https://clerk.com/docs/pr/1045/custom-flows/oauth-connections
> DOCS-5242 Update OAuth connections custom flow guide

- docs/guides/basic-rbac.mdx
> Update basic-rbac.mdx 

- docs/references/nextjs/server-actions.mdx
https://clerk.com/docs/pr/1084/references/nextjs/server-actions
> DOCS-5371 update instructions/references in server actions guide

- docs/authentication/saml/azure.mdx
- docs/authentication/saml/google.mdx
- docs/authentication/saml/okta.mdx
Align SAML attribute mapping per provider with what's actually available
> Align SAML attribute mapping per provider with what's actually available

- docs/authentication/configuration/restrictions.mdx
The allowlist blocks sign-ins as well as sign-ups. We only mention it blocking sign-ups
> Update Allowlist docs

- docs/manifest.json
- docs/manifest.schema.json
Requires this PR to be merged as well, so the icon will be visible:
- https://github.com/clerk/clerk/pull/440
Screenshot:
> Add angular to community sdk section

- docs/elements/reference/sign-in.mdx
The feature is not implemented yet
> fix: Remove passkey from allowed strategy

- docs/manifest.json
- docs/organizations/creating-organizations.mdx
https://clerk.com/docs/pr/1093/organizations/creating-organizations
> (/organizations/create-organizations) Update nextjs and js examples

- docs/manifest.json
- docs/organizations/updating-organizations.mdx
https://clerk.com/docs/pr/1094/organizations/updating-organizations
> (/organizations/updating-organizations) Update Nextjs and JS examples

- docs/organizations/custom-organization-switcher.mdx
https://clerk.com/docs/pr/1105/organizations/custom-organization-switcher
> DOCS-325 (/organizations/custom-organization-switcher) Update Nextjs and JS examples

- docs/manifest.json
- docs/organizations/viewing-memberships.mdx
https://clerk.com/docs/pr/1092/organizations/viewing-memberships
> (/organizations/viewing-memberships) update nextjs and js examples

- docs/references/go/verifying-sessions.mdx
Updated the example code so that it compiles correctly.
> fix: Update code for Go verifying sessions

- docs/deployments/set-up-preview-environment.mdx
The text in there now makes it seem like support will create some sort of special new app for you, but this isn't the case. Wording adjusted to accurately capture the process!
> Add some clarification on how preview app upgrades work with support

- docs/advanced-usage/satellite-domains.mdx
- docs/guides/add-onboarding-flow.mdx
- docs/integrations/webhooks/debug-your-webhooks.mdx
- docs/integrations/webhooks/sync-data.mdx
- docs/references/nextjs/auth-middleware.mdx
- docs/references/nextjs/clerk-middleware.mdx
- docs/upgrade-guides/core-2/nextjs.mdx
thank you @JacobMGEvans for finding this!
https://clerkinc.slack.com/archives/C01QFRQNHSN/p1717619011949869
> update config for all clerkMiddleware examples

- docs/elements/reference/common.mdx
- docs/elements/reference/sign-in.mdx
- docs/elements/reference/sign-up.mdx
- Documents https://github.com/clerk/javascript/pull/3461
- Documents https://github.com/clerk/javascript/blob/68b227e969daea7a7b1651901bd794d45c41c301/packages/elements/src/react/common/form/types.ts#L4-L16
Fixes SDK-1813
Fixes SDK-1787
> feat(elements): Document virtual router & Field names

- docs/components/customization/localization.mdx
> Correct the highlighted line number in localizations

- docs/integrations/webhooks/overview.mdx
1. Fixed some grammar errors, added clarity.
2. Added a section on how to develop and test
> Added clarity for webhooks docs.

- docs/authentication/social-connections/linkedin-oidc.mdx
> [!IMPORTANT]
> 🔎 [Preview](https://clerk.com/docs/pr/1155/authentication/social-connections/linkedin-oidc#linked-in-open-id-connect)
- Removes all screenshots
- Ensures all content/instructions are up to date
- Ensures consistency across this and the [Microsoft OAuth](https://github.com/clerk/clerk-docs/pull/1135) updates
> Update LinkedIn OAuth guide

- docs/authentication/saml/azure.mdx
- docs/authentication/social-connections/microsoft.mdx
This PR:
- Removes screenshots
- Updates instructions for new Azure UI
- Updates description of Active Directory in our docs. Microsoft [rebranded this feature](https://learn.microsoft.com/en-us/entra/fundamentals/new-name) to Entra ID
🔎 Preview: https://clerk.com/docs/pr/1135/authentication/social-connections/microsoft
> Update Microsoft Azure OAuth guide

- docs/backend-requests/handling/go.mdx
Updated the request handling example for Go SDK v2.
> fix: Update Go requests guide to SDK v2

- docs/elements/reference/sign-in.mdx
- docs/elements/reference/sign-up.mdx
The docs PR for https://github.com/clerk/javascript/pull/3557 - should be merged once https://github.com/clerk/javascript/pull/3558 was merged (after that it'll be released)
> feat(elements): Document path inference

- docs/manifest.json
- docs/quickstarts/expo.mdx
> fixing the 404 for reading user data & updated headings in the quickstart

- docs/components/customization/overview.mdx
Small copy edits to improve consistency
> PR-1177 Follow up - small edits to customization overview

- docs/custom-flows/bot-sign-up-protection.mdx
- docs/security/bot-protection.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - [Custom flow for bot protection](https://clerk.com/docs/pr/1182/custom-flows/bot-sign-up-protection)
> - [Bot protection conceptual guide](https://clerk.com/docs/pr/1182/security/bot-protection)
While doing a small content audit for the IA, I moved this guide in the sidenav in [this PR.](https://github.com/clerk/clerk-docs/pull/1181) While taking a look at this guide, I noticed it needed more structure and to be made consistent with our other custom flow guides.
[Custom flow for bot protection](https://clerk.com/docs/pr/1182/custom-flows/bot-sign-up-protection)
- Updates title to be consistent with other custom flow titles
- Updates callout to be consistent with other custom flow callouts
- Updates overall structure (using `<Steps>` and doing two …
> Update bot protection custom flow guide

- docs/references/expo/overview.mdx
> Fixed typo in URL that was causing 404 redirect

- docs/manifest.json
- docs/references/backend/user/verify-totp.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1220/references/backend/user/verify-totp
Missing doc
- Adds doc for `verifyTOTP` method
> Add verifyTOTP method to Backend SDK

- docs/manifest.json
- docs/references/backend/organization/update-organization-logo.mdx
- docs/references/backend/user/update-user-profile-image.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - [updateUserProfileImage](https://clerk.com/docs/pr/1219/references/backend/user/update-user-profile-image)
> - [updateOrganizationLogo](https://clerk.com/docs/pr/1219/references/backend/organization/update-organization-logo)
Missing documentation for `updateUserProfileImage`
[updateUserProfileImage](https://clerk.com/docs/pr/1219/references/backend/user/update-user-profile-image)
- adds missing documentation
[updateOrganizationLogo](https://clerk.com/docs/pr/1219/references/backend/organization/update-organization-logo)
- updates syntax for file names
- adds code highlights
- updates codeblocktabs tab names
> Add updateUserProfileImage to Backend SDK; update updateOrganizationLogo for consistency

- docs/organizations/updating-organizations.mdx
Previously, this clamed that only an org name can be updated.
In fact, the org slug can also be updated! The API: 
https://github.com/clerk/javascript/blob/025ab87c660f65ad0dad8980554f1e21fc6dbce6/packages/types/src/organization.ts#L99-L102
And I have a little proof-of-concept proving that it works.
> Clarifying that organization name *and* slug can be updated.

- docs/quickstarts/astro.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1247/quickstarts/astro
-
> Enhance astro quickstart

- docs/elements/guides/sign-in.mdx
- docs/elements/guides/sign-up.mdx
- docs/elements/overview.mdx
- adds note within elements overview warning about app router support
> chore(elements): add note about app router only support

- docs/references/backend/email-addresses/create-email-address.mdx
- docs/references/backend/email-addresses/delete-email-address.mdx
- docs/references/backend/email-addresses/get-email-address.mdx
- docs/references/backend/email-addresses/update-email-address.mdx
- docs/references/backend/phone-numbers/create-phone-number.mdx
- docs/references/backend/phone-numbers/delete-phone-number.mdx
- docs/references/backend/phone-numbers/get-phone-number.mdx
- docs/references/backend/phone-numbers/update-phone-number.mdx
Part of the work for checking that our /backend/* reference docs were up to date ([due to this linear ticket](https://linear.app/clerk/issue/DOCS-6039/check-that-our-docsreferencesbackend-pages-match-our-backend-api))
I added each pages' corresponding `clerk/javascript` file in a comment on at the top of the page. Adding these links will make it easy to find where these methods exist in the `clerk/javascript` repo when updating their respective pages.
I updated pages accordingly to reflect the BAPI docs.
> Update Email address and Phone number Backend SDK docs to match BAPI docs

- docs/references/astro/migrating-from-astro-community-sdk.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1248/references/astro/migrating-from-astro-community-sdk
-
> Add migration guide for astro

- docs/manifest.json
> [!IMPORTANT]
> 🔎 Previews:
>
> -
Was found missing in a PR follow up review https://github.com/clerk/clerk-docs/pull/1229#discussion_r1673106210
-
> Add getOrganizationInvitation to sidenav

- docs/manifest.json
- docs/references/backend/organization/delete-organization-logo.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1215/references/backend/domains/delete-domain
Missing doc
- Adds doc for `deleteOrganizationLogo` method
> Add deleteOrganizationLogo method to Backend SDK

- docs/manifest.json
- docs/references/astro/endpoints.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1251/references/astro/endpoints
- Adds a guide on how to protect server endpoints (API routes)
> docs(astro): Add endpoint reference

- docs/deployments/deploy-to-vercel.mdx
- docs/deployments/set-up-preview-environment.mdx
Our guide for setting up a preview environment in Vercel was inaccurate.
This update resolves the inaccuracies, and also trims some information that may have been extraneous.  We may need to add some information back depending on additional customer feedback.
-
> Revise the vercel preview environment docs

- docs/deployments/set-up-preview-environment.mdx
Use bold instead of italics for consistent styling.
> bold instead of italics

- docs/references/astro/migrating-from-astro-community-sdk.mdx
- docs/references/astro/ui-react.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1260/references/astro/ui-react
> - https://clerk.com/docs/pr/1260/references/astro/migrating-from-astro-community-sdk
-
> Update migration guide to include latest changes

- docs/guides/authjs-migration.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
While reading docs I noticed these two anchor links were incorrect, so just a quick fixup here.
> fix: update anchor links

- docs/references/astro/endpoints.mdx
- docs/references/astro/locals.mdx
- docs/references/astro/migrating-from-astro-community-sdk.mdx
- docs/references/backend/overview.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
-
> Address PR reviews

- docs/references/backend/overview.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1246/references/backend/overview
- Splits the guide into two concepts: using the Backend SDK on its own vs. using it with other SDKs
- Adds `options`
> (/backend/overview) Add info for using the Backend SDK vs with other SDKs

- docs/manifest.json
- docs/quickstarts/astro.mdx
- docs/references/astro/clerk-middleware.mdx
- docs/references/astro/locals.mdx
- docs/references/astro/ui-react.mdx
- docs/references/backend/overview.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1276/quickstarts/astro#add-type-script-declarations
> - https://clerk.com/docs/pr/1276/references/astro/clerk-middleware#clerk-middleware-options
> - https://clerk.com/docs/pr/1276/references/backend/overview#instantiate-a-default-clerk-client-instance
> - https://clerk.com/docs/pr/1276/references/astro/locals#protect-your-pages
- Addressing some suggestions to the main Astro PR
> docs(astro): Reference updates

- docs/deployments/environments.mdx
Update docs to reflect the new user limit for development instances.
> Update the max number of users in development instances

- docs/references/astro/ui-react.mdx
- docs/references/expo/expo-impersonation.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
-
> fix broken links

- docs/references/astro/migrating-from-astro-community-sdk.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
This PR attempts to fix this spacing/alignment issues
-
> Address space indents in astro community migration guide

- docs/security/clerk-csp.mdx
Correcting errors in the CSP syntax, adding cloudflare's domain for bot protection, adding notes about the unsafe directives, why they are there, and scenarios in which they can be removed.
> [!IMPORTANT]
> 🔎 Previews:
>
> -
-
> Update CSP page 

- docs/manifest.json
- docs/organizations/manage-invitations.mdx
- docs/references/javascript/organization-invitation.mdx
- docs/references/javascript/types/user-organization-invitation.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1308/organizations/manage-invitations
> - https://clerk.com/docs/pr/1308/references/javascript/types/user-organization-invitation
- Adds the `UserOrganizationInvitation` type: https://clerk.com/docs/pr/1308/references/javascript/types/user-organization-invitation
- Adds a custom flow guide for managing a user's organization invitations: https://clerk.com/docs/pr/1308/organizations/manage-invitations
> Add a custom flow guide for managing a user's organization invitations

- docs/references/react/use-session-list.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1314/references/react/use-session-list
-
> fix usesessionlist() params table

- docs/authentication/configuration/sign-up-sign-in-options.mdx
~~⚠️ this PR should only be merged after feature and changelog PRs are merged ⚠️~~ this is done
- removes the callout around the beta period
> prep passkeys GA

- docs/references/astro/clerk-middleware.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1325/references/astro/clerk-middleware
- Fixes incorrect middleware exports. Reported [here](https://github.com/clerk/javascript/pull/3792#issuecomment-2248777202)
> docs(astro): Fix incorrect middleware exports

- docs/custom-flows/email-password.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1285/custom-flows/email-password
This will be the first in series of PRs adding iOS code examples to most of the custom flows pages.
- Adds iOS code examples to the Email & Password page.
> Add iOS example code to Custom Flows Email & Password

- docs/custom-flows/email-password-mfa.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1289/custom-flows/email-password-mfa
- Add iOS code example to email & password + mfa custom flow
> Add iOS example code to email & password + mfa custom flow

- docs/custom-flows/oauth-connections.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1290/custom-flows/oauth-connections
- Adds iOS example code to OAuth custom flow
> Add iOS example code to OAuth custom flow

- docs/custom-flows/sign-out.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1301/custom-flows/sign-out
- Adds iOS code example to sign out custom flows page
> Add iOS example code to sign out custom flow

- docs/custom-flows/multi-session-applications.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1303/custom-flows/multi-session-applications
- Adds iOS code example to custom flows multi session page
> Add iOS example code to multi-session custom flow

- docs/custom-flows/forgot-password.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1304/custom-flows/forgot-password
- Adds iOS example code to custom flows forgot password page
> Add iOS example code to forgot password custom flow

- docs/custom-flows/add-email.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1305/custom-flows/add-email
- Adds iOS example code to custom flows add email page
> Add iOS example code to add email custom flow

- docs/custom-flows/add-phone.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1316/custom-flows/add-phone
- Adds iOS example code to add phone custom flow
> Add iOS example code to add phone custom flow

- docs/backend-requests/resources/session-tokens.mdx
There was this file that was breaking the CI result.
> Fix formatting

- docs/manifest.json
- docs/references/ios/overview.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1335/references/ios/overview
-
> add iOS sdk reference and overview

- docs/quickstarts/expo.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
-
> remove Expo SDK link space

- docs/advanced-usage/using-proxies.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1352/advanced-usage/using-proxies
**Before**
**After**
> Use `nginx` lang for nginx config code snippet

- docs/organizations/overview.mdx
> [!WARNING]
> Do not merge until https://github.com/clerk/dashboard/pull/3216 is merged
(/organizations/overview)
> (/organizations/overview): update allow users to create organization path

- docs/custom-flows/user-impersonation.mdx
- docs/integrations/databases/neon.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1347/custom-flows/user-impersonation
> - https://clerk.com/docs/pr/1347/integrations/databases/neon
Correcting a couple broken links 🔗
> Correct broken links

- docs/organizations/overview.mdx
@alexisintech can we make it so that the Lint check must pass before merging?
> Apply Prettier formatting

- docs/organizations/overview.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
-
> (/organizations/overview) Fix formatting

- docs/custom-flows/add-email.mdx
- docs/custom-flows/add-phone.mdx
- docs/custom-flows/email-password-mfa.mdx
- docs/custom-flows/email-password.mdx
- docs/custom-flows/email-sms-otp.mdx
- docs/custom-flows/forgot-password.mdx
- docs/custom-flows/oauth-connections.mdx
- docs/custom-flows/sign-out.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1355
As discussed [here](https://github.com/clerk/clerk-docs/pull/1336#issuecomment-2263282306)
> Change Custom Flow Swift Code Blocks to 2 Spaces

- docs/integrations/databases/neon.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1367/integrations/databases/neon
| - | - |
| ![CleanShot 2024-08-02 at 09 49 08@2x](https://github.com/user-attachments/assets/7ef8a1e1-366a-488e-920e-efaf2b4f8385) | ![CleanShot 2024-08-02 at 09 49 20@2x](https://github.com/user-attachments/assets/6bc7815d-1136-4103-8e4c-39a62fbce0c8) |
> Fix lists on Neon page

- docs/components/customization/layout.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1369/components/customization/layout
-
> Add layout.unsafe_disableDevelopmentModeWarnings property to appearance

- docs/custom-flows/oauth-connections.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1376/custom-flows/oauth-connections
Update to match SDK method change.
> rename .social to .oauth in ios oauth custom flow

- docs/testing/cypress.mdx
- docs/testing/playwright.mdx
cypress docs were just released, and I wanted to update the playwright guide - quick little cleanup for consistency 🙏 
https://clerk.com/docs/pr/1375/testing/playwright
https://clerk.com/docs/pr/1375/testing/cypress
> Align Cypress and Playwright guides

- docs/integrations/databases/supabase.mdx
- docs/testing/cypress.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
-
> Update demo repo callouts for Cypress and Supabase guides

- docs/integrations/databases/firebase.mdx
- docs/integrations/webhooks/inngest.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1360/integrations/webhooks/inngest
FIXES #1126
> (/webhooks/inngest) Fix code example

- docs/backend-requests/handling/gatsby.mdx
- docs/backend-requests/handling/go.mdx
- docs/backend-requests/handling/manual-jwt.mdx
- docs/backend-requests/handling/nodejs.mdx
- docs/backend-requests/handling/ruby-rails.mdx
- docs/backend-requests/making/cross-origin.mdx
- docs/backend-requests/making/custom-session-token.mdx
- docs/backend-requests/making/jwt-templates.mdx
- docs/backend-requests/making/same-origin.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1378/backend-requests/handling/gatsby
> - https://clerk.com/docs/pr/1378/backend-requests/handling/go
> - https://clerk.com/docs/pr/1378/backend-requests/handling/manual-jwt
> - https://clerk.com/docs/pr/1378/backend-requests/handling/nodejs
> - https://clerk.com/docs/pr/1378/backend-requests/handling/ruby-rails
> - https://clerk.com/docs/pr/1378/backend-requests/making/cross-origin
> - https://clerk.com/docs/pr/1378/backend-requests/making/custom-session-token
> - https://clerk.com/docs/pr/1378/backend-requests/making/jwt-templates
> - https://clerk.com/docs/pr/1378/backend-requests/making/same-origin
> Enable Prettier for code blocks: `backend-requests`

- docs/account-portal/getting-started.mdx
- docs/advanced-usage/clerk-idp.mdx
- docs/advanced-usage/satellite-domains.mdx
- docs/advanced-usage/using-proxies.mdx
- docs/authentication/social-connections/oauth.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1377/account-portal/getting-started
> - https://clerk.com/docs/pr/1377/advanced-usage/clerk-idp
> - https://clerk.com/docs/pr/1377/advanced-usage/satellite-domains
> - https://clerk.com/docs/pr/1377/advanced-usage/using-proxies
> - https://clerk.com/docs/pr/1377/authentication/social-connections/oauth
> Enable Prettier for code blocks: `account-portal`, `advanced-usage`, `authentication`

- docs/custom-flows/email-links.mdx
- docs/custom-flows/email-sms-otp.mdx
- docs/custom-flows/embedded-email-links.mdx
- docs/custom-flows/error-handling.mdx
- docs/custom-flows/forgot-password.mdx
- docs/custom-flows/google-one-tap.mdx
- docs/custom-flows/invitations.mdx
- docs/custom-flows/multi-session-applications.mdx
- docs/custom-flows/passkeys.mdx
- docs/custom-flows/saml-connections.mdx
- docs/custom-flows/sign-out.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1380/custom-flows/email-links
> - https://clerk.com/docs/pr/1380/custom-flows/email-sms-otp
> - https://clerk.com/docs/pr/1380/custom-flows/embedded-email-links
> - https://clerk.com/docs/pr/1380/custom-flows/error-handling
> - https://clerk.com/docs/pr/1380/custom-flows/forgot-password
> - https://clerk.com/docs/pr/1380/custom-flows/google-one-tap
> - https://clerk.com/docs/pr/1380/custom-flows/invitations
> - https://clerk.com/docs/pr/1380/custom-flows/multi-session-applications
> - https://clerk.com/docs/pr/1380/custom-flows/passkeys
> - https://clerk.com/docs/pr/1380/custom-flows/saml-connections
> - https://clerk.com/docs/pr/1380/custom-flows/sign-out
> Enable Prettier for code blocks: `custom-flows`

- docs/integrations/databases/convex.mdx
- docs/integrations/databases/fauna.mdx
- docs/integrations/databases/firebase.mdx
- docs/integrations/databases/grafbase.mdx
- docs/integrations/databases/hasura.mdx
- docs/integrations/databases/neon.mdx
- docs/integrations/databases/nhost.mdx
- docs/integrations/databases/supabase.mdx
- docs/integrations/webhooks/debug-your-webhooks.mdx
- docs/integrations/webhooks/inngest.mdx
- docs/integrations/webhooks/overview.mdx
- docs/integrations/webhooks/sync-data.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1384/integrations/databases/convex
> - https://clerk.com/docs/pr/1384/integrations/databases/fauna
> - https://clerk.com/docs/pr/1384/integrations/databases/firebase
> - https://clerk.com/docs/pr/1384/integrations/databases/grafbase
> - https://clerk.com/docs/pr/1384/integrations/databases/hasura
> - https://clerk.com/docs/pr/1384/integrations/databases/neon
> - https://clerk.com/docs/pr/1384/integrations/databases/nhost
> - https://clerk.com/docs/pr/1384/integrations/databases/supabase
> - https://clerk.com/docs/pr/1384/integrations/webhooks/debug-your-webhooks
> - https://clerk.com/docs/pr/1384/integrations/webhooks/inngest
> - https://clerk.com/docs/pr/1384/integrations/webhooks/overview
> - …
> Enable Prettier for code blocks: `integrations`

- docs/deployments/changing-domains.mdx
- docs/deployments/migrate-from-firebase.mdx
- docs/deployments/migrate-overview.mdx
- docs/elements/examples/primitives.mdx
- docs/elements/examples/shadcn-ui.mdx
- docs/elements/examples/sign-in.mdx
- docs/elements/examples/sign-up.mdx
- docs/elements/guides/sign-in.mdx
- docs/elements/guides/sign-up.mdx
- docs/elements/guides/styling.mdx
- docs/elements/overview.mdx
- docs/elements/reference/common.mdx
- docs/elements/reference/sign-in.mdx
- docs/elements/reference/sign-up.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1381/deployments/changing-domains
> - https://clerk.com/docs/pr/1381/deployments/migrate-from-firebase
> - https://clerk.com/docs/pr/1381/deployments/migrate-overview
> - https://clerk.com/docs/pr/1381/elements/examples/primitives
> - https://clerk.com/docs/pr/1381/elements/examples/shadcn-ui
> - https://clerk.com/docs/pr/1381/elements/examples/sign-in
> - https://clerk.com/docs/pr/1381/elements/examples/sign-up
> - https://clerk.com/docs/pr/1381/elements/guides/sign-in
> - https://clerk.com/docs/pr/1381/elements/guides/sign-up
> - https://clerk.com/docs/pr/1381/elements/guides/styling
> - https://clerk.com/docs/pr/1381/elements/overview
> - https://clerk.com/docs/pr/1381/elements/reference/common
> - …
> Enable Prettier for code blocks: `deployments`, `elements`

- docs/errors/actor-tokens.mdx
- docs/errors/allowlist-identifiers.mdx
- docs/errors/application.mdx
- docs/errors/authentication.mdx
- docs/errors/backup-codes.mdx
- docs/errors/billing-accounts.mdx
- docs/errors/billing.mdx
- docs/errors/blocklist-identifiers.mdx
- docs/errors/clients.mdx
- docs/errors/cookie.mdx
- docs/errors/deprecation.mdx
- docs/errors/domains.mdx
- docs/errors/entitlements.mdx
- docs/errors/features.mdx
- docs/errors/identifications.mdx
- docs/errors/sign-in-tokens.mdx
- docs/errors/sign-in.mdx
- docs/errors/sign-up.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1382/errors/actor-tokens
> - https://clerk.com/docs/pr/1382/errors/allowlist-identifiers
> - https://clerk.com/docs/pr/1382/errors/application
> - https://clerk.com/docs/pr/1382/errors/authentication
> - https://clerk.com/docs/pr/1382/errors/backup-codes
> - https://clerk.com/docs/pr/1382/errors/billing-accounts
> - https://clerk.com/docs/pr/1382/errors/billing
> - https://clerk.com/docs/pr/1382/errors/blocklist-identifiers
> - https://clerk.com/docs/pr/1382/errors/clients
> - https://clerk.com/docs/pr/1382/errors/cookie
> - https://clerk.com/docs/pr/1382/errors/deprecation
> - https://clerk.com/docs/pr/1382/errors/domains
> - https://clerk.com/docs/pr/1382/errors/entitlements
> - https://clerk.com/docs/pr/1382/errors/features
> …
> Enable Prettier for code blocks: `errors`

- docs/guides/add-onboarding-flow.mdx
- docs/guides/authjs-migration.mdx
- docs/guides/basic-rbac.mdx
- docs/guides/custom-redirects.mdx
- docs/guides/force-organizations.mdx
- docs/guides/image-optimization/imageurl-image-optimization.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1383/guides/add-onboarding-flow
> - https://clerk.com/docs/pr/1383/guides/authjs-migration
> - https://clerk.com/docs/pr/1383/guides/basic-rbac
> - https://clerk.com/docs/pr/1383/guides/custom-redirects
> - https://clerk.com/docs/pr/1383/guides/force-organizations
> - https://clerk.com/docs/pr/1383/guides/image-optimization/imageurl-image-optimization
> Enable Prettier for code blocks: `guides`

- docs/custom-flows/oauth-connections.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1385/custom-flows/oauth-connections
- Changes the object name to match the recent change in the SDK
> rename socialprovider to oauthprovider

- docs/references/ios/overview.mdx
Fixing a tiny typo, something I am cursed with as a former Hubber 😅
> iOS SDK: Correct GitHub capitalization

- docs/organizations/creating-organizations.mdx
- docs/organizations/custom-organization-switcher.mdx
- docs/organizations/inviting-users.mdx
- docs/organizations/manage-invitations.mdx
- docs/organizations/manage-membership-requests.mdx
- docs/organizations/managing-roles.mdx
- docs/organizations/updating-organizations.mdx
- docs/organizations/verified-domains.mdx
- docs/organizations/verify-user-permissions.mdx
- docs/organizations/viewing-memberships.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1389/organizations/creating-organizations
> - https://clerk.com/docs/pr/1389/organizations/custom-organization-switcher
> - https://clerk.com/docs/pr/1389/organizations/inviting-users
> - https://clerk.com/docs/pr/1389/organizations/manage-invitations
> - https://clerk.com/docs/pr/1389/organizations/manage-membership-requests
> - https://clerk.com/docs/pr/1389/organizations/managing-roles
> - https://clerk.com/docs/pr/1389/organizations/updating-organizations
> - https://clerk.com/docs/pr/1389/organizations/verified-domains
> - https://clerk.com/docs/pr/1389/organizations/verify-user-permissions
> - https://clerk.com/docs/pr/1389/organizations/viewing-memberships
> Enable Prettier for code blocks: `organizations`

- docs/quickstarts/astro.mdx
- docs/quickstarts/fastify.mdx
- docs/quickstarts/gatsby.mdx
- docs/quickstarts/javascript.mdx
- docs/quickstarts/nextjs.mdx
- docs/quickstarts/react.mdx
- docs/quickstarts/remix.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1390/quickstarts/astro
> - https://clerk.com/docs/pr/1390/quickstarts/fastify
> - https://clerk.com/docs/pr/1390/quickstarts/gatsby
> - https://clerk.com/docs/pr/1390/quickstarts/javascript
> - https://clerk.com/docs/pr/1390/quickstarts/nextjs
> - https://clerk.com/docs/pr/1390/quickstarts/react
> - https://clerk.com/docs/pr/1390/quickstarts/remix
> Enable Prettier for code blocks: `quickstarts`

- docs/components/customization/user-button.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
-
> Remove duplicate usage of UserButton

- docs/references/astro/auth-store.mdx
- docs/references/astro/clerk-middleware.mdx
- docs/references/astro/clerk-store.mdx
- docs/references/astro/endpoints.mdx
- docs/references/astro/locals.mdx
- docs/references/astro/migrating-from-astro-community-sdk.mdx
- docs/references/astro/organization-store.mdx
- docs/references/astro/react.mdx
- docs/references/astro/read-session-data.mdx
- docs/references/astro/session-list-store.mdx
- docs/references/astro/session-store.mdx
- docs/references/astro/sign-in-store.mdx
- docs/references/astro/sign-up-store.mdx
- docs/references/astro/user-store.mdx
- docs/references/react/add-react-router.mdx
- docs/references/react/use-auth.mdx
- docs/references/react/use-clerk.mdx
- docs/references/react/use-organization-list.mdx
- docs/references/react/use-organization.mdx
- docs/references/react/use-session-list.mdx
- docs/references/react/use-session.mdx
- docs/references/react/use-sign-in.mdx
- docs/references/react/use-sign-up.mdx
- docs/references/react/use-user.mdx
- docs/references/remix/custom-signup-signin-pages.mdx
- docs/references/remix/read-session-data.mdx
- docs/references/remix/spa-mode.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1405/references/astro/auth-store
> - https://clerk.com/docs/pr/1405/references/astro/clerk-middleware
> - https://clerk.com/docs/pr/1405/references/astro/clerk-store
> - https://clerk.com/docs/pr/1405/references/astro/endpoints
> - https://clerk.com/docs/pr/1405/references/astro/locals
> - https://clerk.com/docs/pr/1405/references/astro/migrating-from-astro-community-sdk
> - https://clerk.com/docs/pr/1405/references/astro/organization-store
> - https://clerk.com/docs/pr/1405/references/astro/react
> - https://clerk.com/docs/pr/1405/references/astro/read-session-data
> - https://clerk.com/docs/pr/1405/references/astro/session-list-store
> - https://clerk.com/docs/pr/1405/references/astro/session-store
> - …
> Enable Prettier for code blocks: `references/{astro,react,remix}`

- docs/references/sdk/fullstack.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1395/references/sdk/fullstack
This PR will be merged into https://github.com/clerk/clerk-docs/pull/1344 and operates in the same context of "SDK Spec".
This doc copies text from https://github.com/clerk/clerk-docs/pull/1368 and https://github.com/clerk/clerk-docs/pull/1394 so if changes are requested there they'd also apply to this doc.
Fixes ECO-111
> SDK Spec: Fullstack

- docs/manifest.json
> [!IMPORTANT]
> 🔎 Previews:
>
> -
-
> Capitalize top level nav titles

- docs/authentication/social-connections/custom-provider.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1419/authentication/social-connections/custom-provider
> Fix nested list on "OAuth with a custom auth provider" page

- docs/organizations/creator-role.mdx
> Correct broken link to roles page

- docs/references/nextjs/custom-signup-signin-pages.mdx
Adds a missing `createRouteMatcher` import
> fix: Add missing `createRouteMatcher` import

- docs/custom-flows/email-links.mdx
- docs/guides/add-onboarding-flow.mdx
- docs/guides/authjs-migration.mdx
- docs/organizations/verify-user-permissions.mdx
- docs/quickstarts/astro.mdx
- docs/quickstarts/javascript.mdx
- docs/quickstarts/nextjs.mdx
- docs/quickstarts/react.mdx
- docs/references/nextjs/auth-middleware.mdx
- docs/references/remix/spa-mode.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1448/custom-flows/email-links
> - https://clerk.com/docs/pr/1448/guides/add-onboarding-flow
> - https://clerk.com/docs/pr/1448/guides/authjs-migration
> - https://clerk.com/docs/pr/1448/organizations/verify-user-permissions
> - https://clerk.com/docs/pr/1448/quickstarts/astro
> - https://clerk.com/docs/pr/1448/quickstarts/javascript
> - https://clerk.com/docs/pr/1448/quickstarts/nextjs
> - https://clerk.com/docs/pr/1448/quickstarts/react
> - https://clerk.com/docs/pr/1448/references/nextjs/auth-middleware
> - https://clerk.com/docs/pr/1448/references/remix/spa-mode
This PR fixes cases where sub-lists are not correctly indented, resulting in incorrect markup.
> Fix sub-list indentation

- docs/customization/localization.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
Once [this](https://github.com/clerk/javascript/pull/3953) PR is merged and the localization package is published we can update the docs to add Icelandic to the supported languages list for localization customization.
> Add Icelandic to supported languages list for localization customization

- docs/components/control/redirect-to-userprofile.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
-
> User profile URL is *not* configurable

- docs/manifest.json
> Remove duplicate /custom-flows/sign-out from sidenav

- docs/quickstarts/remix.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1467/quickstarts/remix
| - | - |
| ![CleanShot 2024-08-19 at 16 12 46@2x](https://github.com/user-attachments/assets/ab384d2d-779f-4b04-9287-344d0bbb4513) | ![CleanShot 2024-08-19 at 16 12 41@2x](https://github.com/user-attachments/assets/a71018eb-3d03-4886-a3bb-3bcd2425b975) |
> Add Remix icon to quickstart hero

- docs/guides/custom-types.mdx
- docs/manifest.json
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1462/guides/custom-types
https://linear.app/clerk/issue/DOCS-95/create-documentation-for-supported-custom-types
- Creates documentation for the Clerk interfaces that support custom types through interface merging.
> Create guide on overriding Clerk interfaces for custom types

- docs/organizations/creating-organizations.mdx
> Correct broken link

- docs/authentication/social-connections/custom-provider.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1482/authentication/social-connections/custom-provider#handling-edge-cases
I needed to create my own proxy and was a bit stumped at first on how to do it. After figuring it out (and building https://github.com/LekoArts/trakt-clerk-proxy) I'm documenting the rough outline of what one needs to do. So that others after me have it easier ✨
> chore: Improve custom OAuth edge cases section

- docs/advanced-usage/satellite-domains.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1485/advanced-usage/satellite-domains
The docs were incorrect in how they describe satellite domain usage in several spots, this should get everything in line!
> Satellite domain docs fixes

- docs/authentication/configuration/sign-up-sign-in-options.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1490/authentication/configuration/sign-up-sign-in-options#reset-a-users-mfa
During Support triage today, one of the tickets asked about how to reset a user's MFA.
-
> (/sign-up-sign-in-options) Add section about resetting a user's MFA

- docs/components/overview.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
Maintenance stuff:
- The reiteration of the sidenav in copy is not favourable for maintenance. Removes this from the copy.
- Adds explanation of control components
> Update component overview

- docs/quickstarts/astro.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
-
> Fix typos in astro.mdx

- docs/components/clerk-provider.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
While working on https://github.com/clerk/javascript/pull/4098 I saw that some properties were missing. So I added them.
> chore: Add ClerkProvider properties

- docs/authentication/social-connections/apple.mdx
- docs/authentication/social-connections/oauth.mdx
Added information regarding the configuration of your instance for native Apple sign in.
> [!IMPORTANT]
> 🔎 Previews:
>
>
-
> feat: Native Apple sign in

- docs/deployments/set-up-preview-environment.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
We need to merge this so that the docs make us look better buy using proper grammar.
- Fix typos like "avialable".
> docs: fix typo in set-up-preview-environment.mdx

- docs/references/ios/sign-in-with-apple.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1558/references/ios/sign-in-with-apple#build-your-sign-in-flow
Updates guide to match updated method signature in the iOS SDK.
> Update method signature in iOS Sign in with Apple guide

- docs/deployments/clerk-environment-variables.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1567
- updates variable names
> update variable names

- docs/authentication/saml/authentication-flows.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
Man -> Meddler, because it's better in all ways
> man -> meddler

- docs/testing/playwright.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
-
> (/playwright) Fix copy errors

- docs/authentication/saml/authentication-flows.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
-
> (/authentication-flows) Fix broken link

- docs/organizations/creator-role.mdx
- docs/organizations/default-role.mdx
- docs/organizations/verified-domains.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
-
> PR-1584 followup review from docs team

- docs/customization/localization.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
- Added the Finnish language to the supported languages list.
> Added Finnish language to the supported languages list.

- docs/quickstarts/javascript.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1593/quickstarts/javascript
- fixes spelling
> (/quickstarts/javascript) fix spelling

- docs/customization/localization.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1587/customization/localization
-
> (/localization) Add JS example; update list of supported locales

- docs/authentication/configuration/sign-up-sign-in-options.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
-
> Update 'Delete MFA' > 'Reset MFA'

- docs/customization/localization.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1604/customization/localization
I have added a new translation in clerk/javascript [PR-4280](https://github.com/clerk/javascript/pull/4280), so the list of available localizations has been updated.
- Update list available localizations
> Update localizations docs

- docs/authentication/social-connections/oauth.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
this pr solves issue for exception handling on when "accessToken" is null or undefined
it solves issue #1627 , with exception handling and crash checks
- includes exception handling for social connection accessToken
> (/social-connections/oauth) Add error handling to access token example

- docs/authentication/saml/authentication-flows.mdx
- docs/authentication/saml/overview.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1631/authentication/saml/authentication-flows
- adds definition for SP and IP
- fixes structure and refactors content
> (/authentication/saml/authentication-flows) update guide

- docs/advanced-usage/satellite-domains.mdx
- docs/authentication/social-connections/oauth.mdx
- docs/backend-requests/making/custom-session-token.mdx
- docs/components/clerk-provider.mdx
- docs/custom-flows/user-impersonation.mdx
- docs/guides/add-onboarding-flow.mdx
- docs/guides/authjs-migration.mdx
- docs/guides/basic-rbac.mdx
- docs/guides/custom-redirects.mdx
- docs/guides/force-organizations.mdx
- docs/integrations/databases/neon.mdx
- docs/integrations/databases/supabase.mdx
- docs/manifest.json
- docs/organizations/verify-user-permissions.mdx
- docs/references/backend/sessions/get-token.mdx
- docs/references/nextjs/auth-middleware.mdx
- docs/references/nextjs/auth-object.mdx
- docs/references/nextjs/auth.mdx
- docs/references/nextjs/clerk-middleware.mdx
- docs/references/nextjs/custom-signup-signin-pages.mdx
- docs/references/nextjs/read-session-data.mdx
- docs/references/nextjs/rendering-modes.mdx
- docs/references/nextjs/route-handlers.mdx
- docs/references/nextjs/server-actions.mdx
- docs/upgrade-guides/nextjs/v6.mdx
- docs/users/user-impersonation.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1641/upgrade-guides/nextjs/v6
> - https://clerk.com/docs/pr/1641/references/nextjs/rendering-modes
Bringing Clerk docs in line with latest version of Next.js SDK
-
> feat: next@15 compatibility

- docs/why-clerk.mdx
> Remove empty pages

- .github/CODEOWNERS
> [!IMPORTANT]
> 🔎 Previews:
>
> -
Adds Clerk Growth team (currently just @mwickett ) as optional reviewer on changes to Quickstart content
> codeowners: notify growth team on quickstart changes

- docs/authentication/social-connections/slack.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1646/authentication/social-connections/slack
- updates guide
> (/authentication/social-connections/slack) update guide

- docs/authentication/configuration/email-sms-templates.mdx
- docs/authentication/configuration/sign-up-sign-in-options.mdx
- docs/authentication/saml/jit-provisioning.mdx
- docs/components/organization/organization-profile.mdx
- docs/components/organization/organization-switcher.mdx
- docs/deployments/migrate-overview.mdx
- docs/guides/architecture-scenarios.mdx
- docs/guides/routing.mdx
Also removes "out-of-the-box" where it's not necessary.
> Out of the box --> out-of-the-box

- docs/custom-flows/oauth-connections.mdx
> fix: Remove `console.log` from code snippet

- docs/customization/elements/examples/shadcn-ui.mdx
- docs/customization/elements/examples/sign-in.mdx
- docs/customization/elements/examples/sign-up.mdx
- docs/customization/elements/reference/common.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1674/customization/elements/reference/common#link
> - https://clerk.com/docs/pr/1674/customization/elements/examples/sign-in
> - https://clerk.com/docs/pr/1674/customization/elements/examples/sign-up
> - https://clerk.com/docs/pr/1674/customization/elements/examples/shadcn-ui
Add docs for Elements `<Link />` component https://github.com/clerk/javascript/pull/4456
- add reference docs for `<Link />` component
- updates Elements examples to make use of `<Link />` component
> chore(Elements): Add `<Link />` component references

- docs/components/overview.mdx
> Fix localization link

- docs/maintenance-mode.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1686/maintenance-mode
Maintenance mode scheduled for December 1st
https://clerkinc.slack.com/archives/C080A8U759N/p1730863756394729
> Maintenance mode doc

- docs/customization/elements/overview.mdx
- docs/customization/localization.mdx
- docs/customization/themes.mdx
- docs/guides/authjs-migration.mdx
- docs/integrations/databases/convex.mdx
- docs/integrations/webhooks/sync-data.mdx
- docs/references/astro/migrating-from-astro-community-sdk.mdx
- docs/references/astro/react.mdx
- docs/references/expo/local-credentials.mdx
- docs/references/expo/web-support/custom-signup-signin-pages.mdx
- docs/references/javascript/types/overview.mdx
- docs/references/nextjs/custom-signup-signin-pages.mdx
- docs/references/nextjs/usage-with-older-versions.mdx
- docs/references/nodejs/overview.mdx
- docs/references/react/add-react-router.mdx
- docs/references/redwood/overview.mdx
- docs/references/remix/custom-signup-signin-pages.mdx
- docs/references/remix/spa-mode.mdx
- docs/references/tanstack-start/custom-signup-signin-pages.mdx
- docs/upgrade-guides/core-2/backend.mdx
- docs/upgrade-guides/core-2/chrome-extension.mdx
- docs/upgrade-guides/core-2/expo.mdx
- docs/upgrade-guides/core-2/fastify.mdx
- docs/upgrade-guides/core-2/javascript.mdx
- docs/upgrade-guides/core-2/nextjs.mdx
- docs/upgrade-guides/core-2/node.mdx
- docs/upgrade-guides/core-2/react.mdx
- docs/upgrade-guides/core-2/remix.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
-
> chore: remove type="installer" 

- docs/references/express/overview.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/references/express/overview
The word "response" is replaced with "res" in the middleware to fix a response not found error.
- Replaces "response" with "res" in hasPermission.
> Replace 'response' with 'res'

- docs/references/nextjs/clerk-middleware.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1697/references/nextjs/clerk-middleware#dynamic-keys
-
> chore: move dynamic keys callout above

- .github/pull_request_template.md
> [!IMPORTANT]
> 🔎 Previews:
>
> -
Fixes the checklist rendering in PR template
| BEFORE | AFTER |
|--------|--------|
| <img width="945" alt="before" src="https://github.com/user-attachments/assets/0d4e4d2a-cc4e-4e5c-b3cc-4d8686a78a23"> | <img width="806" alt="after" src="https://github.com/user-attachments/assets/3573acea-b35e-4cdc-a9ad-173643436fd6"> | 
This enables clicking the checkboxes in the PR
- 
[ ] I have clicked on "Files changed" and performed a thorough self-review
[ ] I have added the "deploy-preview" label and added the preview link(s) to this PR description
[ ] All existing checks pass
> fix pull request template checklist

- docs/references/javascript/clerk/clerk.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
I believe this has changed since Core 2 came out
> chore: Remove interstitial reference

- docs/_partials/reverification-route-handler.mdx
- docs/guides/reverification.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1745/guides/reverification
- 
-
> (/guides/reverification): improve "Other" tab in "How to require reverification"

- docs/guides/reverification.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
- 
-
> improve text for ruby example

- docs/references/backend/authenticate-request.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1761/references/backend/authenticate-request
- Builds are failing because of a malformed include
- Replaces `<Input/>` with `<Include/>`
- Fixes the include source
> Fix include

- docs/manifest.json
> (manifest): remove dupe link

- docs/backend-requests/making/jwt-templates.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
- 
-
> fix: JWT Template shortcodes for verified email and phone number

- docs/guides/authjs-migration.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
- 
-
> fix: formatting

- docs/authentication/enterprise-connections/overview.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1785/authentication/enterprise-connections/overview
- Fixes broken links found by [Oh Dear](https://clerkinc.slack.com/archives/C07JVHA2UTZ/p1733538674458739).
> Fix broken links on Enterprise SSO overview

- docs/testing/playwright/overview.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1798/testing/playwright/overview#configure-playwright-with-clerk
- Improves our testing docs by ensuring the global setup is run serially, even if playwright is configured to run in parallel.
> fix(testing): add note about running test setup in serial mode

- docs/custom-flows/error-handling.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1810/custom-flows/error-handling
- Aligns the code examples with their canonical references (from the email-password custom flow guides).
- Adds syntax highlighting to the code examples
> (/custom-flows/error-handling) update guide

- docs/how-clerk-works/overview.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1812/how-clerk-works/overview
[Internal discussion here](https://clerkinc.slack.com/archives/C02SCBZ08GN/p1734341139254019?thread_ts=1734204556.650219&cid=C02SCBZ08GN) - helps users to know where they are in the video, control it, not feel lost in the loops.
> Add controls to "how clerk works" videos

- docs/quickstarts/expo.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
Documentation Update. Fixes the Documentation for the expo install guidelines to highlight the correct line instead of the existing incorrect line
is not a lot, its just 1 charecter but it fixes the highlighted line
> change the marking of the _layout.tsx file

- docs/authentication/web3/coinbase-wallet.mdx
**Preview**: https://clerk.com/docs/pr/1830/authentication/web3/coinbase-wallet
**Related PRs**:
- https://github.com/clerk/clerk-docs/pull/1817#pullrequestreview-2516391236
- https://github.com/clerk/clerk-docs/pull/1818#pullrequestreview-2516399944
> chore: (authentication/web3/coinbase-wallet) align with metamask and okx

- docs/authentication/web3/okx-wallet.mdx
- docs/manifest.json
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1817/authentication/web3/okx-wallet
- 
-
> feat: OKX Wallet Web3 authentication guide

- docs/references/nuxt/clerk-middleware.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
- 
-
> (/references/nuxt/clerk-middleware) fix path

- docs/references/backend/user/get-organization-membership-list.mdx
…embership examples in documentation
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1851
[DOCS-9525](https://linear.app/clerk/issue/DOCS-9525/update-getorganizationmembershiplist-example-object-to-match-api)
Adds missing fields in the response body of the `getOrganizationMembershipList()` API call
> (backend/user/get-organization-membership-list): Add missing permissions property in code examples

- docs/components/authentication/google-one-tap.mdx
- docs/components/authentication/sign-in.mdx
- docs/components/authentication/sign-up.mdx
- docs/components/control/signed-in.mdx
- docs/components/control/signed-out.mdx
- docs/components/organization/create-organization.mdx
- docs/components/organization/organization-list.mdx
- docs/components/organization/organization-profile.mdx
- docs/components/organization/organization-switcher.mdx
- docs/components/protect.mdx
- docs/components/unstyled/sign-in-button.mdx
- docs/components/unstyled/sign-in-with-metamask.mdx
- docs/components/unstyled/sign-out-button.mdx
- docs/components/unstyled/sign-up-button.mdx
- docs/components/user/user-button.mdx
- docs/components/user/user-profile.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> **Authentication components**
> - https://clerk.com/docs/pr/1858/components/authentication/sign-in
> - https://clerk.com/docs/pr/1858/components/authentication/sign-up
> - https://clerk.com/docs/pr/1858/components/authentication/google-one-tap
>
> **Control components**
> - https://clerk.com/docs/pr/1858/components/control/signed-in
> - https://clerk.com/docs/pr/1858/components/control/signed-up
> - https://clerk.com/docs/pr/1858/components/protect
>
> **Unstyled components**
> - https://clerk.com/docs/pr/1858/components/unstyled/sign-in-button
> - https://clerk.com/docs/pr/1858/components/unstyled/sign-up-button
> - https://clerk.com/docs/pr/1858/components/unstyled/sign-in-with-metamask
> - https://clerk.com/docs/pr/1858/components/unstyled/sign-out-butto …
> Add UI components examples for Vue

- docs/backend-requests/handling/nodejs.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1876/backend-requests/handling/nodejs
**Before**
**After**
> Fix middleware options list on Node.js page

- docs/references/backend/types/backend-session.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1886/references/backend/types/backend-session
Linear ticket: USER-1181
This PR updates Backend Session resource to match the SDK
> chore: Update backend Session resource

- docs/quickstarts/javascript.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1889/quickstarts/javascript
Updates JavaScript quickstart script tag implementation to pull the correct latest version.
-
> Update javascript quickstart script link version

- docs/components/control/redirect-to-organizationprofile.mdx
- docs/components/control/redirect-to-userprofile.mdx
> fix page titles again

- docs/authentication/configuration/restrictions.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1900/authentication/configuration/restrictions
- 
-
> (docs/authentication/configuration/restrictions): add enterprise connections mention on restricted mode

- docs/components/control/redirect-to-userprofile.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
- 
-
> fix `<RedirectToUserProfile />` page title

- docs/backend-requests/resources/rate-limits.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1910/backend-requests/resources/rate-limits
-  Our rate limit docs are not quite accurate. We only rate limit by IP for FAPI. I've updated the wording to avoid confusion.
-  Fixed words to clarify how each API approaches rate limiting.
> Clarify how rate limiting works

- docs/manifest.json
> [!IMPORTANT]
> 🔎 Previews:
>
> -
- Fix sidenav path for geo blocking doc
- Edits the manfiest.json with the correct path
> Fix sidenav for geo blocking doc

- docs/references/react/overview.mdx
https://linear.app/clerk/issue/DOCS-9782/edit-note-about-clerkreact-in-nextjs
> remove note about clerk/react not being compatible with nextjs

- docs/components/authentication/sign-in.mdx
- docs/components/authentication/sign-up.mdx
- docs/guides/custom-redirects.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> - https://clerk.com/docs/pr/1916/guides/custom-redirects
> - https://clerk.com/docs/pr/1916/components/authentication/sign-in
> - https://clerk.com/docs/pr/1916/components/authentication/sign-up
https://linear.app/clerk/issue/DOCS-9819/update-description-for-signinforceredirecturl-signupforceredirecturl
> clarify force and fallback redirect prop descriptions

- docs/references/javascript/types/set-active-params.mdx
https://clerkinc.slack.com/archives/C01QFRQNHSN/p1737131760380359
> hotfix set-active-params title

- docs/manifest.json
> [!IMPORTANT]
> 🔎 Previews:
>
> -
Depends on [this PR here](https://github.com/clerk/clerk/pull/939) for the icon
> Add c# sdk docs to nav

- docs/how-clerk-works/overview.mdx
> [!IMPORTANT]
> 🔎 Previews:
>
> -
- The backend API overview link is broken.
- Fix broken link for backend API overview.
> fix: broken link for backend api overview

- docs/authentication/social-connections/account-linking.mdx
- docs/authentication/social-connections/twitter.mdx
- docs/backend-requests/making/custom-session-token.mdx
- docs/custom-flows/email-links.mdx
- docs/deployments/migrate-from-firebase.mdx
- docs/integrations/databases/grafbase.mdx
- docs/integrations/databases/hasura.mdx
- docs/integrations/databases/nhost.mdx
- docs/security/unlock-user-accounts.mdx
- docs/testing/postman-or-insomnia.mdx
- docs/troubleshooting/create-a-minimal-reproduction.mdx
- docs/users/invitations.mdx
- docs/webhooks/inngest.mdx
- docs/webhooks/overview.mdx
**ticket**: https://linear.app/clerk/issue/DOCS-9770/chore-update-click-to-select
> chore: "click" -> "select"

- CONTRIBUTING.md
update `style guide` reference to renamed STYLEGUIDE file
> update `style guide` reference

- docs/references/nextjs/authjs-migration.mdx
> docs(authjs-migration): fix wrong import directory

- docs/custom-flows/email-sms-otp.mdx
- https://clerk.com/docs/pr/1954/custom-flows/email-sms-otp#sign-up-flow
- Changes var names that may have been confusing. 
- Changes the name to reflect the correct object that is being acted on.
> fix: Updated var names on email-sms-otp signup flow

- docs/backend-requests/resources/rate-limits.mdx
-
-  Update our rate limit docs to align with the real values
-
> fix: Align rate limits with actual values

- docs/organizations/overview.mdx
-
This is no longer accurate. 
-
> fix: Remove outdated callout about empty org deletion

- package.json
Was mistakenly added by a previous employee
> Remove @clerk/testing depedency

- docs/authentication/configuration/email-sms-templates.mdx
- docs/components/organization/organization-profile.mdx
- docs/custom-flows/manage-sms-based-mfa.mdx
- docs/integrations/overview.mdx
- docs/references/react/use-organization.mdx
- docs/upgrade-guides/core-2/component-redesign.mdx
- docs/upgrade-guides/core-2/remix.mdx
- docs/users/invitations.mdx
- docs/webhooks/debug-your-webhooks.mdx
-
- First open source contribution to the Clerk documentation!
- Updated minor spelling mistakes, updated anchor links, and external links that 404'd.
> Update Anchor Links + Typos

- CONTRIBUTING.md
- docs/manifest.schema.json
Requires https://github.com/clerk/clerk/pull/1001 to be merged first.
This documents the `<If />` component for use in the markdown files.
> Add <If /> component to CONTRIBUTING.md

- docs/custom-flows/add-email.mdx
- docs/custom-flows/add-phone.mdx
- docs/custom-flows/email-password-mfa.mdx
- docs/custom-flows/email-password.mdx
- docs/custom-flows/email-sms-otp.mdx
- docs/custom-flows/forgot-password.mdx
- docs/custom-flows/oauth-connections.mdx
- docs/custom-flows/sign-out.mdx
- https://clerk.com/docs/pr/2004/custom-flows/email-password
- https://clerk.com/docs/pr/2004/custom-flows/email-sms-otp
- https://clerk.com/docs/pr/2004/custom-flows/email-password-mfa
- https://clerk.com/docs/pr/2004/custom-flows/oauth-connections
- https://clerk.com/docs/pr/2004/custom-flows/sign-out
- https://clerk.com/docs/pr/2004/custom-flows/forgot-password
- https://clerk.com/docs/pr/2004/custom-flows/add-email
- https://clerk.com/docs/pr/2004/custom-flows/add-phone
- Updates the custom flows to reflect the latest version of the iOS SDK.
> update ios custom flows code examples

- docs/customization/user-button.mdx
- docs/quickstarts/expo.mdx
- docs/references/expo/web-support/custom-sign-in-or-up-page.mdx
- docs/references/expo/web-support/custom-sign-up-page.mdx
- docs/testing/cypress/overview.mdx
- styleguides/STYLEGUIDE.md
old syntax: filename=""
new syntax: {{ filename: "" }}
> (chore) remove deprecated filename syntax

- docs/_partials/authentication/microsoft/get-client-id-secret.mdx
https://linear.app/clerk/issue/DOCS-9947/partial-authenticationmicrosoft-warning-is-missing
> Fix missing authentication/microsoft-warning partial

- docs/webhooks/sync-data.mdx
https://linear.app/clerk/issue/DOCS-9948/feedback-for-webhookssync-data
> (webhooks/sync-data) stringify the payload

- docs/testing/playwright/overview.mdx
https://linear.app/clerk/issue/DOCS-9942/feedback-for-testingplaywrightoverview
> (testing/playwright) clarify how to set testing token env var

- CONTRIBUTING.md
- prettier-mdx.mjs
> Update Prettier plugin and contributing doc to support inline code highlights

- docs/_partials/hooks/paginated-resources.mdx
- docs/_partials/hooks/shared-properties.mdx
- docs/references/react/use-organization-list.mdx
- docs/references/react/use-organization.mdx
-
- Related to changes in https://github.com/clerk/clerk-docs/pull/2038 , wanted to get these consistent across.
- Introduced partials to reuse in both useOrganization() and useOrganizationList() reference docs
> Update useOrganizationList() reference

- docs/references/javascript/types/enterprise-account-connection.mdx
- docs/references/javascript/types/enterprise-account.mdx
- docs/references/javascript/types/saml-account-connection.mdx
- docs/references/javascript/types/saml-account.mdx
- docs/references/javascript/types/sso.mdx
- docs/references/javascript/types/verification.mdx
- docs/references/javascript/user/user.mdx
- https://clerk.com/docs/pr/2036/references/javascript/user/user
- https://clerk.com/docs/pr/2036/references/javascript/types/enterprise-account
- https://clerk.com/docs/pr/2036/references/javascript/types/enterprise-account-connection
- https://clerk.com/docs/pr/2036/references/javascript/types/saml-account
- https://clerk.com/docs/pr/2036/references/javascript/types/saml-account-connection
- The `externalId` prop was reported as missing from the `User` reference
- Adds missing props to `User`
- Puts props in alphabetical order
- Adds missing type references
> Update User reference; add missing types

- docs/custom-flows/email-links.mdx
> (email links) fix headings

- docs/advanced-usage/clerk-idp.mdx
> Add the 'sub' OAuth User Info property

- docs/references/nextjs/trpc.mdx
- Updates the guide for App Router
- Creates a new pair repository: https://github.com/clerk/clerk-nextjs-trpc
FIXES DOCS-393, DOCS-5259, DOCS-5284, DOCS-5423, DOCS-5424, DOCS-5870, DOCS-5877, DOCS-6001, DOCS-8872, DOCS-9573, DOCS-9582, DOCS-9589, DOCS-9911
> Update tRPC guide for App Router

- docs/customization/localization.mdx
- Added missing locales
- Put list in alphabetical order
> (localizations) update and alphabetize list of locales

- docs/custom-flows/email-password.mdx
- docs/custom-flows/email-sms-otp.mdx
- docs/custom-flows/error-handling.mdx
- docs/custom-flows/manage-sms-based-mfa.mdx
- docs/custom-flows/manage-totp-based-mfa.mdx
- docs/integrations/databases/firebase.mdx
"it can be adapted for any React meta framework, such as Remix" --> "it can be adapted for any React-based framework"
> (chore) React meta framework --> React-based framework

- docs/security/bot-protection.mdx
https://linear.app/clerk/issue/DOCS-9952/mention-that-bot-protection-breaks-in-device-emulators
> mention that bot protection isnt supported by device emulators

- docs/references/javascript/clerk.mdx
- docs/references/nextjs/add-onboarding-flow.mdx
-
Corrected misspelled words
Used the correct spellings
> fix(docs): corrected misspelled words 

- docs/references/chrome-extension/add-react-router.mdx
React Router v7+ is currently having issues, causing a known "useNavigate" error when following [Chrome Extension: Add React Router documentation](https://clerk.com/docs/references/chrome-extension/add-react-router) directly (aka without specifying a react-router-dom package version).  Specifying v6.28.0 will install a version that is compatible.
**Before (popup):**
**After (popup):**
**Clerk Discord server discussion:**
**Related GitHub issues:**
- https://github.com/remix-run/react-router/issues/12399
- https://github.com/remix-run/react-router/issues/12475
React Router v7+ is currently having issues, causing a known "useNavigate" error when following [Chrome Extension: Add React Router documentation](https://clerk.com/docs/references/chrome-extension/add-react-router) directly (aka …
> Specify React Router v7 for React Router + Chrome extension guide

- docs/quickstarts/ios.mdx
- https://clerk.com/docs/pr/2134/quickstarts/ios
- Added Create first user step to iOS QS
> (ios) add create first user step to QS

- docs/custom-flows/email-password-mfa.mdx
- docs/custom-flows/email-password.mdx
- docs/custom-flows/email-sms-otp.mdx
- docs/custom-flows/forgot-password.mdx
- docs/quickstarts/ios.mdx
- https://clerk.com/docs/pr/2135/custom-flows/email-password-mfa
- https://clerk.com/docs/pr/2135/custom-flows/email-password
- https://clerk.com/docs/pr/2135/custom-flows/email-sms-otp
- https://clerk.com/docs/pr/2135/custom-flows/forgot-password
- https://clerk.com/docs/pr/2135/quickstarts/ios
- iOS function parameters have changed. This PR updates the docs to match.
> iOS: update function parameters to latest

- docs/integrations/databases/instantdb.mdx
- https://clerk.com/docs/pr/2128/integrations/databases/instantdb
- Part of a project to update the integrations docs
- Updates copy overall to better match Docs voice and to ensure all information is up to date
- Removes screenshots
- Updated the paired repo: https://github.com/clerk/clerk-instantdb-nextjs
> (instantdb) overhaul guide

- docs/integrations/databases/supabase.mdx
-
- 
- Fixes code snippets and RLS SQL statements based on testing
> chore(supabase): Fix RLS statements and code snippets

- docs/references/nextjs/rendering-modes.mdx
- https://clerk.com/docs/pr/2138/references/nextjs/rendering-modes
This guide was a bit misleading as it was originally written. I've updated the guide to be more clear, and have more comprehensive examples.
> (nextjs/rendering-modes) update guide

- docs/hooks/use-reverification.mdx
- https://clerk.com/docs/pr/2143/hooks/use-reverification
- 
-
> chore: useReverification hook improvement

- docs/authentication/social-connections/apple.mdx
https://linear.app/clerk/issue/DOCS-10148/add-additional-information-about-apple-private-key
Related dashboard PR: https://github.com/clerk/dashboard/pull/4960
> (apple) add copy about including key prefix and suffix

- docs/components/authentication/sign-in.mdx
- docs/components/authentication/sign-up.mdx
- docs/components/control/signed-in.mdx
- docs/components/control/signed-out.mdx
- docs/components/organization/organization-profile.mdx
- docs/components/unstyled/sign-in-with-metamask.mdx
- docs/components/user/user-button.mdx
- docs/components/user/user-profile.mdx
> (components) update examples; add app router examples

- docs/authentication/configuration/restrictions.mdx
https://linear.app/clerk/issue/DOCS-10169/search-for-allowlist-not-linking-to-restrictions-page
> (restrictions) boost page search ranking

- docs/authentication/configuration/restrictions.mdx
https://linear.app/clerk/issue/DOCS-10041/update-blocklist-description-to-include-sign-ins
> (restrictions) blocklist also blocks sign ins

- CONTRIBUTING.md
- It's a bit complicated now with the sdk selector.
- Added a section to the contributing.md on modifying the available sdks.
> (CONTRIBUTING.md) Add docs surrounding the SDK selector

- docs/how-clerk-works/overview.mdx
-
There were some slight inaccuracies and unclear parts in the handshake description that I aimed to clear up.
> Handshake logic corrections for HCW

- docs/backend-requests/resources/session-tokens.mdx
- docs/organizations/create-roles-permissions.mdx
- docs/organizations/roles-permissions.mdx
- docs/versioning/available-versions.mdx
> (wip) session token v2 docs

- docs/backend-requests/resources/session-tokens.mdx
- docs/organizations/create-roles-permissions.mdx
- docs/organizations/roles-permissions.mdx
- docs/versioning/available-versions.mdx
This reverts commit 0d0eb1c2d964d23535f9cb4f33649ce5f7f0728d.
-
- 
-
> Revert "(wip) session token v2 docs (#2173)"

- docs/backend-requests/resources/session-tokens.mdx
- docs/organizations/org-slugs-in-urls.mdx
- docs/references/nextjs/authjs-migration.mdx
Missed a few things regarding the new v2 session token
> session token v2 followup

- docs/how-clerk-works/overview.mdx
This PR corrects the video dimensions in the `docs/how-clerk-works/overview.mdx` file, to ensure that they match each video’s natural size.
> Correct video dimensions in `docs/how-clerk-works/overview.mdx`

- docs/references/go/overview.mdx
https://linear.app/clerk/issue/DOCS-9512/feedback-for-referencesgooverview
> (/go/overview) clarify use of $ variable

- docs/account-portal/disable-account-portal.mdx
https://linear.app/clerk/issue/DOCS-9914/feedback-for-customizationaccount-portaldisable-account-portal
> (account-portal/overview) clarify instructions for disabling account portal

- docs/_partials/hooks/use-auth.mdx
- docs/references/expo/read-session-user-data.mdx
- docs/references/tanstack-react-start/read-session-data.mdx
https://linear.app/clerk/issue/DOCS-10272/update-referencesexporead-session-user-data
> Update useAuth example to include getToken example usage

- docs/references/nextjs/rendering-modes.mdx
https://linear.app/clerk/issue/DOCS-9669/feedback-for-referencesnextjsrendering-modes
> (rendering-modes) clarify usage of multiple clerkproviders

- docs/billing/overview.mdx
- docs/components/pricing-table.mdx
Updates for https://github.com/clerk/clerk-docs/pull/2200
> billing: Updates for guide in review

- docs/authentication/social-connections/overview.mdx
- https://clerk.com/docs/pr/2228/authentication/social-connections/overview#configure-additional-o-auth-scopes
- Fixes link to be a hash to the heading on the current page
-
> fix enabling a new social connection link

- docs/components/pricing-table.mdx
- https://clerk.com/docs/pr/2227/components/pricing-table#properties
- Adds `newSubscriptionRedirectUrl` to PricingTable properties.
-
> chore: Add newSubscriptionRedirectUrl property to PricingTable

- docs/integrations/databases/firebase.mdx
> Fixed typo

- docs/advanced-usage/using-proxies.mdx
https://linear.app/clerk/issue/DOCS-10340/customer-feedback-about-proxying-doc
> clarify that proxying doesnt work in development

- docs/users/creating-users.mdx
- docs/users/deleting-users.mdx
- docs/users/metadata.mdx
- docs/users/user-impersonation.mdx
https://linear.app/clerk/issue/DOCS-10362/feedback-for-usersdeleting-users
> (/users) clarify usage of backend sdk

- docs/custom-flows/enterprise-connections.mdx
https://linear.app/clerk/issue/DOCS-10417/update-custom-flow-doc-for-enterprise-connections
> Remove callout about expo not supporting OIDC

- docs/organizations/overview.mdx
- https://clerk.com/docs/pr/2252
Updates the organization overview to link to the newest orgs repo with the recent app examples
> fix(organizations): Update overview callout to point to orgs repo

- docs/authentication/configuration/sign-up-sign-in-options.mdx
- docs/authentication/enterprise-connections/account-linking.mdx
- docs/authentication/enterprise-connections/overview.mdx
- docs/authentication/web3/coinbase-wallet.mdx
- docs/authentication/web3/metamask.mdx
- docs/authentication/web3/okx-wallet.mdx
- docs/custom-flows/add-email.mdx
- docs/custom-flows/email-links.mdx
- docs/custom-flows/email-password-mfa.mdx
- docs/custom-flows/email-password.mdx
- docs/custom-flows/email-sms-otp.mdx
- docs/custom-flows/overview.mdx
- docs/custom-flows/passkeys.mdx
- docs/customization/elements/examples/sign-in.mdx
- docs/customization/elements/examples/sign-up.mdx
- docs/hooks/use-reverification.mdx
- docs/organizations/invitations.mdx
- docs/references/expo/passkeys.mdx
- docs/references/expo/use-local-credentials.mdx
- docs/references/javascript/sign-in.mdx
- docs/references/javascript/sign-up.mdx
- docs/references/javascript/user.mdx
- docs/security/email-link-protection.mdx
- docs/security/password-protection.mdx
- docs/testing/test-emails-and-phones.mdx
This PR reflects the UI updates for the Email, Phone, Username page in the Clerk Dashboard.
> Updates for Email, Phone, Username page in Clerk Dashboard

- docs/errors/overview.mdx
Recently, the errors docs were updated and are now auto generated !
This PR updates the overview to point to the newly created pages.
> Update Errors overview

- docs/integrations/analytics/google-analytics.mdx
-
It's currently unclear whether customers need to set up GA tags themselves or if our integration does this for them. Reference: https://clerkinc.slack.com/archives/C07JK3YT2G2/p1748602441988639?thread_ts=1748008158.615249&cid=C07JK3YT2G2
Note is added to provide clarity on how GA tags need to be handled with this integration
> Added note to clarify GA tag handling

- vercel.json
- We need stronger caching for the public assets to reduce server costs
- added a `vercel.json` config file to define custom headers for the public assets
> Add a vercel.json config file

- docs/integrations/overview.mdx
- docs/integrations/vercel-marketplace.mdx
- docs/manifest.json
- **New file:** `docs/integrations/vercel-marketplace.mdx` - Complete documentation for Clerk's Vercel Marketplace integration
- **Updated:** `docs/integrations/overview.mdx` - Added Vercel integration to main integrations page
- Installation through Vercel Marketplace
- Automatic environment variable sync
- Team/role management
- Project connection workflow
- Billing and limitations
> feat: Vercel integration docs

- docs/components/protect.mdx
- https://clerk.com/docs/pr/aa-update-protect/components/protect
The `<Protect />` component always performs authentication checks. But the docs currently only cover authorization checks. This PR adds missing content surrounding authentication checks.
> (components/protect) Include explanation of authentication checks

- docs/components/unstyled/sign-in-button.mdx
- docs/components/unstyled/sign-up-button.mdx
- https://clerk.com/docs/pr/aa-docs-10576/components/unstyled/sign-in-button
- https://clerk.com/docs/pr/aa-docs-10576/components/unstyled/sign-up-button
https://linear.app/clerk/issue/DOCS-10576/improve-explanation-of-account-portal
> Mention Account Portal usage in SignInButton/SignUpButton docs

- docs/billing/b2b-saas.mdx
> chore: Update usage of PricingTable in B2B setup

- docs/customization/variables.mdx
Reverts clerk/clerk-docs#2347
This hadn't been released yet. Missed adding do not merge notice 😞
> Revert "Add css variable support docs"

- docs/references/javascript/session.mdx
- https://clerk.com/docs/pr/ss-docs-10557/references/javascript/session#check-authorization
Linear ticket: https://linear.app/clerk/issue/DOCS-10557/sessioncheckauthorization-params-and-examples-are-incorrect
The previous listed types of `checkAuthorization` were incomplete and slightly misleading about how reverification works. This PR aims at clarifying that `checkAuthorization` doesn't always require a role or permission, but can sometimes take the reverification param as well. 
- Refined the explanation of `checkAuthorization` to align with all three params
- Added the `reverification` type in the `CheckAuthorizationParams` object + added the bit about reverification being in public beta to align with what's in here: https://clerk.com/docs/references/backend/types/auth-object#reverific …
> Improve session.CheckAuthorizationParams explanation and reverification examples

- docs/custom-flows/email-password-mfa.mdx
- docs/references/sdk/types.mdx
-
This pull request updates the documentation to include support for Android/Kotlin in the context of MFA flows and SDK examples. It adds Kotlin code snippets for implementing MFA sign-in functionality and updates references to include Android/Kotlin as supported platforms.
* Added "Android" as a tab option in the MFA guide under `docs/custom-flows/email-password-mfa.mdx`.
* Included Kotlin code snippets for implementing MFA sign-in functionality, including `MFASignInView` and `MFASignInViewModel` classes. These snippets demonstrate handling MFA states such as unverified, needs second factor, and verified.
* Updated supported platform examples in `docs/references/sdk/types.mdx` to include Android/Kotlin alongside existing platforms like iOS/Swift.
> [DO NOT MERGE] Update `email-password-mfa.mdx` to include android samples

- docs/custom-flows/oauth-connections.mdx
-
This pull request updates the documentation for custom OAuth flows by adding support for Android. It introduces a new tab in the code examples and provides Kotlin implementations for an OAuth view and its corresponding view model.
* [`docs/custom-flows/oauth-connections.mdx`](diffhunk://#diff-b07fbdfb37e670ebef908aa62b0abe4673b02349ddc15acbe94263b516993d15L14-R14): Added an "Android" tab to the list of supported platforms in the example code section.
* [`docs/custom-flows/oauth-connections.mdx`](diffhunk://#diff-b07fbdfb37e670ebef908aa62b0abe4673b02349ddc15acbe94263b516993d15R205-R248): Included Kotlin code examples for implementing OAuth functionality on Android, featuring an `OAuthView` composable and an `OAuthViewModel` class. These examples demonstrate signing in with Google as an …
> [DO NOT MERGE] Update `oauth-connections.mdx` to have Android samples

- data/api_errors.json
-
- 
Automatically generated latest updates to the API Errors JSON file.
-
> chore: Update API Errors

- prompts/react-vite-quickstart.md
-
The react quickstart got some updates, and this brings the prompt up to date.
> chore: update react prompt to match quickstart

- docs/references/ios/clerk-theme.mdx
- https://clerk.com/docs/pr/mike-update-clerk-theme-docs/references/ios/clerk-theme
- Mosaic recently updated some of their color variables, this updates the iOS docs to match.
> update clerk theme docs

- docs/_partials/hooks/hook-list.mdx
- docs/hooks/use-checkout.mdx
- docs/hooks/use-payment-element.mdx
- docs/hooks/use-payment-methods.mdx
- docs/hooks/use-plans.mdx
- docs/hooks/use-subscription.mdx
-
Adds new billing hooks to the hooks overview page
> add new billing hooks to hooks overview

- docs/quickstarts/ios.mdx
> add your app to native apps page step to quickstart

- docs/references/android/overview.mdx
- https://clerk.com/docs/pr/nick-android-broken-link/references/android/overview
- Broken link to https://clerk-android.clerkstage.dev
-
> Fix broken link

- docs/customization/themes.mdx
- https://clerk.com/docs/pr/alexcarpenter-shadcn-theme-v4-notice/customization/themes#shadcn-theme
- Add notice to shadcn theme about tailwind css v4 usage, and recommendation when using v3
-
> add shadcn v4 usage notice

- docs/billing/free-trials.mdx
Same content as #2532, but we're structuring it by phase of the trial now and cleaning up some of the flow.
-
- 
-
> feat: Free trial docs revision

- docs/components/overview.mdx
- docs/custom-flows/forgot-password.mdx
- https://clerk.com/docs/pr/elef-update-components-overview/components/overview
- 
-
> chore: Add billing components to overview

- docs/references/javascript/sign-up.mdx
- docs/references/javascript/types/external-account.mdx
- docs/references/javascript/user.mdx
-
Inspired by stale PR from external contributor: https://github.com/clerk/clerk-docs/pull/2434
Adds a reference link so users can find more info about usernames
> Update property description for a users username

- redirects/static/docs.json
- https://clerk.com/docs/pr/fix-redirects-4/guides/configure/auth-strategies/social-connections/oauth
- /docs/guides/configure/auth-strategies/social-connections/oauth is 404ing
- Add redirect
> Add redirect to social connections overview

- flags.json
With https://github.com/clerk/clerk/pull/1647 merged we no longer need these flags.
> POST IA - Remove no longer used flags

- docs/guides/development/custom-flows/authentication/bot-sign-up-protection.mdx
-
Removes Next.js-specific code to generalize the guide for any SDK-usage
> update captcha custom flow

- docs/guides/development/troubleshooting/help-support/browser-replay.mdx
- docs/guides/how-clerk-works/support-replays.mdx
- docs/manifest.json
- https://clerk.com/docs/pr/dsfeat-support-jam-har/guides/how-clerk-works/support-replays
- This adds a doc that support can link to that describes how to record using the Jam extension or how to produce a HAR with sensitive values.
- Added a new doc
> Add doc on generating Jam and HAR

- docs/guides/billing/overview.mdx
-
This cuts FAQ down by half
- 
-
> docs(billing): moving questions from /billing to the overview

- docs/guides/development/custom-flows/authentication/oauth-connections.mdx
> Fix return statement formatting in OAuth connections guide

- docs/guides/development/customize-redirect-urls.mdx
- https://clerk.com/docs/pr/aa-docs-10793/guides/development/customize-redirect-urls
A user was confused about customizing redirect URLs
https://linear.app/clerk/issue/DOCS-10793/feedback-for-guidescustom-redirects
Updates the wording in the introduction paragraph (explanatory paragraph) to be more palatable
> Update explanation of redirect URLs

- docs/getting-started/core-concepts.mdx
- docs/guides/organizations/overview.mdx
- docs/guides/sessions/session-tokens.mdx
Small update to the core concepts guide to mention session tokens, and point users to the "How Clerk works" guide
> Update core concepts guide
